### ISSUE TITLE
MSR READ Failed

### ISSUE THREAD

**Issue by sheepdestroyer** [intel/thermal_daemon#10]
Hi, i tried running thermal daemon from git with Fedora 18 on a Lenovo X220 with SandyBridge CPU (2.7Ghz, 3.4GHz max turbo).

My kernel is 3.10-rc5 with CONFIG_X86_MSR=y, CONFIG_X86_INTEL_PSTATE=y and CONFIG_INTEL_POWERCLAMP=y

Throttling is weird : while compiling kernel, first my cpu reach 95 C during one or two minute on turbo (3.2GHz) then it mainly reduce speed to 2.2GHz with temp reaching only 80 C despite having 84.5 C defined in thermal_set_point.conf

Thermald reports some MSR related error messages.
Did i miss something in my kernel configuration or is that a thermald bug?

Started Thermal Daemon Service.
13 CPUID levels; family:model:stepping 0x6:2a:7 (6:42:7)
Polling mode is enabled: 4
Found Intel pstate driver
RAPL device for cpu 0
sysfs read failed 0/msr
MSR READ Failed
Read set point 84500
DTS package temp thermal zone not found, Requires polling !!
Default DTS processing for cpus mask = ffff
node type: Element, name: CoolingDevice value: CDEV_INTEL_RAPL_DRIVER
node type: Element, name: CoolingDevice value: CDEV_RAPL
node type: Element, name: CoolingDevice value: CDEV_INTEL_PSTATE_DRIVER
node type: Element, name: CoolingDevice value: CDEV_MSR_TURBO_STATES
node type: Element, name: CoolingDevice value: CDEV_MSR_PSTATES_PARTIAL
node type: Element, name: CoolingDevice value: CDEV_TURBO_ON_OFF
node type: Element, name: CoolingDevice value: CDEV_POWER_CLAMP
node type: Element, name: CoolingDevice value: CDEV_CPU_FREQ
node type: Element, name: CoolingDevice value: CDEV_MSR_PSTATES
node type: Element, name: CoolingDevice value: CDEV_T_STATES
CDEVS order specified in thermal-cdev-order.xml
FD = 7
Current user preference is 0
thd_engine_thread begin

**Comment by spandruvada** [comment]
No longer using MSR reads.
