### ISSUE TITLE
Failed to start Thermald in Ubuntu 16

### ISSUE THREAD

**Issue by ankithprabhas** [intel/thermal_daemon#100]
When i try to start thermal_daemon in my ubuntu 16 it says 

> start: Unable to connect to Upstart: Failed to connect to socket /com/ubuntu/upstart: Connection refused

Ubuntu switched to systemd as its service framework starting in 15.04 for all flavors, including Desktop and Server.
When i switched to upstart from systemd it worked good.
I would say that it is recommended to change your upstart jobs/scripts to systemd jobs.
Else, everytime user must switch to Upstart by removing systemd. That would become too laborious.

**Comment by spandruvada** [comment]
On Mon, 2016-08-15 at 03:26 -0700, ankithprabhas wrote:
> When i try to start therma_deamon in my ubuntu 16.x it says
> start: Unable to connect to Upstart: Failed to connect to socket
> /com/ubuntu/upstart: Connection refused
> Ubuntu switched to systemd as its service framework starting in 15.04
> for all flavors, including Desktop and Server.
Correct.

> When i switched to upstart from systemd it worked good.
> I would say that it is recommended to change your upstart
> jobs/scripts to systemd jobs.
Ubuntu maintains its own thermald packages for every version. They will
take care of how to start. The older version with upstart is still
used.

But we can certainly update the README.txt for older and newer version.
If you want you can submit change, with instruction for older and newer
version.

**Comment by spandruvada** [comment]
Updated README.
