### ISSUE TITLE
sysfs write failed /sys/devices/virtual/powercap/intel-rapl/intel-rapl:0/constraint_0_power_limit_uw

### ISSUE THREAD

**Issue by twu2** [intel/thermal_daemon#113]
Debian testing x86_64
i7-4770
thermald 1.5.4-2

after CPU full loading, got  a lots of message as title.
running under debug mode, it seems to write a minus value, it reject by sysfs.

>cdev at index 15:rapl_controller
 \>\>thd_cdev_set_state index:15 state:0 :3:1:16777215
thd_cdev_set_15:curr state -664288000 max state -664288000
op->device:rapl_controller -834750512
set cdev state index 15 state -834750512 wr:-885717296
sysfs write failed /sys/devices/virtual/powercap/intel-rapl/intel-rapl:0/constraint_0_power_limit_uw
Set : threshold:80000, temperature:39000, cdev:15(rapl_controller), curr_state:-664288000, max_state:-664288000

and at program begging, also got minus max limit:

>thd_read_default_cooling devices loaded 15 cdevs
Default constraint power limit is more than max power 3409250000:84000000
powercap RAPL max power limit range 3409250000
RAPL max limit -664288000 increment: 170462512

in src/thd_cdev_rapl.cpp, I found new_state, max_state, min_state, curr_stat are declare as int, but phy_max is declare as unsigned long, after some calculator, it might cause integer overflow for the int variable, so we got minus number.

**Comment by twu2** [comment]
my ugly patch to fix this issue:

[x.patch.txt](https://github.com/01org/thermal_daemon/files/769100/x.patch.txt)

**Comment by spandruvada** [comment]
Sorry, traveling for next two weeks. So can't look at the change.

Thanks,
Srinivas

**Comment by elad661** [comment]
I'm getting the same error (and a bunch of other ones) on Fedora 26 running on a Dell XPS 13 (9343) with an i7-5500U CPU. Is this the same issue? If not, should I open another one, or does this just mean my OS / hardware is not supported by thermald?

```
thermald[18730]: Using generated /var/run/thermald/thermal-conf.xml.auto
thermald[18730]: sysfs write failed /sys/devices/virtual/powercap/intel-rapl/intel-rapl:0/enabled
thermald[18730]: sysfs read failed constraint_0_max_power_uw
thermald[18730]: csys_fs::read exception /sys/class/thermal/thermal_zone4/trip_point_0_hyst
thermald[18730]: csys_fs::read exception /sys/class/thermal/thermal_zone4/trip_point_1_hyst
thermald[18730]: csys_fs::read exception /sys/class/thermal/thermal_zone4/trip_point_2_hyst
thermald[18730]: csys_fs::read exception /sys/class/thermal/thermal_zone4/trip_point_3_hyst
thermald[18730]: csys_fs::read exception /sys/class/thermal/thermal_zone4/trip_point_4_hyst
thermald[18730]: sysfs write failed /sys/devices/virtual/powercap/intel-rapl/intel-rapl:0/enabled
thermald[18730]: sysfs write failed /sys/devices/virtual/powercap/intel-rapl/intel-rapl:0/constraint_0_power_limit_uw
```

**Comment by spandruvada** [comment]
On Sun, 2017-07-02 at 17:02 -0700, Elad Alfassa wrote:
> I'm getting the same error (and a bunch of other ones) on Fedora 26
> running on a Dell XPS 13 (9343) with an i7-5500U CPU. Is this the
> same issue? If not, should I open another one, or does this just mean
> my OS / hardware is not supported by thermald?
The HW is supported, these errors can be ignored. The platform is not
exposing these and kernel driver doesn't have a good way not to expose
them.

Thanks,
Srinivas

**Comment by spandruvada** [comment]
The original issue is addressed in the master branch and will be part of 1.7 release.
csys_fs::read exception /sys/class/thermal/thermal_zone4/trip_point_0_hyst needs to be fixed in kernel.
