### ISSUE TITLE
Kaby lake support?

### ISSUE THREAD

**Issue by darrenhaken** [intel/thermal_daemon#114]
I just installed this on a Kaby Lake laptop but the daemon says my CPU is unsupported.
Do you know when you'll have support for Kaby Lake or is there a config I can change to already make it work?

**Comment by spandruvada** [comment]
On Fri, 2017-02-24 at 01:15 -0800, Darren Haken wrote:
> I just installed this on a Kaby Lake laptop but the daemon says my
> CPU is unsupported.
> Do you know when you'll have support for Kaby Lake or is there a
> config I can change to already make it work?
The next version will have support for this. Meanwhile you can add
the following command line option to thermald in thermald.conf file.

--ignore-cpuid-check

**Comment by darrenhaken** [comment]
@spandruvada any idea when the next version will be available?

**Comment by bhack** [comment]
Seems supported by version 1.6 can you check?

**Comment by spandruvada** [comment]
It is added in 1.6.
