### ISSUE TITLE
i7-5700HQ (Broadwell) Unsupported cpu model.

### ISSUE THREAD

**Issue by emield12** [intel/thermal_daemon#116]
Hello,
When I run thermald it gives me the following error:

```
20 CPUID levels; family:model:stepping 0x6:47:1 (6:71:1)
 Need Linux PowerCap sysfs 
Unsupported cpu model, use thermal-conf.xml file or run with --ignore-cpuid-check 
THD engine start failed
```

Information in /proc/cpuinfo: http://pastebin.com/Hf3kqDPk 
My cpu model number is 0x47. This number isn't listed in thd_engine.cpp file: 

```
// Add any tested platform ids in this table
static supported_ids_t id_table[] = {
		{ 6, 0x2a }, // Sandybridge
		{ 6, 0x3a }, // IvyBridge
		{ 6, 0x3c }, // Haswell
		{ 6, 0x45 }, // Haswell ULT
		{ 6, 0x46 }, // Haswell ULT
		{ 6, 0x3d }, // Broadwell
		{ 6, 0x37 }, // Valleyview BYT
		{ 6, 0x4c }, // Brasewell
		{ 6, 0x4e }, // skylake
		{ 6, 0x5e }, // skylake
		{ 6, 0x5c }, // Broxton

		{ 0, 0 } // Last Invalid entry
};
```
So is my cpu type unsupported? This seems odd, because the previous and next generations are supported. Intel Broadwell generation is even showing up in the list...

For the moment I'm running thermald with "--ignore-cpuid-check" argument. But is thermald working correctly when you add this argument?

Thanks,
Emiel

**Comment by spandruvada** [comment]
This seems that this is a desktop type device with high end graphics part. 
Is it a laptop?

Thanks,
Srinivas
________________________________________

**Comment by emield12** [comment]
Yes, it's a laptop: MSI PE60 2QE.

**Comment by spandruvada** [comment]
On Wed, 2017-03-01 at 08:24 -0800, emield12 wrote:
> Yes, it's a laptop: MSI PE60 2QE.
OK, I will add this id.

Thanks,
Srinivas

**Comment by spandruvada** [comment]
Fixed.
