### ISSUE TITLE
I7-620m (Arrandale) is unsupported

### ISSUE THREAD

**Issue by mex20** [intel/thermal_daemon#118]
When I try to run thermald.service using 'sudo systemctl status thermald.service' I get the below information of the program failing because my cpu is unsupported:
[thermaldstatus.txt](https://github.com/01org/thermal_daemon/files/862886/thermaldstatus.txt)

Here is my /proc/cpuinfo output: 
[cpuinfo.txt](https://github.com/01org/thermal_daemon/files/862895/cpuinfo.txt)

This is a 15" mid 2010 macbook pro model 6,2 with an Nvidia GT215m (GT 320m) gpu and an Intel Integrated GPU.

Please let me know if you need any more information.

**Comment by spandruvada** [comment]
Can you add option to thermald.service (You can find the location of the file by executing "sudo systemctl status thermald.service")

--ignore-cpuid-check

If it doesn't cause issue after using for sometime, let me know, I can add the model number.
