### ISSUE TITLE
csys_fs::read exception /sys/class/thermal/thermal_zone[1-4]/trip_point_[0-3]_hyst

### ISSUE THREAD

**Issue by ArchangeGabriel** [intel/thermal_daemon#119]
Not sure if this is worth reporting debugging or what it means, but I get this in thermald debug output:
```
22 CPUID levels; family:model:stepping 0x6:5e:3 (6:94:3)
Polling mode is enabled: 4
Using generated /var/run/thermald/thermal-conf.xml.auto
sysfs read failed constraint_0_max_power_uw
csys_fs::read exception /sys/class/thermal/thermal_zone3/trip_point_0_hyst
csys_fs::read exception /sys/class/thermal/thermal_zone3/trip_point_1_hyst
csys_fs::read exception /sys/class/thermal/thermal_zone3/trip_point_2_hyst
csys_fs::read exception /sys/class/thermal/thermal_zone3/trip_point_3_hyst
csys_fs::read exception /sys/class/thermal/thermal_zone1/trip_point_0_hyst
csys_fs::read exception /sys/class/thermal/thermal_zone1/trip_point_1_hyst
csys_fs::read exception /sys/class/thermal/thermal_zone1/trip_point_2_hyst
csys_fs::read exception /sys/class/thermal/thermal_zone1/trip_point_3_hyst
csys_fs::read exception /sys/class/thermal/thermal_zone4/trip_point_0_hyst
csys_fs::read exception /sys/class/thermal/thermal_zone4/trip_point_1_hyst
csys_fs::read exception /sys/class/thermal/thermal_zone4/trip_point_2_hyst
csys_fs::read exception /sys/class/thermal/thermal_zone4/trip_point_3_hyst
csys_fs::read exception /sys/class/thermal/thermal_zone2/trip_point_0_hyst
csys_fs::read exception /sys/class/thermal/thermal_zone2/trip_point_1_hyst
csys_fs::read exception /sys/class/thermal/thermal_zone2/trip_point_2_hyst
csys_fs::read exception /sys/class/thermal/thermal_zone2/trip_point_3_hyst
```

**Comment by devscott** [comment]
I have the same issue: 
thermald[6043]: 22 CPUID levels; family:model:stepping 0x6:9e:9 (6:158:9)
thermald[6043]: Polling mode is enabled: 4
systemd[1]: Started Thermal Daemon Service.
thermald[6043]: sysfs read failed constraint_0_max_power_uw
thermald[6043]: csys_fs::read exception /sys/class/thermal/thermal_zone2/trip_point_0_hyst
thermald[6043]: csys_fs::read exception /sys/class/thermal/thermal_zone2/trip_point_1_hyst
thermald[6043]: csys_fs::read exception /sys/class/thermal/thermal_zone2/trip_point_2_hyst
thermald[6043]: csys_fs::read exception /sys/class/thermal/thermal_zone2/trip_point_3_hyst
thermald[6043]: csys_fs::read exception /sys/class/thermal/thermal_zone2/trip_point_4_hyst

**Comment by Peter-Levine** [comment]
I'm also getting this with a Dell Inspiron 5577 gaming laptop with an Intel(R) Core(TM) i7-7700HQ processor running Gentoo Linux with kernel 4.11.4:

```
Jun 21 23:40:06 Laptop-PC systemd[1]: Starting Thermal Daemon Service...
Jun 21 23:40:06 Laptop-PC thermald[26468]: 22 CPUID levels; family:model:stepping 0x6:9e:9 (6:158:9)
Jun 21 23:40:06 Laptop-PC thermald[26468]: Polling mode is enabled: 4
Jun 21 23:40:06 Laptop-PC thermald[26468]: Using generated /var/lib/run/thermald/thermal-conf.xml.auto
Jun 21 23:40:06 Laptop-PC thermald[26468]: sysfs read failed constraint_0_max_power_uw
Jun 21 23:40:06 Laptop-PC thermald[26468]: csys_fs::read exception /sys/class/thermal/thermal_zone4/trip_point_0_hyst
Jun 21 23:40:06 Laptop-PC thermald[26468]: csys_fs::read exception /sys/class/thermal/thermal_zone4/trip_point_1_hyst
Jun 21 23:40:06 Laptop-PC thermald[26468]: csys_fs::read exception /sys/class/thermal/thermal_zone4/trip_point_2_hyst
Jun 21 23:40:06 Laptop-PC systemd[1]: Started Thermal Daemon Service.
```

When running something like 
> cat /sys/class/thermal/thermal_zone4/trip_point_0_hyst

 on the command line, I get 

> cat: /sys/class/thermal/thermal_zone4/trip_point_0_hyst: Input/output error

**Comment by spandruvada** [comment]
This is an issue with Linux kernel framework. The hysteresis operation needs to be specified even if any one of the trip has a hysteresis. For the other read will fail.
I can't fix in thermald except removing error print.
So will look for fixing in kernel.

**Comment by trulyliu** [comment]
I met the same error on Ubuntu 16.04 with kernel 4.10.0-28-generic on an Lenovo Yoga 910 laptop.
My CPU is kabyLake I7
Because of this error, thermald does not use the configuration file under /etc/thermal/ directory.
Instead it use a generated config file under /var/run/thermald/ .
It leads thermald does not work.
Simply disable intel_rapl kernel module fixed this issue.

`cat /etc/modprobe.d/blacklist-intel_rapl.conf
blacklist intel_rapl
install intel_rapl /bin/false
`
ThermalD will use intel_pstate or intel_powerclamp driver.

**Comment by spandruvada** [comment]
The error is subject in the email has nothing to do with intel-rapl. So
I guess you just replied to this email.

But your case is interesting. The generated file is much better unless
you want to change as this is defined by platform.

So I want to get your logs and generated file.
Please do
# systemctl stop thermald
# thermald --no-daemon --loglevel=debug

and paste the log along with generated file in /var/run/thermald..

Thanks,
Srinivas
