### ISSUE TITLE
autoconf for Intel 3350 (ASUS E403N)

### ISSUE THREAD

**Issue by bosim** [intel/thermal_daemon#121]
config autogeneration fails on an Intel 3350 machine. 
```
Apr 07 19:21:11 alpha.geekworld.lan thermald[2879]: 21 CPUID levels; family:model:stepping 0x6:5c:9 (6:92:9)
Apr 07 19:21:11 alpha.geekworld.lan thermald[2879]: Polling mode is enabled: 4
Apr 07 19:21:11 alpha.geekworld.lan thermald[2879]: Using generated /var/run/thermald/thermal-conf.xml.auto
Apr 07 19:21:11 alpha.geekworld.lan thermald[2879]: sysfs read failed constraint_0_max_power_uw
Apr 07 19:21:12 alpha.geekworld.lan thermald[2879]: XML zone: invalid sensor type SEN1
Apr 07 19:21:12 alpha.geekworld.lan thermald[2879]: Zone update failed: unable to bind
Apr 07 19:21:12 alpha.geekworld.lan thermald[2879]: XML zone: invalid sensor type GEN2
Apr 07 19:21:12 alpha.geekworld.lan thermald[2879]: Zone update failed: unable to bind
Apr 07 19:21:12 alpha.geekworld.lan thermald[2879]: XML zone: invalid sensor type GEN3
Apr 07 19:21:12 alpha.geekworld.lan thermald[2879]: Zone update failed: unable to bind
Apr 07 19:21:12 alpha.geekworld.lan thermald[2879]: XML zone: invalid sensor type GEN4
Apr 07 19:21:12 alpha.geekworld.lan thermald[2879]: Zone update failed: unable to bind
```

**Comment by spandruvada** [comment]
On Fri, 2017-04-07 at 10:29 -0700, Bo Simonsen wrote:
> config autogeneration fails on an Intel 3350 machine.
> Apr 07 19:21:11 alpha.geekworld.lan thermald[2879]: 21 CPUID levels;
> family:model:stepping 0x6:5c:9 (6:92:9)
> Apr 07 19:21:11 alpha.geekworld.lan thermald[2879]: Polling mode is
> enabled: 4
> Apr 07 19:21:11 alpha.geekworld.lan thermald[2879]: Using generated
> /var/run/thermald/thermal-conf.xml.auto
> Apr 07 19:21:11 alpha.geekworld.lan thermald[2879]: sysfs read failed
> constraint_0_max_power_uw
> Apr 07 19:21:12 alpha.geekworld.lan thermald[2879]: XML zone: invalid
> sensor type SEN1
> Apr 07 19:21:12 alpha.geekworld.lan thermald[2879]: Zone update
> failed: unable to bind
> Apr 07 19:21:12 alpha.geekworld.lan thermald[2879]: XML zone: invalid
> sensor type GEN2
> Apr 07 19:21:12 alpha.geekworld.lan thermald[2879]: Zone update
> failed: unable to bind
> Apr 07 19:21:12 alpha.geekworld.lan thermald[2879]: XML zone: invalid
> sensor type GEN3
> Apr 07 19:21:12 alpha.geekworld.lan thermald[2879]: Zone update
> failed: unable to bind
> Apr 07 19:21:12 alpha.geekworld.lan thermald[2879]: XML zone: invalid
> sensor type GEN4
> Apr 07 19:21:12 alpha.geekworld.lan thermald[2879]: Zone update
> failed: unable to bind
> 
Looks like some configuration is missing.
What is the dump of

# grep -r . /sys/class/thermal/*
Also
# acpidump > acpi.out
and send acpi.out

Thanks,
Srinivas

**Comment by spandruvada** [comment]
If still an issue, please reopen.
