### ISSUE TITLE
access of thd_engine after it has been deleted

### ISSUE THREAD

**Issue by ColinIanKing** [intel/thermal_daemon#123]
the following code deletes thd_engine but then accesses it via get_control_mode() - is that correct?

gboolean thd_dbus_interface_reinit(PrefObject *obj, GError **error) {
        bool exclusive_control = false;

        thd_engine->thd_engine_terminate();
        sleep(1);
        delete thd_engine;
        sleep(2);
        if (thd_engine->get_control_mode() == EXCLUSIVE)
                exclusive_control = true;

**Comment by spandruvada** [comment]
Obviously a blunder. Fixed and pushed. Thanks for finding.

**Comment by ColinIanKing** [comment]
Thanks!  I've packaged this up and it will land in Debian and Ubuntu today.
