### ISSUE TITLE
Meaning of Cooling Device IncDecStep 

### ISSUE THREAD

**Issue by Konfekt** [intel/thermal_daemon#126]
In the man page,
```xml
<!--  Cooling  device  can  be  specified  by a type and optionally a sysfs path.
If the type  is  already  present  in  thermal sysfs,  there  is  no  need of a path.
Compensation can use min/max and step size to increasing cool the system.
Debounce period can be used to force a waiting period for action.
-->
<Type>example_cooling_device</Type>
<MinState>0</MinState>
<IncDecStep>10</IncDecStep>
<ReadBack> 0 </ReadBack>
<MaxState>50</MaxState>
<DebouncePeriod>5000</DebouncePeriod>
```
there is the option `<IncDecStep>10</IncDecStep>`.

At which temperatures does it increase or decrease which value?
For example, if
```xml
<Path>/sys/devices/platform/thinkpad_hwmon/pwm1</Path>
```
then at which temperatures does is increase the value of `/sys/devices/platform/thinkpad_hwmon/pwm1` ?

**Comment by spandruvada** [comment]
This step size is not for the temperature but for the compensation. Suppose the value you write to sysfs is x, then next value is x+inc_dec_step and opposite during the decrease.
Temperature is as a trip point in zone when this device is activated. Like in the example in man page is 75C.

**Comment by Konfekt** [comment]
So sysfs could be `/sys/devices/platform/thinkpad_hwmon/pwm1`, and then `/sys/devices/platform/thinkpad_hwmon/pwm1` would be increased by `10` if IncDecStep is `10` at every trip point?

**Comment by spandruvada** [comment]
On Fri, 2017-06-30 at 05:37 +0000, Konfekt wrote:
> So sysfs could be /sys/devices/platform/thinkpad_hwmon/pwm1, and then
> /sys/devices/platform/thinkpad_hwmon/pwm1 would be increased by 10 if
> IncDecStep is 10 at every trip point?
As long as the temperature is >= trip then it will increment +10 step
here.

Thanks,
Srinivas

**Comment by Konfekt** [comment]
On what event does it increment by 10 as long as temperature is >= trip? On every increase of the measured CPU temperature by 1?

**Comment by spandruvada** [comment]
On Tue, 2017-07-04 at 09:30 +0000, Konfekt wrote:
> On what event does it increment by 10 as long as temperature is >=
> trip? On every increase of the measured CPU temperature by 1?
That depends on your polling interval. Default is 5 sec. So when
temperature is polled, it will start. It will start increasing
exponentially going up, but will come down step wise with the
increments.
