### ISSUE TITLE
Use thinkpad_acpi interface with thermal_daemon

### ISSUE THREAD

**Issue by Konfekt** [intel/thermal_daemon#127]
There are to options to control fan speed by thinkfan: via `pwm_fan` and `tp_fan`. 

- The former writes a byte to `/sys/class/hwmon/hwmon1/device/pwm1` say, whereas 
- the latter needs the command 

```sh
echo level 1 | sudo tee /proc/acpi/ibm/fan
```

Does thermald allow for setting up a cooling device using the latter? The latter has the advantage of allowing for the level `127`, disengaged, which runs the fan at highest possible speed and is not available via the former `pwm` method.

**Comment by spandruvada** [comment]
Not currently, but I see the advantage, so will plan for this and to the queue for the list feature additions.
