### ISSUE TITLE
intel_pstate frequency question

### ISSUE THREAD

**Issue by khumarahn** [intel/thermal_daemon#128]
Hi,

I use thermald to make silent a desktop computer with bad cooling design. The processor is i7-3770. Things used to work wonderfully for a rather long time, but it looks like recent updates broke something.

My config is the simple one from the man page, with the max passive temperature of 74 degrees celsius. I see the following issue: under load computer heats up and:
```
# cpupower frequency-info
analyzing CPU 0:
  driver: intel_pstate
  CPUs which run at the same hardware frequency: 0
  CPUs which need to have their frequency coordinated by software: 0
  maximum transition latency:  Cannot determine or is not supported.
  hardware limits: 1.60 GHz - 3.90 GHz
  available cpufreq governors: performance powersave
  current policy: frequency should be within 1.60 GHz and 1.60 GHz.
                  The governor "powersave" may decide which speed to use
                  within this range.
  current CPU frequency: 3.70 GHz (asserted by call to hardware)
  boost state support:
    Supported: yes
    Active: yes
    3700 MHz max turbo 4 active cores
    3800 MHz max turbo 3 active cores
    3900 MHz max turbo 2 active cores
    3900 MHz max turbo 1 active cores
```
it seems it ignores the frequency limitation.

thermald's log: https://pastebin.com/w9k86Uxw

**Comment by khumarahn** [comment]
I found something. I have a process running in the background using virtualgl, using a little bit of resources. If I stop it, then the frequency limitation works ok and the temperature does not go above my limit. This is very strange, I wonder if anybody met this.

**Comment by Esuil** [comment]
That process that uses virtualgl, does it run on intel graphics? I had similar issue and cause of ignoring was fact that it is not that CPU was bumped up, but intel GPU was working on frequency that was bumping CPU automatically.  
What solved problem to me was reading table of GPU-CPU frequency dependency with:  
`sudo cat /sys/kernel/debug/dri/0/i915_ring_freq_table`  
and changing intel GPU limits accordingly.  
This is my output of  
`sudo cat /sys/kernel/debug/dri/1/i915_ring_freq_table`  
(it can be dri/1/ if you use system with multiple GPUs):  
```
GPU freq (MHz)	Effective CPU freq (MHz)	Effective Ring freq (MHz)
650		800				0
700		800				0
750		1400				0
800		1500				0
850		1600				0
900		1600				0
950		1700				0
1000		1800				0
1050		1900				0
1100		2000				0
```  
When I want CPU not to go about 1500 MHz, I set my GPU limit to 800 using this command:  
`echo 800 | sudo tee /sys/kernel/debug/dri/1/i915_max_freq`  
Where /dri/1 will probably be /dri/0 for most people, you need to check that manually.

For some reason in my case CPU limits are ignored when GPU starts working on GL, just like in your case, and this solved it. GPU no longer bumps up to maximum and CPU stays within it's limits as well.  

You can also try running:  
`sudo service thermald stop`  
temporally and starting that application to see if this is thermald related problem, or it is similar to mine case.

**Comment by khumarahn** [comment]
Thank you for a very spot on answer!

I use virtualgl with intel graphics, yes.

How are the frequencies related? Can it be in your example that GPU freq is 650 and CPU freq is 2000?

**Comment by Esuil** [comment]
Yes it can. For example GPU can work on 650, but because it only requires CPU to work on 800, it will work with no issues on any range from 800 to the max. But if CPU frequency is **below** of what GPU requires to work on it's frequency, it will bump CPU up ignoring limits. So GPU set to 650 will work with any CPU range from 800-2000, but if GPU goes to frequency of 900 while CPU is limited to 1500 max, CPU will work on 1600, ignoring limit, because that is required minimum for GPU to work on 900. I am not really an expert in this matter, this is just my observations and result of research of solution because I had same problem as you did.
I would recommend just checking your ring_freq_table and then checking what frequency your GPU works on with `cat /sys/kernel/debug/dri/0/i915_frequency_info` when your application is running. Usually system itself works on minimum GPU freq without issues, but bumps GPU up when you use OpenGL etc.

**Comment by spandruvada** [comment]
On Thu, 2017-06-29 at 16:13 +0000, Esuil wrote:
> Yes it can. For example GPU can work on 650, but because it only
> requires CPU to work on 800, it will work with no issues on any range
> from 800 to the max. But if CPU frequency is below of what GPU
> requires to work on it's frequency, it will bump CPU up ignoring
> limits. So GPU set to 650 will work with any CPU range from 800-2000, 
> but if GPU goes to frequency of 900 while CPU is limited to 1500 max,
> CPU will work on 1600, ignoring limit, because that is required
> minimum for GPU to work on 900. I am not really an expert in this
> matter, this is just my observations and result of research of
> solution because I had same problem as you did.
> I would recommend just checking your ring_freq_table and then
> checking what frequency your GPU works on with cat
> /sys/kernel/debug/dri/0/i915_frequency_info when your application is
> running. Usually system itself works on minimum GPU freq without
> issues, but bumps GPU up when you use OpenGL etc.

Try setting a package power limit in /sys/class/powercap/intel-
rapl/intel-rapl:0/constraint_0_power_limit_uw to a lower value and make
sure "enabled" attribute is set.

Thanks,
Srinivas

**Comment by Esuil** [comment]
> Try setting a package power limit in /sys/class/powercap/intel- rapl/intel-rapl:0/constraint_0_power_limit_uw to a lower value and make sure "enabled" attribute is set.  
  
Thank you for reply! When I try to set it, this happens:
```  
echo 20000000 | sudo tee /sys/class/powercap/intel-rapl/intel-rapl:0/constraint_0_power_limit_uw
20000000
tee: '/sys/class/powercap/intel-rapl/intel-rapl:0/constraint_0_power_limit_uw': No data available
echo 1 | sudo tee /sys/class/powercap/intel-rapl/intel-rapl:0/enabled
1
tee: '/sys/class/powercap/intel-rapl/intel-rapl:0/enabled': Function not implemented


```
Values of `constraint_0_power_limit_uw` and `enabled` are as follows:  
```  
sudo cat /sys/class/powercap/intel-rapl/intel-rapl:0/constraint_0_power_limit_uw
35000000
sudo cat /sys/class/powercap/intel-rapl/intel-rapl:0/enabled
0
```  
It does look like possible better solution, so I will keep looking around. What can be the reason why I can't set it right now?

**Comment by spandruvada** [comment]
On Thu, 2017-06-29 at 12:31 -0700, Esuil wrote:
> Try setting a package power limit in /sys/class/powercap/intel-
> rapl/intel-rapl:0/constraint_0_power_limit_uw to a lower value and
> make sure "enabled" attribute is set.
> Thank you for reply! When I try to set it, this happens:
> echo 20000000 | sudo tee /sys/class/powercap/intel-rapl/intel-
> rapl:0/constraint_0_power_limit_uw
> 20000000
> tee: '/sys/class/powercap/intel-rapl/intel-
> rapl:0/constraint_0_power_limit_uw': No data available
> echo 1 | sudo tee /sys/class/powercap/intel-rapl/intel-rapl:0/enabled
> 1
> tee: '/sys/class/powercap/intel-rapl/intel-rapl:0/enabled': Function
> not implemented
> 
check dmesg
If there is a message
"locked by BIOS, monitoring only"

then you can't use this method. Then check your BIOS settings and see
if there is any option to for "Running average power limit".

Thanks,
Srinivas

**Comment by Esuil** [comment]
It is indeed locked by BIOS and there is no option to disable it in my BIOS. But hopefully it will help someone else who have same issue. Is there any viable way to lock intel GPU performance instead?

**Comment by khumarahn** [comment]
According to my dmesg, I too cannot use this method, and cannot enable it in the BIOS.

The method suggested by @Esuil worked perfectly, but I have to do it manually which is not so convenient.

**Comment by spandruvada** [comment]
On Thu, 2017-06-29 at 20:16 +0000, Alexey Korepanov wrote:
> According to my dmesg, I too cannot use this method, and cannot
> enable it in the BIOS.
> The method suggested by @Esuil worked perfectly, but I have to do it
> manually which is not so convenient.
I don't know why OEM locked this. This is very useful limit as this can
limit the whole package power.

Thanks,
Srinivas

**Comment by spandruvada** [comment]
On Thu, 2017-06-29 at 20:16 +0000, Alexey Korepanov wrote:
> According to my dmesg, I too cannot use this method, and cannot
> enable it in the BIOS.
> The method suggested by @Esuil worked perfectly, but I have to do it
> manually which is not so convenient.
Since your are running some GL workload, they will be impacted by
capping the GPU frequency. Just to be aware of it.

Thanks,
Srinivas

**Comment by khumarahn** [comment]
Yes, I am aware of the GL workload speed. But the priority is to keep the system cool and silent, performance is not important at all.

**Comment by Esuil** [comment]
Just to add to workaround that I am using right now, in Ubuntu 17.04 I have to set GPU frequency cap differently, because GPU boost ignores cap (was asking about it [here](https://askubuntu.com/questions/930372/setting-intel-gpu-limits-in-ubuntu-17-04-no-longer-works/930449), ended up finding solution myself.  
So instead of setting it by **`/sys/kernel/debug/dri/1/i915_max_freq`**, if your boost will override this setting (like it did for me after I changed to 17.04), you can set it like that instead:
```
echo 800 | sudo tee /sys/class/drm/card1/gt_max_freq_mhz
echo 800 | sudo tee /sys/class/drm/card1/gt_boost_freq_mhz
```  
This way you can set both normal and boost frequency limits. **800** and **card1** should be changed according to your system and desired limit.  
It is pretty strange that default CPU scaling totally ignores GPU bound to that CPU, rendering CPU scaling completely useless in cases like this.

**Comment by spandruvada** [comment]
I will close this. Open it again if the current solution is not enough,

**Comment by dos1** [comment]
So, does thermald actually care about GPU frequency now, or is the manual way of setting max frequency somehow considered "a solution"? My laptop, which has only an Intel's integrated GPU, is overheating to the point of turning off on long-lasting high GPU load, which doesn't happen on long-lasting high CPU load. It seems like thermald doesn't do it's job very well (at all?) regarding GPU thermal throttling.

**Comment by spandruvada** [comment]
On Wed, 2018-04-18 at 08:42 -0700, Sebastian Krzyszkowiak wrote:
> So, does thermald actually care about GPU frequency now, or is the
> manual way of setting max frequency somehow considered "a solution"?
> My laptop, which has only an Intel's integrated GPU, is overheating
> to the point of turning off on long-lasting high GPU load, which
> doesn't happen on long-lasting high CPU load. It seems like thermald
> doesn't do it's job very well (at all?) regarding GPU thermal
> throttling.
thermald first try to limit power, which includes GPU power also.
It is possible that your OEM disabled the power control (you can check
via "dmesg | grep -i rapl" and see if you see any locked or error
message).

Also you can configure via thermal-conf.xml or manually by writing to
/sys/class/drm/card0/gt_max_freq_mhz

Thanks,
Srinivas

**Comment by dos1** [comment]
@spandruvada: Okay, I looked around a bit, but I can't find proper resources that would explain it to me.

So I have a question: if RAPL control of the powercap is disabled by BIOS, is there a sensible way to scale GPU frequency down when the temperature gets critically high using thermald? If so, could it be made default?

Right now the default thermald config makes my laptop abruptly shut down when exposed to prolonged GPU load. It doesn't seem right that there's no fallback, especially with RAPL package locking being so common.

**Comment by spandruvada** [comment]
On Mon, 2018-06-04 at 15:19 -0700, Sebastian Krzyszkowiak wrote:
> @spandruvada: Okay, I looked around a bit, but I can't find proper
> resources that would explain it to me.
> So I have a question: if RAPL control of the powercap is disabled by
> BIOS, is there a sensible way to scale GPU frequency down when the
> temperature gets critically high using thermald? If so, could it be
> made default?
Good question. If it is i915 GPU, we can. But for other it will be
difficult as we may not have any user space control.


> Right now the default thermald config makes my laptop abruptly shut
> down when exposed to prolonged GPU load. It doesn't seem right that
> there's no fallback, especially with RAPL package locking being so
> common.
Let me check on this. Do you have i915 or something else?

Thanks,
Srinivas

**Comment by dos1** [comment]
Yes, it's i915.

**Comment by spandruvada** [comment]
On Mon, 2018-06-04 at 15:26 -0700, Sebastian Krzyszkowiak wrote:
> Yes, it's i915.
I will inform you once I push a change.

Thanks,
Srinivas

**Comment by diaevd** [comment]
Are there any changes on this issue? For me it is just as important

**Comment by dos1** [comment]
Yeah, I'm using an additional script that's throttling the GPU based on temperature right now, as otherwise the laptop is pretty much unusable and turns off from overheating when doing something GPU-heavy for a long time (which happens a lot as I make games). Would like to finally have this nicely integrated into thermald.

**Comment by adrelanos** [comment]
Could you re-open please? @spandruvada
