### ISSUE TITLE
thermald-monitor crash on launch

### ISSUE THREAD

**Issue by cmurf** [intel/thermal_daemon#132]
Discovered and filed downstream Fedora 26 with abrt capturing a bunch of state information on the crash.
https://bugzilla.redhat.com/show_bug.cgi?id=1464548

Jun 23 20:52:10 f26h.localdomain gnome-shell[1819]: gsignal.c:2641: instance '0x558f7e7c1360' has no handler with id '44282'
Jun 23 20:52:10 f26h.localdomain gnome-shell[1819]: gsignal.c:2641: instance '0x558f7e7c1360' has no handler with id '44283'
Jun 23 20:52:10 f26h.localdomain thermald-monitor.desktop[2717]: error: ThermaldInterface::initialize()  could not find valid trip for zone 2
Jun 23 20:52:11 f26h.localdomain audit[2717]: ANOM_ABEND auid=1000 uid=1000 gid=1000 ses=2 subj=unconfined_u:unconfined_r:unconfined_t:s0-s0:c0.c1023 pid=2717 comm="ThermalMonitor" exe="/usr/bin/ThermalMonitor" sig=11 res=1
Jun 23 20:52:11 f26h.localdomain kernel: show_signal_msg: 73 callbacks suppressed
Jun 23 20:52:11 f26h.localdomain kernel: ThermalMonitor[2717]: segfault at 5632b79b4548 ip 00005630aef45e36 sp 00007ffd10387690 error 4 in ThermalMonitor[5630aeea0000+ee000]

Attaching the coredumpctl stack trace.

[thermaldmonitor-crash-coredumpctl-stacktrace.txt](https://github.com/01org/thermal_daemon/files/1099390/thermaldmonitor-crash-coredumpctl-stacktrace.txt)

This happens with kernel kernel-4.10.17-200.fc25.x86_64, kernel-4.11.6-301.fc26.x86_64, and kernel-4.12.0-0.rc6.git3.1.fc27.x86_64.

**Comment by spandruvada** [comment]
Can you build and try, with this one line change?

diff --git a/tools/thermal_monitor/thermaldinterface.cpp b/tools/thermal_monitor/thermaldinterface.cpp
index eca8d74..e73b7a5 100644
--- a/tools/thermal_monitor/thermaldinterface.cpp
+++ b/tools/thermal_monitor/thermaldinterface.cpp
@@ -453,6 +453,7 @@ int ThermaldInterface::getZoneInformation(uint index, zoneInformationType &info)
         info.name = result.arguments().at(0).toString();
         info.sensor_count = result.arguments().at(1).toInt();
         info.trip_count = result.arguments().at(2).toInt();
+        info.lowest_valid_index = 0;
         return 0;
     } else {
         qCritical() << "error from" << iface->interface() <<  result.errorMessage();

**Comment by besser82** [comment]
[Scratch build](https://koji.fedoraproject.org/koji/taskinfo?taskID=20259759) with patch applied.

**Comment by cmurf** [comment]
Scratch build works for me.

**Comment by besser82** [comment]
@cmurf Allrighty, then please downgrade thermald in Fedora again…  There will be a new build in updates-testing having some more fixes from upstream commits tomorrow / this evening.

**Comment by spandruvada** [comment]
Pushed this change.
