### ISSUE TITLE
thermald and Haswell CPU's

### ISSUE THREAD

**Issue by Utini2000** [intel/thermal_daemon#135]
According to the following "Github Issue" and my own experience, thermald still doesn't work with Haswell CPU's as there is no kernel driver to handle PCH Sensors?

See: https://github.com/intel/thermal_daemon/issues/82

@spandruvada was working on a kernel patch to fix this and needed someone to try it out. Unfortunately I failed at testing it because I couldn't compile it (Linux newbie).

Is anyone around who can either develop this, try this or run me through the process of compiling & testing this (e.g. via IRC or Teamviewer/Remote Desktop) ?

Thanks in advance !

**Comment by devang** [comment]
I have an Asus with a i7-4710HQ, and thermald doesn't seem to increase fan speed at all (it constantly reads 2700 even under load). I see MCE in dmesg: CPU5: Package temperature above threshold, cpu clock throttled

**Comment by spandruvada** [comment]
We have two Haswell PCI ids in the kernel code. I see the driver is enumerating on two Haswells using kernel 4.13.
What is the output of
#lspci -vvv

**Comment by Utini2000** [comment]
@spandruvada I uploaded the output to two different paste providers:

https://dpaste.de/gpKp
https://pastebin.com/4eB40N5t

**Comment by Utini2000** [comment]
@spandruvada 

Any update/news?

**Comment by spandruvada** [comment]
Those pastes are expired. As far as I remember you have a PCH sensor.
It is possible that this is a high end desktop or server part, which thermald is not including support for.

**Comment by Utini2000** [comment]
@spandruvada 
I re-uploaded the output to my own file server:
http://files.bestmail.ws/thermald.txt

I run a laptop (Dell XPS15 9530) which is quite common but I believe it was a general Haswell problem? 
Anyway, hopefully the output helps solving the issue. If not, please let me know how to help.

**Comment by spandruvada** [comment]
On Sat, 2017-12-09 at 09:46 +0000, Utini2000 wrote:
> @spandruvada
> I re-uploaded the output to my own file server:
> http://files.bestmail.ws/thermald.txt
> I run a laptop (Dell XPS15 9530) which is quite common but I believe
> it was a general Haswell problem?
> Anyway, hopefully the output helps solving the issue. If not, please
> let me know how to help.
I see that driver is correctly loaded.
00:1f.6 Signal processing controller: Intel Corporation 8 Series
Chipset Family Thermal Management Controller (rev 05)
	Subsystem: Dell 8 Series Chipset Family Thermal Management
Controller
	Control: I/O- Mem+ BusMaster- SpecCycle- MemWINV- VGASnoop-
ParErr- Stepping- SERR- FastB2B- DisINTx-
	Status: Cap+ 66MHz- UDF- FastB2B- ParErr- DEVSEL=fast >TAbort-
<TAbort- <MAbort- >SERR- <PERR- INTx-
	Interrupt: pin C routed to IRQ 18
	Region 0: Memory at f7a20000 (64-bit, non-prefetchable)
[size=4K]
	Capabilities: [50] Power Management version 3
		Flags: PMEClk- DSI+ D1- D2- AuxCurrent=0mA PME(D0-,D1-
,D2-,D3hot-,D3cold-)
		Status: D0 NoSoftRst+ PME-Enable- DSel=0 DScale=0 PME-
	Capabilities: [80] MSI: Enable- Count=1/1 Maskable- 64bit-
		Address: 00000000  Data: 0000
	Kernel modules: intel_pch_thermal


What error you are getting in the thermald log?

Thanks,
Srinivas

**Comment by Utini2000** [comment]
@spandruvada 
Thank you for your quick response.

Attached is "systemctl status thermald.service".
Afterwards I stopped thermald and ran it manually with "thermald --no-daemon --loglevel=debug".
The output of this is attached aswell.
Link: http://files.bestmail.ws/thermald2.txt

I couldn't find a logfile (I believe thermald just logs into the system logfiles?) so I thought manually running it in "loglevel=debug" for a few seconds was the best solution?

**Comment by spandruvada** [comment]
On Sun, 2017-12-10 at 08:54 +0000, Utini2000 wrote:
> @spandruvada
> Thank you for your quick response.
> Attached is "systemctl status thermald.service".
> Afterwards I stopped thermald and ran it manually with "thermald --
> no-daemon --loglevel=debug".
> The output of this is attached aswell.
> Link: http://files.bestmail.ws/thermald2.txt
> I couldn't find a logfile (I believe thermald just logs into the
> system logfiles?) so I thought manually running it in
> "loglevel=debug" for a few seconds was the best solution?
> —
I don't see any issue in the log. You have a platform with defined
thermal relationship via ACPI. There are some errors printed because of
loglevel=debug, these are not errors but the way we are searching for
hierarchy of powercap devices.

So your thermald is functional.

Thanks,
Srinivas

**Comment by Utini2000** [comment]
Oh nice! I always thought that it wasn't working because of:

`Dec 10 09:42:44 _____ thermald[484]: sysfs write failed /sys/devices/virtual/powercap/intel-rapl/intel-rapl:0/enabled
Dec 10 09:42:44 _____ thermald[484]: sysfs read failed constraint_0_max_power_uw
Dec 10 09:42:44 _____ thermald[484]: XML zone: invalid sensor type B0D4
Dec 10 09:42:44 _____ thermald[484]: Zone update failed: unable to bind`
