### ISSUE TITLE
Side effects before/after

### ISSUE THREAD

**Issue by kayb94** [intel/thermal_daemon#137]
I am currently trying to get a working config on my laptop which is pretty though because thermald seems to have side effects.

E.g. I just started thermald as --no-daemon, realized the config wasen't quite right and stopped it. Anyway, I'm still having lots of idle-injects (with almost 0% CPU load right now). To be honest, I still really haven't figured out how to treat thermald right, else I probably had a working config that immediately was able to get rid off those previously set idle-injects. Anyway, it would be easier without side effects.

Kind regards
Kay

**Comment by spandruvada** [comment]
I suggest,
Stop the daemon. remove your config file. 
# thermald --no-daemon --loglevel=info
Run your work load and see what is thermald doing
Then we can adjust your config file.

**Comment by kayb94** [comment]
Hi

thank you for your very quick reply. When I do so and apply
a) 4x 100% CPU load or -- 90°C after roughly 2 seconds, stopped it there
b) 1x 100% CPU load, -- constantly 65°C
thermald basically does nothing. Which is of course not surprising with the default config (shall I post it?).

It's thermald 1.6.1 (Arch Linux).

```
RAPL domain count 0
RAPL domain count 1
13 CPUID levels; family:model:stepping 0x6:3a:9 (6:58:9)
Running on a vanilla kernel
Polling mode is enabled: 4
sensor_update: type x86_pkg_temp
sensor_update: type acpitz
thd_read_default_thermal_sensors loaded 2 sensors 
dts /sys/devices/platform/coretemp.0/name doesn't exist
dts /sys/class/hwmon/hwmon1/name doesn't exist
failed to open /dev/acpi_thermal_rel 
failed to open /dev/acpi_thermal_rel 
TRT/ART read failed
 Dumping parsed XML Data
 *** Index 0 ***
Name: GenericX86LaptopDevice
UUID: 
type: 0
	Sensor 0 
	 Name: TSKN
	 Path: 
	 Async Capable: 1
	 Virtual: 0
	Zone 0 
	 Name: SKIN
		 Trip Point 0 
		  temp 55000 
		  trip type 2 
		  hyst id 0 
		  sensor type TSKN 
		  cdev index 0 
			  type rapl_controller 
			  influence 100 
			  SamplingPeriod 16 
		  cdev index 1 
			  type intel_powerclamp 
			  influence 100 
			  SamplingPeriod 12 
 *** Index 1 ***
Name: ExamplePlatformName
UUID: ExampleUUID
type: 0
	Sensor 0 
	 Name: TSKN
	 Path: 
	 Async Capable: 1
	 Virtual: 0
	Sensor 1 
	 Name: example_sensor_1
	 Path: /some_path
	 Async Capable: 0
	 Virtual: 0
	Sensor 2 
	 Name: example_thermal_sysfs_sensor
	 Path: 
	 Async Capable: 1
	 Virtual: 0
	Sensor 3 
	 Name: example_virtual_sensor
	 Path: 
	 Async Capable: 0
	 Virtual: 1
		 Link type: example_sensor_1
		 Link mult: 0.500000
		 Link offset: 10.000000
	Zone 0 
	 Name: ExampleZonetype
		 Trip Point 0 
		  temp 75000 
		  trip type 1 
		  hyst id 0 
		  sensor type example_sensor_1 
		  cdev index 0 
			  type example_cooling_device 
			  influence 100 
			  SamplingPeriod 12 
	Cooling Dev 0 
		Type: example_cooling_device
		Path: 
		Min: 0
		Max: 50
		Step: 10
		AutoDownControl: 0
	 PID: Kp 0.001000
	 PID: Ki 0.000100
	 PID: Kd 0.000100
sensor index:1 x86_pkg_temp /sys/class/thermal/thermal_zone1/ Async:1 
sensor index:0 acpitz /sys/class/thermal/thermal_zone0/ Async:0 
sensor index:2 hwmon /sys/class/hwmon/hwmon0/temp1_input Async:0 
sensor index:3 hwmon /sys/class/hwmon/hwmon0/temp2_input Async:0 
sensor index:4 hwmon /sys/class/hwmon/hwmon0/temp3_input Async:0 
thd_read_default_cooling devices loaded 5 cdevs 
powercap RAPL max power limit range 35000000 
sysfs write failed /sys/devices/virtual/powercap/intel-rapl/intel-rapl:0/enabled
set_pid_param 5 [1000.100,10]
Use Default pstate drv settings
name = package-0
name = uncore
name = core
3: Processor, C:0 MN: 0 MX:10 ST:1 pt:/sys/class/thermal/ rd_bk 0 
1: Processor, C:0 MN: 0 MX:10 ST:1 pt:/sys/class/thermal/ rd_bk 0 
4: intel_powerclamp, C:-1 MN: 0 MX:50 ST:5 pt:/sys/class/thermal/ rd_bk 0 
2: Processor, C:0 MN: 0 MX:10 ST:1 pt:/sys/class/thermal/ rd_bk 0 
0: Processor, C:0 MN: 0 MX:10 ST:1 pt:/sys/class/thermal/ rd_bk 0 
5: rapl_controller, C:0 MN: 0 MX:26250000 ST:1750000 pt:/sys/devices/virtual/powercap/intel-rapl/intel-rapl:0/ rd_bk 1 
6: intel_pstate, C:0 MN: 0 MX:10 ST:1 pt:/sys/devices/system/cpu/intel_pstate/ rd_bk 1 
7: LCD, C:0 MN: 0 MX:4437 ST:443 pt:/sys/class/backlight/intel_backlight/ rd_bk 1 
Sorted trip dump zone index:0 type:acpitz:
index 0: type:critical temp:200000 hyst:1 zone id:0 sensor id:0 cdev size:0
trip type: 0 temp: 200000 
thd_read_default_thermal_zones loaded 1 zones 
zone cpu will be created 
dts zone /sys/devices/platform/coretemp.0/name doesn't exist
/sys/class/hwmon/hwmon2/name->acpitz
/sys/class/hwmon/hwmon0/name->coretemp
Core temp DTS :critical 105000, max 87000, psv 96000
node type: Element, name: CoolingDevice value: rapl_controller
node type: Element, name: CoolingDevice value: intel_pstate
node type: Element, name: CoolingDevice value: intel_powerclamp
node type: Element, name: CoolingDevice value: cpufreq
node type: Element, name: CoolingDevice value: Processor
CDEVS order specified in thermal-cpu-cdev-order.xml
Sorted trip dump zone index:2 type:cpu:
index 0: type:passive temp:96000 hyst:0 zone id:2 sensor id:65535 cdev size:4
cdev[0] rapl_controller
cdev[1] intel_pstate
cdev[2] intel_powerclamp
cdev[3] Processor
trip type: 2 temp: 96000 
dts zone /sys/class/hwmon/hwmon1/name doesn't exist
Zone 0: acpitz, Active:0 Bind:0 Sensor_cnt:1
..sensors.. 
sensor index:0 acpitz /sys/class/thermal/thermal_zone0/ Async:0 
..trips.. 
index 0: type:critical temp:200000 hyst:1 zone id:0 sensor id:0 cdev size:0
Zone 2: cpu, Active:1 Bind:0 Sensor_cnt:1
..sensors.. 
sensor index:1 x86_pkg_temp /sys/class/thermal/thermal_zone1/ Async:1 
..trips.. 
index 0: type:passive temp:96000 hyst:0 zone id:2 sensor id:65535 cdev size:4
cdev[0] rapl_controller
cdev[1] intel_pstate
cdev[2] intel_powerclamp
cdev[3] Processor
index 1: type:polling temp:91000 hyst:0 zone id:2 sensor id:1 cdev size:0
FD = 7
Current user preference is 0
thd_engine_thread begin
^CTerminating ...
terminating on user request ..

```

**Comment by spandruvada** [comment]
On Wed, 2017-08-23 at 21:21 +0000, kayb94 wrote:
> Hi
> thank you for your very quick reply. When I do so and apply
> a) 4x 100% CPU load or -- 90°C after roughly 2 seconds, stopped it
> there
> b) 1x 100% CPU load, -- constantly 65°C
> thermald basically does nothing. Which is of course not surprising
> with the default config (shall I post it?).

I think you don't need any config changes. You have pretty high TDP
system.
If you want to control temperature at 90C, just execute this command
one time.

# dbus-send  --system  --dest=org.freedesktop.thermald  /org/freedesk‐
       top/thermald         org.freedesktop.thermald.SetUserPassiveTemp
erature
       string:cpu uint32:90000

Thanks,
Srinivas

**Comment by kayb94** [comment]
I tried this with 65000, as I still like my Intel CPU and don't want to fry it, neither have the money to buy a new one. ;)
Anyway, it didn't work (90C again). Is there supposed to be a reaction in thermald's output uppon the dbus message? Because I didn't see anything there neither.

Regards,
Kay

**Comment by spandruvada** [comment]
On Wed, 2017-08-23 at 14:35 -0700, kayb94 wrote:
> I tried this with 65000, as I still like my Intel CPU and don't want
> to fry it, neither have the money to buy a new one. ;)
> Anyway, it didn't work (90C again). Is there supposed to be a
> reaction in thermald's output uppon the dbus message? Because I
> didn't see anything there neither.

In the logs you sent me before the line
index 0: type:passive temp:96000 hyst:0 zone id:2 sensor id:65535 cdev
size:4

would have change to when you restart ()
index 0: type:passive temp:90000 hyst:0 zone id:2 sensor id:65535 cdev
size:4

If you are still running via command line you need to add option 
--dbus-enable
(With service it would have already added this)

You can change to lower but it will hurt performance. You can change it 87C, where fans should be running at full speed on your system.

**Comment by kayb94** [comment]
The fan on my Lenovo T430 never runs full speed since a BIOS update; people were complaining about the (indeed) noisy fans in half of the laptops (sold with differnt fans), so they just globally limited the fan speed from 5000 to now 4000 rpm (at least that's my interpretation of the reason).

Anyway, I got some better results now! But it's still not what I expected, to be honest. I mean, the temperature stays below 75°C (I changed that) but is actually often too low, resulting in rough performance hits. I tried playing SuperTux Kart. First it was okay, but then it started lagging a lot, with the following output of thermald:

```
cdev index:3 consecutive call, increment exponentially state 9
Set : threshold:65000, temperature:73000, cdev:3(Processor), curr_state:9, max_state:10
cdev index:3 consecutive call, increment exponentially state 17
Set : threshold:65000, temperature:67000, cdev:3(Processor), curr_state:10, max_state:10
match zone 2 trip 0 clamp 16777215
Erased  [2: 0 16777215
Set : threshold:65000, temperature:62000, cdev:3(Processor), curr_state:9, max_state:10
Added zone 2 trip 0 clamp 16777215
Set : threshold:65000, temperature:67000, cdev:3(Processor), curr_state:10, max_state:10
match zone 2 trip 0 clamp 16777215
Erased  [2: 0 16777215
Set : threshold:65000, temperature:64000, cdev:3(Processor), curr_state:9, max_state:10
Added zone 2 trip 0 clamp 16777215
Set : threshold:65000, temperature:66000, cdev:3(Processor), curr_state:10, max_state:10
match zone 2 trip 0 clamp 16777215
Erased  [2: 0 16777215
Set : threshold:65000, temperature:61000, cdev:3(Processor), curr_state:9, max_state:10
Added zone 2 trip 0 clamp 16777215
Set : threshold:65000, temperature:67000, cdev:3(Processor), curr_state:10, max_state:10
match zone 2 trip 0 clamp 16777215
Erased  [2: 0 16777215
Set : threshold:65000, temperature:61000, cdev:3(Processor), curr_state:9, max_state:10
Added zone 2 trip 0 clamp 16777215
Set : threshold:65000, temperature:65000, cdev:3(Processor), curr_state:10, max_state:10
match zone 2 trip 0 clamp 16777215
Erased  [2: 0 16777215
Set : threshold:65000, temperature:61000, cdev:3(Processor), curr_state:9, max_state:10
Set : threshold:65000, temperature:59000, cdev:3(Processor), curr_state:8, max_state:10
Set : threshold:65000, temperature:59000, cdev:3(Processor), curr_state:7, max_state:10
Set : threshold:65000, temperature:58000, cdev:3(Processor), curr_state:6, max_state:10
Set : threshold:65000, temperature:56000, cdev:3(Processor), curr_state:5, max_state:10

```

It's staying at curr-state 9 and 10 pretty long, compared to the actual temperature.

Btw:
I figured out now, how come I had those "side effects":
1. start thermald
2. start 4x100% CPU load (busy-loops)
3. stop thermald
4. stop 4x100% CPU load
```
cat /sys/devices/system/cpu/intel_pstate/max_perf/pct
60
```
That seems to be the side effect I was talking about. In my opinion that is unexpected, but maybe its wanted. Just to let you know.

Regards
Kay

**Comment by kayb94** [comment]
One thing btw: Could you tell me how thermald stops TurboBoost? I noticed, that it definitely does so, but I was never able to accomplish this myself (with all different kinds of methods I found on the web). I would enjoy doing some experiments with that.

Regards
Kay

**Comment by spandruvada** [comment]
I don't think this is a full log. I was expecting rapl to be first
control.
65C is too low as a threshold, it will hurt performance. I think 85C is
better on your system.

Thanks,
Srinivas

**Comment by kayb94** [comment]
Yes, it isn't a full log, that's right. As mentioned, the threshold I had entered that time was 75°C. So I tested with SuperTux Kart and first it went pretty good and actually staying close by 75°C, but then it was way too long at around 60°C, thats the part of the log I sent (full log would haven been too long I think, please pardon if actually shortened it too much). Together with a huge performance hit. My point just is, that it seemed to me like the throttling was too strong. If this is unexpected, but the logdata isn't enough, I'm willing to try to reproduce that, never mind.

Thinking of the 88°C being considered "HIGH" in the lm-sensors output (don't know if this number originates to lenovo or intel), I prefer staying at least 10°C below that. Especially, when taking into account, that roughly speaking +10°C temperature half the lifetime of a silicon chip (at least that's what I learned at university).

> echo 1 > /sys/devices/system/cpu/intel_pstate/no_turbo

Sadly, this does not work for me. I think I had one time read somewhere, this was just a "hint" for intel_pstate, but no requirement.

Regards
Kay

**Comment by spandruvada** [comment]
On Wed, 2017-08-23 at 18:17 -0700, kayb94 wrote:
> Yes, it isn't a full log, that's right. As mentioned, the threshold I
> had entered that time was 75°C. So I tested with SuperTux Kart and
> first it went pretty good and actually staying close by 75°C, but
> then it was way too long at around 60°C, thats the part of the log I
> sent (full log would haven been too long I think, please pardon if
> actually shortened it too much). Together with a huge performance
> hit. My point just is, that it seemed to me like the throttling was
> too strong. If this is unexpected, but the logdata isn't enough, I'm
> willing to try to reproduce that, never mind.
> Thinking of the 88°C being considered "HIGH" in the lm-sensors output
> (don't know if this number originates to lenovo or intel), I prefer
> staying at least 10°C below that. Especially, when taking into
> account, that roughly speaking +10°C temperature half the lifetime of
> a silicon chip (at least that's what I learned at university).
> echo 1 > /sys/devices/system/cpu/intel_pstate/no_turbo
> Sadly, this does not work for me. I think I had one time read
> somewhere, this was just a "hint" for intel_pstate, but no
> requirement.
This is not a hint. Enter an issue in kernel bugzilla, I will take a
look.

Thanks,
Srinivas

**Comment by kayb94** [comment]
Okay, I just submitted the bug:
https://bugzilla.kernel.org/show_bug.cgi?id=196757

Regards
Kay

**Comment by spandruvada** [comment]
I took care on the kernel side entered via bugzilla. I don't think anything  to be done here,
