### ISSUE TITLE
Haswell Xeon CPUID missed

### ISSUE THREAD

**Issue by tycho** [intel/thermal_daemon#139]
My Intel Xeon E5-2630 v3 CPUs aren't recognized by thermald. This patch solves it:

```diff
diff --git a/src/thd_engine.cpp b/src/thd_engine.cpp
index 2bb919c..20645a0 100644
--- a/src/thd_engine.cpp
+++ b/src/thd_engine.cpp
@@ -595,6 +595,7 @@ static supported_ids_t id_table[] = {
 		{ 6, 0x2a }, // Sandybridge
 		{ 6, 0x3a }, // IvyBridge
 		{ 6, 0x3c }, // Haswell
+		{ 6, 0x3f }, // Haswell Xeon
 		{ 6, 0x45 }, // Haswell ULT
 		{ 6, 0x46 }, // Haswell ULT
 		{ 6, 0x3d }, // Broadwell
```

**Comment by spandruvada** [comment]
On Sat, 2017-09-16 at 16:23 -0700, Steven Noonan wrote:
> My Intel Xeon E5-2630 v3 CPUs aren't recognized by thermald. This
> patch solves it:
> diff --git a/src/thd_engine.cpp b/src/thd_engine.cpp
> index 2bb919c..20645a0 100644
> --- a/src/thd_engine.cpp
> +++ b/src/thd_engine.cpp
> @@ -595,6 +595,7 @@ static supported_ids_t id_table[] = {
>  		{ 6, 0x2a }, // Sandybridge
>  		{ 6, 0x3a }, // IvyBridge
>  		{ 6, 0x3c }, // Haswell
> +		{ 6, 0x3f }, // Haswell Xeon
Thanks for submitting this change.

We purposely not added Xeon as those platform users don't want any
passive thermal controls. There was an issue in the past when Ubuntu
enabled for all platforms and some users had issue with this, so added
white list.

If someone wants to run on Xeons they can always use command line
parameter to ignore this check.

Thanks,
Srinivas

**Comment by tycho** [comment]
Ah, I see. Thanks @spandruvada!

**Comment by tycho** [comment]
@spandruvada Is it intentional that Xeon E3 Skylake chips still get handled by thermald? I don't have a complaint about it either way, but I notice it happily runs on this one without modification:

```
processor       : 0
vendor_id       : GenuineIntel
cpu family      : 6
model           : 94
model name      : Intel(R) Xeon(R) CPU E3-1275 v5 @ 3.60GHz
stepping        : 3
```
