### ISSUE TITLE
CPU being throttled and fan still doesn't go into highest RPM

### ISSUE THREAD

**Issue by tjackson** [intel/thermal_daemon#140]
Hi there. I have an Asus S500CA laptop that seems unwilling to use its highest fan speed, which I believe is 5300 RPM. I'm unable to confirm that since manually setting the fan speed to highest results in sensors showing -1 for fan speed. Currently I'm at 92C rebuilding some package and fan is only at 4200 RPM. So, in some cases I'll get messages like these:
[118230.637713] CPU2: Package temperature above threshold, cpu clock throttled (total events = 1)
[118230.637714] CPU0: Package temperature above threshold, cpu clock throttled (total events = 1)
[118230.637731] CPU1: Package temperature above threshold, cpu clock throttled (total events = 1)
[118230.637732] CPU3: Package temperature above threshold, cpu clock throttled (total events = 1)
[118230.638737] CPU0: Package temperature/speed normal
[118230.638738] CPU2: Package temperature/speed normal
[118230.638743] CPU1: Package temperature/speed normal
[118230.638744] CPU3: Package temperature/speed normal

I had hoped thermald would help me with this, but it doesn't.

systemctl status thermald
Sep 29 21:40:08 archlinux systemd[1]: Starting Thermal Daemon Service...
Sep 29 21:40:08 archlinux systemd[1]: Started Thermal Daemon Service.
Sep 29 21:40:08 archlinux thermald[3846]: 13 CPUID levels; family:model:stepping 0x6:3a:9 (6:58:9)
Sep 29 21:40:08 archlinux thermald[3846]: Polling mode is enabled: 4

I'm using the default thermal-conf.xml as I'm not really sure what to set.

Currently on a drm-intel kernel, 4.13.0-rc5-g87dc03ad.

This may be more of a question/assistance request than an issue.

This laptop is old so I guess it's reasonable to have thermal issues, but it has idled at 70C for years.

msr is builtin, I also have intel_pstate, intel_rapl, intel_idle available...

**Comment by tjackson** [comment]
Sorry for the noise. I updated thermald to git version and now it seems to be working.

Adapter: ISA adapter
Package id 0:  +90.0°C  (high = +87.0°C, crit = +105.0°C)
Core 0:        +86.0°C  (high = +87.0°C, crit = +105.0°C)
Core 1:        +88.0°C  (high = +87.0°C, crit = +105.0°C)

acpitz-virtual-0
Adapter: Virtual device
temp1:        +89.0°C  (crit = +108.0°C)

asus-isa-0000
Adapter: ISA adapter
cpu_fan:     5700 RPM
temp1:        +89.0°C

**Comment by tjackson** [comment]
Looking at the commits between 0.6 and now I'm still a little confused why it's suddenly working. I'll reopen if I encounter the issue again...

**Comment by tjackson** [comment]
Okay, I'm confused. It seems like the issue reappears after some time. Like thermald stops working, though it's still running?

coretemp-isa-0000
Adapter: ISA adapter
Package id 0:  +94.0°C  (high = +87.0°C, crit = +105.0°C)
Core 0:        +91.0°C  (high = +87.0°C, crit = +105.0°C)
Core 1:        +94.0°C  (high = +87.0°C, crit = +105.0°C)

acpitz-virtual-0
Adapter: Virtual device
temp1:        +92.0°C  (crit = +108.0°C)

asus-isa-0000
Adapter: ISA adapter
cpu_fan:     4100 RPM
temp1:        +92.0°C

**Comment by spandruvada** [comment]
Do you know how to control fan speed from command line on this platform?

**Comment by tjackson** [comment]
echo 255 > /sys/devices/platform/asus-nb-wmi/hwmon/hwmon1/pwm1 will raise fan speed it to max. After that, sensors command shows cpu_fan: -1 RPM. (Is there a /sys entry for fan speed?) Thanks for your help. :)

**Comment by tjackson** [comment]
I found the answer to one question. I don't know why sensors reports bogus value, but after maxing fan speed cat /sys/class/thermal/thermal_zone0/temp shows correct value.

**Comment by spandruvada** [comment]
thermald doesn't control as most of the platform the embedded controller in your platform controls it.
But since you have someway to control, you can try the paste the data to thermal-conf.xm (attached in the next comment).
Your thermal-conf.xml may be at  etc/thermald/thermal-conf.xml or based on your build.
For test to check if this getting used and behavior:
# systemctl stop thermald
# thermald --no-daemon --loglevel=info

then run your load and attach logs,

**Comment by spandruvada** [comment]
<?xml version="1.0"?>
<ThermalConfiguration>
	<Platform>
		<Name>Use Fan control first then CPU throttle </Name>
		<ProductName>*</ProductName>
		<Preference>QUIET</Preference>
		<ThermalZones>
                       <ThermalZone>
                                       <Type>x86_pkg_temp</Type>
                                       <TripPoints>
                                                       <TripPoint>
                                                                       <SensorType>x86_pkg_temp</SensorType>
                                                                       <Temperature>70000</Temperature>
									<type>passive</type>
                                                                       <ControlType>SEQUENTIAL</ControlType>
                                                                       <CoolingDevice>
                                                    <type>_fan_</type>
                                                                       </CoolingDevice>
                                                       </TripPoint>
                                       </TripPoints>
                       </ThermalZone>
                </ThermalZones>
                <CoolingDevices>
                      <CoolingDevice>
                                       <Type>_fan_</Type>
					<Path> /sys/devices/platform/asus-nb-wmi/hwmon/hwmon1/pwm1</Path>
					<MinState>100</MinState>
					<MaxState>255</MaxState>
					<IncDecStep>50</IncDecStep>
					<DebouncePeriod>10</DebouncePeriod>
                     </CoolingDevice>
                </CoolingDevices>
       </Platform>
</ThermalConfiguration>

**Comment by spandruvada** [comment]
If the copy paste messed up the file, attaching as a file to your email.

**Comment by spandruvada** [comment]
Also pasted here

https://pastebin.com/D4aFzsMR

**Comment by tjackson** [comment]
Thanks very much, testing this out. hwmon1 sometimes is hwmon2 (maybe hwmon0 too? not sure) on a reboot. Can thermald's conf do wildcards or multiple values for hwmon*?
For testing at the moment I updated the path on your paste to 
/sys/devices/platform/asus-nb-wmi/hwmon/hwmon2/pwm1 - which is its current value.

After many energy drinks and messing with this, I found another possibly workable solution, but I didn't test it much: echo 80 > /sys/devices/system/cpu/intel_pstate/max_perf_pct

**Comment by spandruvada** [comment]
There is no wildcard support. First try changing to matching hwmon*. We can have a workaround.

**Comment by tjackson** [comment]
Oh yeah, I remembered to set back max_perf_pct to 100 for thermald test.

Perfect, I already notice a huge difference. I fired up a Wine game and after about a minute fans go to max speed, which is what it should have been doing all along IMHO. Temperature is holding at 73C. Of course I will test further.

**Comment by tjackson** [comment]
Performance is not good though. Maybe we can permit higher temperature?


trip type: 2 temp: 70000
Zone 0: acpitz, Active:0 Bind:1 Sensor_cnt:1
..sensors..
sensor index:0 acpitz /sys/class/thermal/thermal_zone0/ Async:0
..trips..
index 0: type:critical temp:108000 hyst:1 zone id:0 sensor id:0 cdev size:0
index 1: type:passive temp:110000 hyst:1 zone id:0 sensor id:0 cdev size:1
cdev[0] Processor
Zone 2: cpu, Active:1 Bind:0 Sensor_cnt:1
..sensors..
sensor index:1 x86_pkg_temp /sys/class/thermal/thermal_zone1/ Async:1
..trips..
index 0: type:passive temp:96000 hyst:0 zone id:2 sensor id:65535 cdev size:4
cdev[0] rapl_controller
cdev[1] intel_pstate
cdev[2] intel_powerclamp
cdev[3] Processor
index 1: type:polling temp:91000 hyst:0 zone id:2 sensor id:1 cdev size:0
Zone 3: x86_pkg_temp, Active:1 Bind:1 Sensor_cnt:1
..sensors..
sensor index:1 x86_pkg_temp /sys/class/thermal/thermal_zone1/ Async:1
..trips..
index 0: type:passive temp:70000 hyst:0 zone id:3 sensor id:1 cdev size:1
cdev[0] _fan_
index 1: type:polling temp:65000 hyst:0 zone id:3 sensor id:1 cdev size:0
Product Name matched [wildcard]
FD = 7
Current user preference is 0
thd_engine_thread begin
Added zone 3 trip 0 clamp 16777215
Set : threshold:70000, temperature:71000, cdev:7(_fan_), curr_state:150, max_state:255
cdev index:7 consecutive call, increment exponentially state 250
Set : threshold:70000, temperature:72000, cdev:7(_fan_), curr_state:250, max_state:255
cdev index:7 consecutive call, increment exponentially state 350
Set : threshold:70000, temperature:71000, cdev:7(_fan_), curr_state:255, max_state:255

**Comment by tjackson** [comment]
Setting Temperature to 85000 seems to get the best performance and it stays under 87C, which is okay with me. :)

**Comment by tjackson** [comment]
One workaround for hwmon renaming is to use the out of tree asus_fan module which can create /tmp entries pointing to the right hwmon. It's really hacky though so if you can think of a better solution please let me know. You've more than answered my question and after a few days of testing the provided config changed to Temperature 85000 does keep it within that range. Thanks! :)
