### ISSUE TITLE
Thermald not working on Enterprise Linux 7.4

### ISSUE THREAD

**Issue by bugreport0** [intel/thermal_daemon#145]
Hello, I tried to install install thermald 1.6 from EL7.4 EPEL repositories (this is the latest one available), but when I try to run it as a service I get these errors:

$ systemctl status thermald
● thermald.service - Thermal Daemon Service
   Loaded: loaded (/usr/lib/systemd/system/thermald.service; enabled; vendor preset: disabled)
   Active: failed (Result: timeout) since Wed 2017-12-27 20:41:11 CET; 35min ago
  Process: 899 ExecStart=/usr/sbin/thermald --no-daemon --dbus-enable (code=exited, status=0/SUCCESS)
 Main PID: 899 (code=exited, status=0/SUCCESS)

Dec 27 20:39:39 computer thermald[899]: D-Bus.RequestName RPC failed: Connection ":1.4" is not allowed to own the service "org.freedesktop.thermald" due to security policies in the configuration file
Dec 27 20:39:39 computer thermald[899]: 22 CPUID levels; family:model:stepping 0x6:5e:3 (6:94:3)
Dec 27 20:39:39 computer thermald[899]: Polling mode is enabled: 4
Dec 27 20:39:39 computer thermald[899]: sysfs read failed constraint_0_max_power_uw
Dec 27 20:41:09 computer systemd[1]: thermald.service start operation timed out. Terminating.
Dec 27 20:41:09 computer thermald[899]: Terminating ...
Dec 27 20:41:10 computer thermald[899]: terminating on user request ..
Dec 27 20:41:11 computer systemd[1]: Failed to start Thermal Daemon Service.
Dec 27 20:41:11 computer systemd[1]: Unit thermald.service entered failed state.
Dec 27 20:41:11 computer systemd[1]: thermald.service failed.

I have lm_sensors package installed and ran sensors-detect before even installing thermald.

When I try to run:

$ sudo thermald --dbus-enable --no-daemon

I get these errors:

D-Bus.RequestName RPC failed: Connection ":1.131" is not allowed to own the service "org.freedesktop.thermald" due to security policies in the configuration file
22 CPUID levels; family:model:stepping 0x6:5e:3 (6:94:3)
Polling mode is enabled: 4
sysfs read failed constraint_0_max_power_uw

Please can you help me with this issue? I cant figure out what could be the problem. If you needed any more information just let me know.

Thank you very much and have a nice day

**Comment by bugreport0** [comment]
I also wanted to try to delete "/var/run/thermald/thermal-conf.xml.auto" as mentioned in this thread:

https://github.com/intel/thermal_daemon/issues/82

But this file does not exist on my system.

**Comment by spandruvada** [comment]
This is due to your security policy on the system:

Do you have this file?
/etc/dbus-1/system.d/org.freedesktop.thermald.conf

What are the contents?

Thanks,
Srinivas

**Comment by bugreport0** [comment]
Hello @spandruvada, thank you for your reply.

No this file does not exist on my system in that location. I was already looking for it but it is not there.

when I searched this file I found one in: /usr/share/dbus-1/system.d/org.freedesktop.thermald.conf

Containing this (I did not modify it):

<?xml version="1.0"?> 
<!DOCTYPE busconfig PUBLIC "-//freedesktop//DTD D-BUS Bus Configuration 1.0//EN"
        "http://www.freedesktop.org/standards/dbus/1.0/busconfig.dtd">



<busconfig>

        <policy user="root">
                <allow own="org.freedesktop.thermald"/>
                <allow send_destination="org.freedesktop.thermald"/>
                <allow receive_sender="org.freedesktop.thermald"/>
        </policy>

        <policy context="default">
                <deny send_destination="org.freedesktop.thermald"/>
                <allow receive_sender="org.freedesktop.thermald"/>
        </policy>

        <policy group="power">
                <allow send_destination="org.freedesktop.thermald"/>
                <allow receive_sender="org.freedesktop.thermald"/>
        </policy>

</busconfig>

**Comment by spandruvada** [comment]
I don't know the configuration of RHEL. Did you build thermald yourself
or Redhat built it?

Thanks,
Srinivas

**Comment by bugreport0** [comment]
No I did not build it, I installed it from EPEL:

https://fedoraproject.org/wiki/EPEL

To this day I had not any problems with packages from this repository, all of them worked well. But I have this same problem with thermald on 2 machines. Do you think it is problem of the package? Could not some security mechanism in RHEL (such as SELinux) block it from fuctioning properly?

**Comment by spandruvada** [comment]
On Fri, 2017-12-29 at 07:37 -0800, bugreport0 wrote:
> No I did not build it, I installed it from EPEL:
> https://fedoraproject.org/wiki/EPEL
> To this day I had not any problems with packages from this
> repository, all of them worked well. But I have this same problem
> with thermald on 2 machines. Do you think it is problem of the
> package? Could not some security mechanism in RHEL (such as SELinux)
> block it from fuctioning properly?
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub, or mute the thread.

There is some security mechanism which is blocking. Since it is not
built by you so the maintainer of the package should have tested this.
Can you enter bug report for fedora EPEL?

Meanwhile you can remove dbus-enable flag from your service file.

Thanks,
Srinivas

**Comment by bugreport0** [comment]
Ok, thank you very much

// By the way what does dbus-enable flag do?
