### ISSUE TITLE
thermald[583]: sysfs read failed /sys/class/thermal/thermal_zone3/temp

### ISSUE THREAD

**Issue by francoism90** [intel/thermal_daemon#150]
It's filling up the journal, any debug info needed why this is happening? :)

System:
HP 360x
Intel i5-7200U
Arch Linux 4.15.9

Thanks!

**Comment by spandruvada** [comment]
On Sun, 2018-03-18 at 19:06 +0000, François M. wrote:
> It's filling up the journal, any debug info needed why this is
> happening? :)
> System:
> HP 360x
> Intel i5-7200U
> Arch Linux 4.15.9
We need to see why read is failing:
what is output of

#cat /sys/class/thermal/thermal_zone3/*

Thanks,
Srinivas

**Comment by francoism90** [comment]
@spandruvada 

```
# cat /sys/class/thermal/thermal_zone3/*
power_allocator user_space bang_bang fair_share step_wise
cat: /sys/class/thermal/thermal_zone3/integral_cutoff: Input/output error
cat: /sys/class/thermal/thermal_zone3/k_d: Input/output error
cat: /sys/class/thermal/thermal_zone3/k_i: Input/output error
cat: /sys/class/thermal/thermal_zone3/k_po: Input/output error
cat: /sys/class/thermal/thermal_zone3/k_pu: Input/output error
cat: /sys/class/thermal/thermal_zone3/offset: Input/output error
step_wise
cat: /sys/class/thermal/thermal_zone3/power: Is a directory
cat: /sys/class/thermal/thermal_zone3/slope: Input/output error
cat: /sys/class/thermal/thermal_zone3/subsystem: Is a directory
cat: /sys/class/thermal/thermal_zone3/sustainable_power: Input/output error
cat: /sys/class/thermal/thermal_zone3/temp: No data available
-32768000
passive
-32768000
passive
-32768000
passive
-32768000
passive
-32768000
passive
-32768000
passive
-32768000
passive
-32768000
passive
iwlwifi
```

If more info is needed, please let me know.

**Comment by spandruvada** [comment]
On Mon, 2018-03-19 at 16:07 +0000, François M. wrote:
> @spandruvada
> # cat /sys/class/thermal/thermal_zone3/*
> power_allocator user_space bang_bang fair_share step_wise
> cat: /sys/class/thermal/thermal_zone3/integral_cutoff: Input/output
> error
> cat: /sys/class/thermal/thermal_zone3/k_d: Input/output error
> cat: /sys/class/thermal/thermal_zone3/k_i: Input/output error
> cat: /sys/class/thermal/thermal_zone3/k_po: Input/output error
> cat: /sys/class/thermal/thermal_zone3/k_pu: Input/output error
> cat: /sys/class/thermal/thermal_zone3/offset: Input/output error
> step_wise
> cat: /sys/class/thermal/thermal_zone3/power: Is a directory
> cat: /sys/class/thermal/thermal_zone3/slope: Input/output error
> cat: /sys/class/thermal/thermal_zone3/subsystem: Is a directory
> cat: /sys/class/thermal/thermal_zone3/sustainable_power: Input/output
> error
> cat: /sys/class/thermal/thermal_zone3/temp: No data available
> -32768000
> passive
> -32768000
> passive
> -32768000
> passive
> -32768000
> passive
> -32768000
> passive
> -32768000
> passive
> -32768000
> passive
> -32768000
> passive
> iwlwifi
> If more info is needed, please let me know.
This is a wifi kernel driver issue, where all reads are giving invalid
data. Only thing can be really done is to remove error message.

Thanks,
Srinivas

**Comment by francoism90** [comment]
I accidentally copied information from my workstation, sorry!

This is the correct output/debug:
```
# cat /sys/class/thermal/thermal_zone3/*
power_allocator user_space bang_bang fair_share step_wise
0
0
0
0
0
0
user_space
cat: /sys/class/thermal/thermal_zone3/power: Is a directory
0
cat: /sys/class/thermal/thermal_zone3/subsystem: Is a directory
0
23000
cat: /sys/class/thermal/thermal_zone3/trip_point_0_hyst: Input/output error
97000
hot
cat: /sys/class/thermal/thermal_zone3/trip_point_1_hyst: Input/output error
92000
passive
cat: /sys/class/thermal/thermal_zone3/trip_point_2_hyst: Input/output error
86000
active
cat: /sys/class/thermal/thermal_zone3/trip_point_3_hyst: Input/output error
81000
active
B0D4
```

Thanks.

**Comment by spandruvada** [comment]
This also needs kernel driver fix. Currently there is no way to avoid
sysfs entries even if certain features are not present.

Thanks,
Srinivas

**Comment by francoism90** [comment]
@spandruvada Thanks for looking at the issue, will report this upstream and link to this issue. :)

**Comment by francoism90** [comment]
@spandruvada Can we do something about the heavy journal logging? I only see `info` and `debug` as possible logging values. The package should work fine, if I understand correctly. Even with the error shown.

Thanks.

**Comment by francoism90** [comment]
Upst
