### ISSUE TITLE
Poll interval of 4 seconds causes overcorrections and huge temperature variance

### ISSUE THREAD

**Issue by Hermanio** [intel/thermal_daemon#151]
OS: Ubuntu 18.04
CPU: Intel i7-3820QM
thermald version: commit bb9ddc7, build from source
Cooling device: intel_pstate

Issue:
Seemingly hardcoded poll interval of 4 seconds set in main.cpp line 70 seems to be way too long.
Code in question: 
```
// poll mode
int thd_poll_interval = 4; //in seconds
```
If trip point is set to 87C then the CPU package temperature will jump between 80-96C and the CPU frequency will oscillate between 1500-3400MHz, all of this while `stress -c 16` is running.

Possible solution:
Change the poll interval to 1 second or lower. Testing with poll interval as 1 second reduced the variance noticeably.
The variance could be reduced further by increasing the amount of allowed states. I noticed that `thermald` utilises corrections of 10 or 20 pct while the smallest amount of pct that has an effect is around 3pct. 

Here are some before and after graphs of thermald with 87C trip point and poll interval of 4 seconds and 1 second, respectively:
![image](https://user-images.githubusercontent.com/8943361/39961710-e411777c-5644-11e8-99ff-fb74bef8a9eb.png)

Configuration file used:
```
<?xml version="1.0"?>
<ThermalConfiguration>
   <Platform>
      <Name>T430</Name>
      <ProductName>*</ProductName>
      <Preference>QUIET</Preference>
      <ThermalSensors>
         <ThermalSensor>
            <Type>pkg-temp-0</Type>
            <Path>/sys/class/thermal/thermal_zone1/temp</Path>
            <AsyncCapable>1</AsyncCapable>
         </ThermalSensor>
      </ThermalSensors>
      <ThermalZones>
         <ThermalZone>
            <Type>cpu package</Type>
            <TripPoints>
               <TripPoint>
                  <SensorType>pkg-temp-0</SensorType>
                  <Temperature>87000</Temperature>
                  <type>passive</type>
                  <CoolingDevice>
                     <index>1</index>
                     <type>intel_pstate</type>
                  </CoolingDevice>
               </TripPoint>
            </TripPoints>
         </ThermalZone>
      </ThermalZones>
   </Platform>
</ThermalConfiguration>

```
```

<CoolingDeviceOrder>
    <CoolingDevice>intel_pstate</CoolingDevice>
</CoolingDeviceOrder>

```

**Comment by spandruvada** [comment]
On Sat, 2018-05-12 at 14:33 -0700, Herman Õunapuu wrote:
> OS: Ubuntu 18.04
> CPU: Intel i7-3820QM
> thermald version: commit bb9ddc7, build from source
> Cooling device: intel_pstate
> Issue:
> Seemingly hardcoded poll interval of 4 seconds set in main.cpp line
> 70 seems to be way too long.
> Code in question:
> // poll mode
> int thd_poll_interval = 4; //in seconds
You can change poll interval by command line option
--poll-interval



> If trip point is set to 87C then the CPU package temperature will
> jump between 80-96C and the CPU frequency will oscillate between
> 1500-3400MHz, all of this while stress -c 16 is running.
CPU temperature varies quickly. The idea is on average reduce power so
that thermal shutdown won't happen.

I don't see attached graphs. It will be interesting to see results
without any config file (You can use command line poll interval
control).

Thanks,
Srinivas

**Comment by Hermanio** [comment]
I see, I'll get around to testing the command line option some time in the future and share the results then.

**Comment by cooper151288** [comment]
Is it possible to have poll interval < 1s without a major rewrite, or even dynamically set.
Dynamically setting poll interval so it is shorter once a trip is violated would be good for some situations. It may bork the PID controller though so that would have to be considered.

**Comment by spandruvada** [comment]
If all sensor can give asynchronous inputs, we don't need polling at all,.
Doing less than 1 second will need nanosleep(), but need to make sure that thermald unnecessary not consuming cpu cycles and contributing to thermals.

**Comment by Hermanio** [comment]
Made some quick tests with `stress` for 10 minutes and thermald with stock settings and a changed poll interval. Tested on Kubuntu 18.04 LiveUSB.
4 second poll interval CPU clock speed and package temperature:
https://i.imgur.com/Te6nPvP.png
![4second-thermald](https://user-images.githubusercontent.com/8943361/42126433-709e7056-7c91-11e8-8860-fa8e2938e7a0.png)

1 second poll interval CPU clock speed and package temperature:
https://i.imgur.com/WGMiRLP.png
![1second-thermald](https://user-images.githubusercontent.com/8943361/42126435-74dfed8e-7c91-11e8-9f7f-0c37a90b7685.png)

For comparison, here is the behaviour of my own solution with a 0.25s polling period and a more precise control of the `intel_pstate` power states:
https://i.imgur.com/0BIkxUl.png
![lcm-behaviour](https://user-images.githubusercontent.com/8943361/42126437-80de8168-7c91-11e8-9489-a45606d67254.png)

It's clear that with the shorter polling period the CPU goes over 100C a lot less.

I did not notice any meaningful CPU usage increase when testing, at least `htop` kept the usage at 0.0%.

@spandruvada do you have some examples of async sensor inputs? Are those for more specialised hardware or are those available on Intel/AMD CPUs?

**Comment by cooper151288** [comment]
@Hermanio have you got details of your custom solution? 
I've been using poll interval of 1, with the ACPI p-state driver's (AMD Bulldozer) ondemand governor's "powersave bias" setting with PID control and the results are excellent when properly tuned, far better than plain cpufreq control, as it allows for some occupancy of boosted states during lightly threaded loads.
Intel p-state driver has a similar function so that might be worth trying. I'll try to get a graph up of both synthetic and real world use if you are interested.

**Comment by Hermanio** [comment]
@cooper151288 Here's my own take on controlling the CPU, not ideal but seems to work fine on my hardware: https://github.com/Hermanio/linux-cpu-manager

**Comment by spandruvada** [comment]
The  latest code on the master branch, dynamically polls at 1 second interval when it is close to the target temperature of action, before that it just  follows poll-interval setting.
