### ISSUE TITLE
thermald startup failed for Intel Xeon Gold 6138

### ISSUE THREAD

**Issue by chan-y-park** [intel/thermal_daemon#153]
Hi,

While investigating the CPU throttling issue of my server, I found that thermald failed to start at boot and I wonder if I can either fix it or run it safely with --ignore-cpuid-check.

First let me provide some information about my system, please let me know if additional information is required:

* Dell Precision 7920 Tower.
* dual Intel Xeon Gold 6138 CPU.
* Ubuntu 18.04.
* compiled and installed thermal_daemon v1.7.1 according to the instruction in README.

Then when I run thermald I get the following:

```
chan@kc-ml2-alpha:~/git-repos/thermal_daemon$ sudo systemctl start thermald.service
chan@kc-ml2-alpha:~/git-repos/thermal_daemon$ sudo systemctl status thermald.service
● thermald.service - Thermal Daemon Service
   Loaded: loaded (/lib/systemd/system/thermald.service; enabled; vendor preset:
   Active: inactive (dead) since Wed 2018-05-30 13:31:27 KST; 4s ago
  Process: 52734 ExecStart=/usr/sbin/thermald --no-daemon --dbus-enable (code=ex
 Main PID: 52734 (code=exited, status=1/FAILURE)

May 30 13:31:27 kc-ml2-alpha systemd[1]: Starting Thermal Daemon Service...
May 30 13:31:27 kc-ml2-alpha systemd[1]: Started Thermal Daemon Service.
May 30 13:31:27 kc-ml2-alpha thermald[52734]: 22 CPUID levels; family:model:step
May 30 13:31:27 kc-ml2-alpha thermald[52734]:  Need Linux PowerCap sysfs
May 30 13:31:27 kc-ml2-alpha thermald[52734]: Unsupported cpu model, use thermal
May 30 13:31:27 kc-ml2-alpha thermald[52734]: THD engine start failed
```

I am not sure if fixing this issue will resolve my original problem, which is that CPU throttling kicks in when I extensively use all the available CPUs (for example building TensorFlow from source code).

I'd be grateful if you can let me know how to fix this thermald issue or if it is safe to run thermald with option  --ignore-cpuid-check, with which thermald runs without failure.

**Comment by spandruvada** [comment]
On Tue, 2018-05-29 at 22:00 -0700, Chan Y. Park wrote:
> Hi,
> While investigating the CPU throttling issue of my server, I found
> that thermald failed to start at boot and I wonder if I can either
> fix it or run it safely with --ignore-cpuid-check.
> First let me provide some information about my system, please let me
> know if additional information is required:
You can use this but not sure if it will be helpful.
You said CPU is getting throttled. Since you are using all cores you
will not reach full turbo frequency, which can be reached by a single
CPU load.
So what is the the output of?
# rdmsr 0xce
# rdmsr 0x1ad

And also what frequency you are getting when you are observing that
CPUs are getting throttled?

Thanks,
Srinivas

**Comment by chan-y-park** [comment]
Hi Srinivas,
Thanks for your reply. I tried running rdmsr but it only returns an error message of "rdmsr: open: No such file or directory". Maybe I am doing something stupid? :$

And is there a way to get a real-time stream of CPU freq? Then I will do the stress test again while recording the freq.

**Comment by spandruvada** [comment]
On Mon, 2018-06-04 at 08:06 -0700, Chan Y. Park wrote:
> Hi Srinivas,
> Thanks for your reply. I tried running rdmsr but it only returns an
> error message of "rdmsr: open: No such file or directory". Maybe I am
> doing something stupid? :$
You may need to do
#modprobe msr

> And is there a way to get a real-time stream of CPU freq?
turbostat tool will show the frequency.

**Comment by spandruvada** [comment]
If it is resolved, please close.

**Comment by chan-y-park** [comment]
Thanks for your help, although it is not resolved, let me close it for now as I am making no progress yet.
