### ISSUE TITLE
Feature request: execute shell command

### ISSUE THREAD

**Issue by cooper151288** [intel/thermal_daemon#154]
Since some users may have already written scripts/programs to manage platform thermals or may have specific requirements for what to do to manage potential problems, is it possible to have a trip point execute a shell command when violated and when the temperature falls below the trip point?

**Comment by spandruvada** [comment]
It is doable. But need to check with security experts for security implication.

**Comment by spandruvada** [comment]
Basically we are not allowed to call to call system() to execute any program when running under root. That is the security requirement.

**Comment by cooper151288** [comment]
yeah that's a reasonable requirement. We don't want arbitrary shell commands being executed if someone injects a rogue config. Close this if you want, unless you can think of a better way.

**Comment by rbalint** [comment]
@spandruvada @cooper151288 How about allowing running executables with absolute path and arguments like it is done with systemd's `ExecStart=`? This does not need `system()`, just an `exec()` variant.
I'd like to use this feature to control a fan.

**Comment by spandruvada** [comment]
I have to check with security folks.

**Comment by rbalint** [comment]
That was not very verbose. I guess I'll offer a patch for the Debian package to carry.
