### ISSUE TITLE
Feature request: Sensor aggregation

### ISSUE THREAD

**Issue by cooper151288** [intel/thermal_daemon#155]
We currently have a virtual sensor interface where we can apply multipliers and offsets to sensors.
Is it possible to expand this by creating virtual sensors which have outputs calculated from multiple sensor outputs.
Many systems have multiple sensors which, if averaged/summed etc may provide more accuracy in determining whether the system needs to take action.

**Comment by spandruvada** [comment]
The current interface is just simple
=mx+c
but output of this can be input to virtual sensor.

If you have some system where you can manually experiment and suggest, it will be great.
