### ISSUE TITLE
implement threshold to stop with injections

### ISSUE THREAD

**Issue by jcbritobr** [intel/thermal_daemon#157]
Seems when thermald start cpu throtling, even when cpu is cool again the injections doesn't stop. This is a real killer machine.  There is something like a termal threshold that injections can be stoped?

**Comment by spandruvada** [comment]
This shouldn't happen. The throttling is removed slowly.

#systemctl stop thermald
#thermald --no-daemon --loglevel=info
and send the logs when you have this.

**Comment by spandruvada** [comment]
Please retry the latest code on the github master branch and reopen of you see issue,
