### ISSUE TITLE
CPU is probably overheating with Thermald v1.7.2 and auto-generated configuration

### ISSUE THREAD

**Issue by romanek-adam** [intel/thermal_daemon#158]
Hi!

When I do CPU-intensive activities I observe CPU temperature at 98\*C and it persists for long periods of time. While this happens the fan reaches 4500 rpm and the CPU frequency is ~2.7GHz. The critical temperature of my CPU is 100*C so I'm seriously worried about this.

Initially I was using Thermald v1.5 (actually 1.5-2ubuntu4). However after the switch to the latest 1.7.2 release things did not change at all.

During startup thermald reports some errors which could be related to the issue:

```
$ journalctl -u thermald
-- Logs begin at wto 2018-07-10 09:18:31 CEST, end at wto 2018-07-10 12:01:47 CEST. --
lip 10 09:18:32 olatec-dell systemd[1]: Starting Thermal Daemon Service...
lip 10 09:18:32 olatec-dell thermald[1134]: 22 CPUID levels; family:model:stepping 0x6:5e:3 (6:94:3)
lip 10 09:18:32 olatec-dell thermald[1134]: Polling mode is enabled: 4
lip 10 09:18:32 olatec-dell thermald[1134]: Using generated /usr/local/var/run/thermald/thermal-conf.xml.auto
lip 10 09:18:32 olatec-dell systemd[1]: Started Thermal Daemon Service.
lip 10 09:18:32 olatec-dell thermald[1134]: csys_fs::read exception /sys/class/thermal/thermal_zone4/trip_point_0_hyst
lip 10 09:18:32 olatec-dell thermald[1134]: csys_fs::read exception /sys/class/thermal/thermal_zone4/trip_point_1_hyst
lip 10 09:18:32 olatec-dell thermald[1134]: csys_fs::read exception /sys/class/thermal/thermal_zone4/trip_point_2_hyst
lip 10 09:18:32 olatec-dell thermald[1134]: csys_fs::read exception /sys/class/thermal/thermal_zone4/trip_point_3_hyst
lip 10 09:18:32 olatec-dell thermald[1134]: csys_fs::read exception /sys/class/thermal/thermal_zone4/trip_point_4_hyst
lip 10 09:18:32 olatec-dell thermald[1134]: XML zone: invalid sensor type TMEM
lip 10 09:18:32 olatec-dell thermald[1134]: Zone update failed: unable to bind
lip 10 12:00:46 olatec-dell systemd[1]: Stopping Thermal Daemon Service...
lip 10 12:00:46 olatec-dell thermald[1134]: Terminating ...
lip 10 12:00:47 olatec-dell thermald[1134]: terminating on user request ..
lip 10 12:00:48 olatec-dell systemd[1]: Stopped Thermal Daemon Service.
```

I attached the [auto-generated thermal-conf.xml](https://github.com/intel/thermal_daemon/files/2179844/thermal-conf.xml.txt) and a [log from a debug run](https://github.com/intel/thermal_daemon/files/2179869/thermald.log) of thermald v1.7.2 captured while observing the overheating issue.

My system is:
HW: Dell Latitude E5470
OS: Ubuntu 16.04 64-bit
Kernel: 4.4.0-130-generic
CPU: Intel(R) Core(TM) i7-6820HQ CPU @ 2.70GHz

Please let me know if you need anything else.

**Comment by spandruvada** [comment]
The platform setting is calling for 99C as control point from your log. So thermald will behave as you observed.
But you can change that using one of these methods:
- Use thermal monitor and reduce passive trip to some lower value
- Use dbus message to change. For example the below will change to 90C
sudo -s
    # dbus-send   --system   --dest=org.freedesktop.thermald  /org/freedesk‐
       top/thermald org.freedesktop.thermald.SetUserPassiveTemperature string:B0D4
       uint32:90000
- Copy /usr/local/var/run/thermald/thermal-conf.xml.auto to /usr/local/etc/thermald/ (or conf directory based on build prefix looks like you use prefix=/usr")

You can see which file path is getting used in log in debug mode.

Edit the copied file in the conf directory ( /usr/local/etc/thermald/ or /etc/thermald/)

From
..
..
<TripPoint>
							<SensorType>B0D4</SensorType>
							<Temperature>*</Temperature>
							<type>passive</type>

to
...
..
<TripPoint>
							<SensorType>B0D4</SensorType>
							<Temperature>90000</Temperature>
							<type>passive</type>

**Comment by romanek-adam** [comment]
With the change you suggested the CPU temperature reaches 92-93C at times, with 90C on average. This is very good. Thanks! I attached the [correct config](https://github.com/intel/thermal_daemon/files/2188598/thermal-conf-passive-90000.xml.txt) for anyone interested.

Now where does this 99C value come from? I'm digging into this as I don't think it's a safe value.

**Comment by spandruvada** [comment]
On Thu, 2018-07-12 at 05:34 -0700, Adam Romanek wrote:
> With the change you suggested the CPU temperature reaches 92-93C at
> times, with 90C on average. This is very good. Thanks! I attached the
> correct config for anyone interested.
> Now where does this 99C value come from? I'm digging into this as I
> don't think it's a safe value.
It is coming from ACPI configuration of B0D4 device.
You can see that in /sys/class/thermal/thermal_zone*/trip_point_*_temp 
where attribute type = B0D4 and trip_point_type is passive.

**Comment by romanek-adam** [comment]
@spandruvada thanks for your support!
