### ISSUE TITLE
thermald not starting on Lenovo laptop with AMD CPU

### ISSUE THREAD

**Issue by mutluit** [intel/thermal_daemon#176]
Hi,
is this tool for Intel devices only? The Debian repository does not mention of any such limitation,
so I installed it, but it does not start. The log says the following (see below).

The machine is a Lenovo E545 laptop with an x4 AMD CPU (AMD A10-5750M APU with Radeon(tm) HD Graphics), Debian 8, kernel 4.19.0.
There is no /etc/acpi* on this machine. Or do I need to install some other software or driver for this?

How should my /etc/thermal-conf.xml look like for this machine?

Btw, the tool "sensors" (lm-sensors) gives the following output.
I was hoping for a tool which can read the CPU temps as well fan-speeds.

radeon-pci-0008
Adapter: PCI adapter
temp1:        +35.0°C  (crit = +120.0°C, hyst = +90.0°C)

thinkpad-isa-0000
Adapter: ISA adapter
Fan:            0 RPM

k10temp-pci-00c3
Adapter: PCI adapter
Core0 Temp:   +36.6°C  (high = +70.0°C)
                       (crit = +100.0°C, hyst = +99.0°C)

thermald log output:
################
: thermald ver 1.3: Ready to serve requests: Daemonizing.. 
: NO RAPL sysfs present  
: Running on a vanilla kernel 
: Polling mode is enabled: 4 
: thd_read_default_thermal_sensors loaded 0 sensors  
: Thermal DTS: No coretemp sysfs found!! 
: failed to open /dev/acpi_thermal_rel  
: failed to open /dev/acpi_thermal_rel  
: TRT/ART read failed 
:  Dumping parsed XML Data 
:  *** Index 0 *** 
: Name: GenericX86LaptopDevice 
: UUID:  
: type: 0 
: 	Sensor 0  
: 	 Name: TSKN 
: 	 Path:  
: 	 Async Capable: 1 
: 	Zone 0  
: 	 Name: SKIN 
: 		 Trip Point 0  
: 		  temp 55000  
: 		  trip type 2  
: 		  hyst id 0  
: 		  sensor type TSKN  
: 		  cdev index 0  
: 			  type rapl_controller  
: 			  influence 100  
: 			  SamplingPeriod 16  
: 		  cdev index 1  
: 			  type intel_powerclamp  
: 			  influence 100  
: 			  SamplingPeriod 12  
:  *** Index 1 *** 
: Name: ExamplePlatformName 
: UUID: ExampleUUID 
: type: 0 
: 	Sensor 0  
: 	 Name: TSKN 
: 	 Path:  
: 	 Async Capable: 1 
: 	Sensor 1  
: 	 Name: example_sensor_1 
: 	 Path: /some_path 
: 	 Async Capable: 0 
: 	Sensor 2  
: 	 Name: example_thermal_sysfs_sensor 
: 	 Path:  
: 	 Async Capable: 1 
: 	Zone 0  
: 	 Name: ExampleZonetype 
: 		 Trip Point 0  
: 		  temp 75000  
: 		  trip type 1  
: 		  hyst id 0  
: 		  sensor type example_sensor_1  
: 		  cdev index 0  
: 			  type example_cooling_device  
: 			  influence 100  
: 			  SamplingPeriod 12  
: 	Cooling Dev 0  
: 		Type: example_cooling_device 
: 		Path:  
: 		Min: 0 
: 		Max: 50 
: 		Step: 10 
: 		AutoDownControl: 0 
: 	 PID: Kp 0.001000 
: 	 PID: Ki 0.000100 
: 	 PID: Kd 0.000100 
: Product Name matched [wildcard] 
: sensor id 0: No temp sysfs for reading raw temp 
: thd_read_default_cooling devices loaded 4 cdevs  
: powercap RAPL no long term time window 
: Product Name matched [wildcard] 
: 1: Processor, C:0 MN: 0 MX:3 ST:1 pt:/sys/class/thermal/ rd_bk 0  
: 2: Processor, C:0 MN: 0 MX:3 ST:1 pt:/sys/class/thermal/ rd_bk 0  
: 0: Processor, C:0 MN: 0 MX:3 ST:1 pt:/sys/class/thermal/ rd_bk 0  
: 3: Processor, C:0 MN: 0 MX:3 ST:1 pt:/sys/class/thermal/ rd_bk 0  
: 4: cpufreq, C:0 MN: 0 MX:0 ST:1 pt:/sys/devices/system/cpu/ rd_bk 1  
: thd_read_default_thermal_zones loaded 0 zones  
: zone cpu will be created  
: /sys/class/hwmon/hwmon2/name->radeon 
: /sys/class/hwmon/hwmon0/name->thinkpad 
: /sys/class/hwmon/hwmon1/name->k10temp 
: Thermal DTS or hwmon: No Zones present Need to configure manually 
: Product Name matched [wildcard] 
: XML zone: invalid sensor type TSKN 
: Zone update failed: unable to bind  
: No Thermal Zones found  
: No thermal sensors found 
: THD engine start failed:

**Comment by cooper151288** [comment]
It should work on your CPU- you'll need to set the path configuration item to read from your sensor of choice and your preferred cooling device. Ill send an example later.
Is it a locked processor? There are ways of doing power clamping on AMD CPUs that ive tested on fx-8350,a4-4000 and r464-l which work despite poor documentation, options are best on unlocked but you can do it on locked (and even "overclock" the locked units)

**Comment by cooper151288** [comment]
Does the fan spin up under load? What output do you get from sensors when you can hear the fan?
Does your laptop shut down before k10temp reaches 100degC?
Does your laptop overheat?
Big spikes in CPU with short loads?
This CPU is very similar to one I have.
On this class of CPU, there is a (somewhat) configurable (can lower it all the way, raise it slightly or force low turbo speed) TDP cap- on unlocked CPUs, you can raise the limit to 256W if you so desire. Thermal throttling temp is  also configurable. Hardware control is definitely more responsive- we get ~millisecond response this way.
I do this on an AMD R-464L (same socket similar model, embedded, industrial temperature variant, 35W)

Reply here or send a message with your requirements and I'll see what I can do, on a hardware level.
