### ISSUE TITLE
Broadwell intel i7-6850 stepping 0x6:4f:1 CPU-ID missing

### ISSUE THREAD

**Issue by gia-goldy** [intel/thermal_daemon#179]

**Comment by gia-goldy** [comment]
thermald --no-daemon --loglevel=info
RAPL domain count 0
RAPL domain count 1
20 CPUID levels; family:model:stepping 0x6:4f:1 (6:79:1)
 Need Linux PowerCap sysfs 
failed to open /dev/acpi_thermal_rel 
failed to open /dev/acpi_thermal_rel 
TRT/ART read failed
I/O warning : failed to load external entity "/etc/thermald/thermal-conf.xml"
error: could not parse file /etc/thermald/thermal-conf.xml
Unsupported cpu model, use thermal-conf.xml file or run with --ignore-cpuid-check 
THD engine start failed

run fine with "--ignore-cpuid-check".  Need more information about the CPU?

**Comment by spandruvada** [comment]
It is server CPU model. We don't support.
