### ISSUE TITLE
Unsupported CPU model: 0x6:4f:1 (6:79:1)

### ISSUE THREAD

**Issue by cjschroeder** [intel/thermal_daemon#180]
thermald[]: 20 CPUID levels; family:model:stepping 0x6:4f:1 (6:79:1)
thermald[]:  Need Linux PowerCap sysfs
thermald[]: Unsupported cpu model, use thermal-conf.xml file or run with --ignore-cpuid-check

cpuinfo version: (3, 3, 0)
Vendor ID: GenuineIntel
Hardware Raw:
Brand: Intel(R) Xeon(R) CPU E5-1650 v4 @ 3.60GHz
Hz Advertised: 3.6000 GHz
Hz Actual: 2.0597 GHz
Hz Advertised Raw: (3600000000, 0)
Hz Actual Raw: (2059664000, 0)
Arch: X86_64
Bits: 64
Count: 12
Raw Arch String: x86_64
L2 Cache Size: 15360 KB
L2 Cache Line Size:
L2 Cache Associativity:
Stepping: 1
Model: 79
Family: 6
Processor Type:
Extended Model:
Extended Family:
Flags: 3dnowprefetch, abm, acpi, adx, aes, aperfmperf, apic, arat, arch_perfmon, avx, avx2, bmi1, bmi2, bts, cat_l3, cdp_l3, clflush, cmov, constant_tsc, cpuid, cpuid_fault, cq
m, cqm_llc, cqm_mbm_local, cqm_mbm_total, cqm_occup_llc, cx16, cx8, dca, de, ds_cpl, dtes64, dtherm, dts, epb, ept, ept_ad, erms, est, f16c, flexpriority, flush_l1d, fma, fpu,
fsgsbase, fxsr, hle, ht, ibpb, ibrs, ida, intel_ppin, intel_pt, invpcid, invpcid_single, lahf_lm, lm, mca, mce, mmx, monitor, movbe, msr, mtrr, nonstop_tsc, nopl, nx, pae, pat,
pbe, pcid, pclmulqdq, pdcm, pdpe1gb, pebs, pge, pln, pni, popcnt, pse, pse36, pti, pts, rdrand, rdseed, rdt_a, rdtscp, rep_good, rtm, sdbg, sep, smap, smep, smx, ss, ssbd, sse
, sse2, sse4_1, sse4_2, ssse3, stibp, sysc

**Comment by spandruvada** [comment]
This has a server CPU model. We don't support server models as it causes regressions .
