### ISSUE TITLE
Threadripper 1950x not supported

### ISSUE THREAD

**Issue by pfc** [intel/thermal_daemon#186]
With a 1950X thermal throttling does not seem to work.
running "thermald --no-daemon" leads to:
```
NO RAPL sysfs present 
I/O warning : failed to load external entity "/etc/thermald/thermal-conf.xml"
error: could not parse file /etc/thermald/thermal-conf.xml
Unsupported cpu model, use thermal-conf.xml file or run with --ignore-cpuid-check 
THD engine start failed
```
and "thermald --no-daemon --ignore-cpuid-check"
```
NO RAPL sysfs present 
Polling mode is enabled: 4
Thermal DTS: No coretemp sysfs found
sensor id 1 : No temp sysfs for reading raw temp
sensor id 1 : No temp sysfs for reading raw temp
sensor id 1 : No temp sysfs for reading raw temp
I/O warning : failed to load external entity "/etc/thermald/thermal-conf.xml"
error: could not parse file /etc/thermald/thermal-conf.xml
sysfs open failed 
sysfs open failed 
I/O warning : failed to load external entity "/etc/thermald/thermal-conf.xml"
error: could not parse file /etc/thermald/thermal-conf.xml
Thermal DTS or hwmon: No Zones present Need to configure manually
I/O warning : failed to load external entity "/etc/thermald/thermal-conf.xml"
error: could not parse file /etc/thermald/thermal-conf.xml
No thermal sensors found
THD engine start failed
```
The file "/etc/thermald/thermal-conf.xml" does not exist.  I have attempted to use example files from online but there does not seem to be any documentation as to how to generate this file for an AMD system.

**Comment by kalaolani** [comment]
Why is this closed with no reply? Same issue here.

sudo thermald --no-daemon --ignore-cpuid-check

[1605383719][WARN]NO RAPL sysfs present 
[1605383719][MSG]Polling mode is enabled: 4
[1605383721][WARN]Thermal DTS: No coretemp sysfs found
[1605383721][MSG]Config file /etc/thermald/thermal-conf.xml does not exist
[1605383721][MSG]Config file /etc/thermald/thermal-conf.xml does not exist
[1605383721][ERR]Thermal DTS or hwmon: No Zones present Need to configure manually
[1605383721][MSG]Config file /etc/thermald/thermal-conf.xml does not exist
[1605383721][ERR]No thermal sensors found
[1605383721][ERR]THD engine start failed

**Comment by pfc** [comment]
I don't think anyone is interested in fixing it...
I ended up writing my own python script to manage thermals.  I'm not familiar enough with this project to contribute.

**Comment by spandruvada** [comment]
If someone from AMD is interested, they can contribute. This can hurt performance if not enabled correctly.


On Sat, 2020-11-14 at 20:01 -0800, pfc wrote:

I don't think anyone is interested in fixing it...
I ended up writing my own python script to manage thermals. I'm not familiar enough with this project to contribute.
