### ISSUE TITLE
Clear Linux: support "stateless" configuration paradigm, remove hard dependencies on XML config/control files

### ISSUE THREAD

**Issue by thac0** [intel/thermal_daemon#188]
Summary says it all. [Clear Linux](https://clearlinux.org/) follows a [stateless](https://github.com/clearlinux/clr-man-pages/blob/master/stateless.7.rst) configuration philosophy. Practical translation: push for all system services and daemons (e.g. thermald) to reasonably function in the absence of config/control files.

Objectives:
- Ensure that thermald hard-codes "sane" defaults for reasonable operation
- Limit syslog/journald output in a stateless environment (currently it's quite chatty)

PS: I'm willing to help make this happen.

**Comment by mrkz** [comment]
FWIW, I recall testing this on Fedora as well once. 

The configuration file is not strictly required as I recall having it populated with commented lines, so I believe that `thermal_daemon` already ships sane defaults, just this annoying warning popping up :sweat_smile:

**Comment by thac0** [comment]
> The configuration file is not strictly required as I recall having it populated with commented lines, so I believe that `thermal_daemon` already ships sane defaults, just this annoying warning popping up sweat_smile

I _assume_ that's the case, @mrkz . Part of this will involve an audit to convince myself that thermald is sane in a stateless environ. :grin:
