### ISSUE TITLE
--poll-interval=0, when and how to send THERMAL_ZONE_NOTIFY message to the thermal_engine

### ISSUE THREAD

**Issue by lindachai** [intel/thermal_daemon#197]
hi , there
here is the question，the engine_thread has 3 methods to check thermal status，1st is periodic polling，check whether is any trip point acrossed，2nd is listen to kobj_event from the netlink，and 3rd is get message from the pipe。
As for the 3rd method，if we get THERMAL_ZONE_NOTIFY message，then to send temperature notification，now the question is ，I could not find who and when to send THERMAL_ZONE_NOTIFY？ Your answer will be very appreciated。

**Comment by lindachai** [comment]
hi , there
here is the question，the engine_thread has 3 methods to check thermal status，1st is periodic polling，check whether is any trip point acrossed，2nd is listen to kobj_event from the netlink，and 3rd is get message from the pipe。
As for the 3rd method，if we get THERMAL_ZONE_NOTIFY message，then to send temperature notification，now the question is ，I could not find who and when to send THERMAL_ZONE_NOTIFY？ Your answer will be very appreciated。

**Comment by spandruvada** [comment]
On Tue, 2019-07-30 at 00:35 -0700, lindachai wrote:
> hi , there
> 
> here is the question，the engine_thread has 3 methods to check thermal
> status，1st is periodic polling，check whether is any trip point
> acrossed，2nd is listen to kobj_event from the netlink，and 3rd is get
> message from the pipe。
> 
> As for the 3rd method，if we get THERMAL_ZONE_NOTIFY message，then to
> send temperature notification，now the question is ，I could not find
> who and when to send THERMAL_ZONE_NOTIFY？ Your answer will be very
> appreciated。
This is for some Android implementation where some external agent
notifies a temperature change to trigger reread of temperature and take
action. 
Thanks,Srinivas

**Comment by lindachai** [comment]
hi，Srinivas
I got it, thanks a lot for your answer


 Linda
| |
柴黎娜
|
|
邮箱：chailina0501@163.com
|

签名由 网易邮箱大师 定制

On 07/31/2019 20:55, Srinivas Pandruvada wrote:
On Tue, 2019-07-30 at 00:35 -0700, lindachai wrote:
> hi , there
>
> here is the question，the engine_thread has 3 methods to check thermal
> status，1st is periodic polling，check whether is any trip point
> acrossed，2nd is listen to kobj_event from the netlink，and 3rd is get
> message from the pipe。
>
> As for the 3rd method，if we get THERMAL_ZONE_NOTIFY message，then to
> send temperature notification，now the question is ，I could not find
> who and when to send THERMAL_ZONE_NOTIFY？ Your answer will be very
> appreciated。
This is for some Android implementation where some external agent
notifies a temperature change to trigger reread of temperature and take
action.
Thanks,Srinivas
