### ISSUE TITLE
Thermald throtls fan when power_clamp and rapl kick in

### ISSUE THREAD

**Issue by hernot** [intel/thermal_daemon#202]
Hi
I'm trying to get a proper configuration of thermald for being able to run system at full performance as long and constant as possible while doing cpu intensive computations with little to no intermittent IO.

Documentation and examples were already quite helpful to get thermald control sort of the fan on my some years old ThinkPad L440 but what i observe is, at least that is my perception, that thermald tries to spin-up fan when temperature increases and throttles it again when the fan alone is not able to keep temperature below limit for power_clamp and rapl_controller. Which is annoying as computations if run at full speed last at least 30 min and longer with throttling back and forth this is extended to > 1h and more.

How to modify configuration such, that thermald does the following in performance mode

1) Spin up fan
2) In addition activate power_clamp if fan is not sufficient but keep fan at full speed 
3) In addition activate rapl_controller if fan and power_clamp are not sufficient keep the other two at max
4) stop rapl_controller first and check if temperature goes up again
5) stop power_clamp and check if temperature goes up again
6) finally throtl fan down to 0 when temperature is still safe

I somehow miss something to get that scheme working with thermald. Something must be still not corect in my configuration.

[thermal-conf.xml.txt](https://github.com/intel/thermal_daemon/files/3578242/thermal-conf.xml.txt)

**Comment by hernot** [comment]
Hi Scinivas

Inline Response (answers below questions asked)
Message sent on Donnerstag, 05.09.2019, 12:36 -0700 by Srinivas
Pandruvada:
> If you only wants thermald to what you defined in the configuration
> run
> with the option
> --ignore-default-control
> This will disable all the default compensation. I think this is what
> you may need here.

Just to better understand how thermald processes configuration, admit
not read introduction to thermald in wiki properly. 

The configuration defined in the xml is not used exclusively but as an
extension and refinement of the built in default control paradigma(s).
In case configuration in xml should be used exclusively (initially for
testing only) than thermald must be instructed to ignore built-in
default-control paradigmas? 

Thanks
Xristoph

-- 
Christoph, Julia, R. Hintermüller
Eisenhandstraße 33/23
4020 Linz
Austria
Tel.: +43 650 8827347
mail: christoph@out-world.com
mail: julia@out-world.com
www: http://www.out-world.com

**Comment by spandruvada** [comment]
On Fri, 2019-09-06 at 00:18 -0700, hernot wrote:
> Hi Scinivas
> 
> 
> 
> Inline Response (answers below questions asked)
> 
> Message sent on Donnerstag, 05.09.2019, 12:36 -0700 by Srinivas
> 
> Pandruvada:
> 
> > If you only wants thermald to what you defined in the configuration
> 
> > run
> 
> > with the option
> 
> > --ignore-default-control
> 
> > This will disable all the default compensation. I think this is
> what
> 
> > you may need here.
> 
> 
> 
> Just to better understand how thermald processes configuration, admit
> 
> not read introduction to thermald in wiki properly. 
> 
> 
> 
> The configuration defined in the xml is not used exclusively but as
> an
> 
> extension and refinement of the built in default control
> paradigma(s).
> 
> In case configuration in xml should be used exclusively (initially
> for
> 
> testing only) than thermald must be instructed to ignore built-in
> 
> default-control paradigmas? 
Yes. The built in are for safety purpose, if the configuration file is
not enough.But some users they prefer configuration file to control.
Thanks,Srinivas

**Comment by hernot** [comment]
Hi @spandruvada 
Thank you very much again. Just to keep you posted I think I have a less crude way to get the expected behaviour. I stumbled over while migrating my old shared use laptop to my new laptops, one  for office and one for office use.

On both setups i have in addition to configuring the active fan device using the thermald-conf.xml i added the cooling device type crated for the fan too the thermald-cpu-cdev-order.xml and reordered the list of devices such that the fan is on top of the list, followed by powerclamp, rapl_controller, pstate and cpufreq last.

This makes thermald spin up fan and keep it running until load and thus temperature drops again. Throttling only happens now if fan and (unobserved assumed) powerclamp are not sufficient.
