### ISSUE TITLE
Doesn't compile with clang

### ISSUE THREAD

**Issue by andrei-pavel** [intel/thermal_daemon#206]
Hi,
I have c++ set to clang++ and build fails with:
```
error: unknown warning option '-Wunused-but-set-variable'; did you mean '-Wunused-const-variable'? [-Werror,-Wunknown-warning-option]
error: unknown warning option '-Wclobbered' [-Werror,-Wunknown-warning-option]
```
Could you force g++ or hide those flags for clang++ on the configuration step?

**Comment by spandruvada** [comment]
On Tue, 2019-12-10 at 00:17 -0800, Andrei Pavel wrote:

Hi,
I have c++ set to clang++ and build fails with:

error: unknown warning option '-Wunused-but-set-variable'; did you mean '-Wunused-const-variable'? [-Werror,-Wunknown-warning-option]

error: unknown warning option '-Wclobbered' [-Werror,-Wunknown-warning-option]

Could you force g++ or hide those flags for clang++ on the configuration step?

We can remove those option when clang++ is used? You can submit a change.

Thanks,
Srinivas
