### ISSUE TITLE
thermald for amd cpus?

### ISSUE THREAD

**Issue by ghcatt** [intel/thermal_daemon#209]
the readme is a bit vague on this matter.

clear and brief, does thermald make sense with amd cpus? anything special to follow in this regard other than the mentioned prerequisites?

**Comment by spandruvada** [comment]
With the configuration file, nothing stops using on AMD CPUs. Need to find paths for the sensors on AMD systems.

**Comment by ghcatt** [comment]
thank you for replying.

one more question that bothers me - can thermald be used on top of [AMDGPU](https://wiki.archlinux.org/index.php/Fan_speed_control#AMDGPU_sysfs_fan_control)'s kernel driver fan control without conflicts?

by installing thermald, i hope to see a benefit for my laptop's fan not going wild ever so often for short periods of time, even on moderate temperatures.

the kernel driver obviously is way too strict in this regard?


p.s.: i also have lm_sensors installed. unfortunately, the detection routine did not find a valid sensor for the fan, so fancontrol is of no use here.

will this probably be the same case with thermald then?
