### ISSUE TITLE
Quick Question about Thermald.

### ISSUE THREAD

**Issue by ghostwheelai** [intel/thermal_daemon#218]
Hello. I spent an evening googling and didn't get any examples on how to configure cooling devices.

My laptop overheats a lot and I use thermald By default, it drops frequency to 800Mhz, which makes Laptop drop fps in games. I was wondering is it possible to configure thermal to drop frequency to another value. 1.2Ghz maybe and let Laptop cool down slowly...

My thermal-conf.xml which has no effect. Thermal detects that passive point is reached, but takes no action.

https://pastebin.com/w9jKAsCE

Can someone tell me please what am I doing wrong? Creating an issue on github is last resort

**Comment by spandruvada** [comment]
On Mon, 2020-03-09 at 13:39 -0700, also_east wrote:

Hello. I spent an evening googling and didn't get any examples on how to configure cooling devices.

My laptop overheats a lot and I use thermald By default, it drops frequency to 800Mhz, which makes Laptop drop fps in games. I was wondering is it possible to configure thermal to drop frequency to another value. 1.2Ghz maybe and let Laptop cool down slowly...

You have setup a limit to 60C, which is too low for many laptops. It depends on what types of options available to you on this laptop whether you can do do such fine grain control.
Stop the thermald service "systemctl stop thermald" and run command line and collect log and attach output "thermald --no-daemon --loglevel=info".

Thanks!



My thermal-conf.xml which has no effect. Thermal detects that passive point is reached, but takes no action.

https://pastebin.com/w9jKAsCE

Can someone tell me please what am I doing wrong? Creating an issue on github is last resort

**Comment by stTheme** [comment]
> You have setup a limit to 60C, which is too low for many laptops. It depends on what types of options available to you on this laptop whether you can do do such fine grain control. Stop the thermald service "systemctl stop thermald" and run command line and collect log and attach output "thermald --no-daemon --loglevel=info". Thanks!

Thanks for reply. I setup this limit for testing purposes. If it would work I would increase it to 90. I did run thermald --no-daemon --loglevel=info both without thermal-conf.xml and with it to see what is going on.

without thermal-conf.xml https://pastebin.com/bftG37cX
with my thermal-conf.xml https://pastebin.com/EErctcem

I think I didn't specify action for cooler device or smth like that. Or need to use another one?

Daemon works. It just doesn't with my trigger.

**Comment by spandruvada** [comment]
On Mon, 2020-03-09 at 16:53 -0700, also_east wrote:

You can play with power limit at different temperature. Like here we set 90C 30W at 85C 25W and so on:


<?xml version="1.0"?>
 
 <ThermalConfiguration>
 <Platform>
<Name> test </Name>
<ProductName>*</ProductName>
<Preference>QUIET</Preference>
<ThermalZones>
<ThermalZone>
<Type>auto_zone_0</Type>
<TripPoints>
<TripPoint>
<SensorType>x86_pkg_temp</SensorType>
<Temperature>90000</Temperature>
<Type>Passive</Type>
<CoolingDevice>
<Type>rapl_controller</Type>
<SamplingPeriod>3</SamplingPeriod>
<TargetState>30000000</TargetState>
</CoolingDevice>
</TripPoint>
</TripPoints>
</ThermalZone>
<ThermalZone>
<Type>auto_zone_0</Type>
<TripPoints>
<TripPoint>
<SensorType>x86_pkg_temp</SensorType>
<Temperature>850000</Temperature>
<Type>Passive</Type>
<CoolingDevice>
<Type>rapl_controller</Type>
<SamplingPeriod>3</SamplingPeriod>
<TargetState>25000000</TargetState>
</CoolingDevice>
</TripPoint>
</TripPoints>
</ThermalZone>
<ThermalZone>
<Type>auto_zone_0</Type>
<TripPoints>
<TripPoint>
<SensorType>x86_pkg_temp</SensorType>
<Temperature>800000</Temperature>
<Type>Passive</Type>
<CoolingDevice>
<Type>rapl_controller</Type>
<SamplingPeriod>3</SamplingPeriod>
<TargetState>20000000</TargetState>
</CoolingDevice>
</TripPoint>
</TripPoints>
</ThermalZone>
</ThermalZones>
</Platform>
</ThermalConfiguration>




You have setup a limit to 60C, which is too low for many laptops. It depends on what types of options available to you on this laptop whether you can do do such fine grain control. Stop the thermald service "systemctl stop thermald" and run command line and collect log and attach output "thermald --no-daemon --loglevel=info". Thanks!

Thanks for reply. I setup this limit for testing purposes. If it would work I would increase it to 90. I did run thermald --no-daemon --loglevel=info both without thermal-conf.xml and with it to see what is going on.

without thermal-conf.xml https://pastebin.com/bftG37cX
with my thermal-conf.xml https://pastebin.com/EErctcem

I think I didn't specify action for cooler device or smth like that. Or need to use another one?

Daemon works. It just doesn't with my trigger.

**Comment by stTheme** [comment]
> You can play with power limit at different temperature. Like here we set 90C 30W at 85C 25W and so on:

I don't think I understand power and processors well enough to play with voltage. I just want to control the frequency of CPU when it's throttling. don't want to break stuff.

I just didn't find any examples (being googling all evening) on how to do it with cpufreq (it's the governer I understand a little) cooling device. What numbers should I put into <TargetState></TargetState>?

Or can I do it with another type of cooling device?

**Comment by spandruvada** [comment]
These power limits will not break stuff, it will be ignored if invalid.
You can do with cpufreq, but is more complex.
