### ISSUE TITLE
Linux 5.6 - Generic Idle Cooling Driver

### ISSUE THREAD

**Issue by francoism90** [intel/thermal_daemon#220]
https://git.kernel.org/pub/scm/linux/kernel/git/torvalds/linux.git/diff/Documentation/driver-api/thermal/cpu-idle-cooling.rst?id=0a1990a2d1f2217db20b30f915f48d9b8b976949

Will this cause issues when running both the generic idle cooling driver and thermald at the same time? What makes thermald better then the generic one and/or visa-versa? :)

Thanks.

**Comment by spandruvada** [comment]
On Mon, 2020-03-30 at 01:02 -0700, François M. wrote:

https://git.kernel.org/pub/scm/linux/kernel/git/torvalds/linux.git/diff/Documentation/driver-api/thermal/cpu-idle-cooling.rst?id=0a1990a2d1f2217db20b30f915f48d9b8b976949

Will this cause issues when running both the generic idle cooling driver and thermald at the same time? What makes thermald better then the generic one and/or visa-versa? :)

No. This is a driver which needs to be used. This is similar to intel-powerclamp driver which is used by the therrmald.
intel_powerclamp driver can be changed to use this new framework.

Thanks,
Srinivas


Thanks.

**Comment by francoism90** [comment]
@spandruvada Thanks for your explanation!
