### ISSUE TITLE
unchecked read/write failures using sysfs.read() and sysfs.write()

### ISSUE THREAD

**Issue by ColinIanKing** [intel/thermal_daemon#223]
Hi there, I ran some static analysis on thermal_daemon on today's tip and there are calls to sysfs.read() and sysfs.write() that don't check for read/write failes in src/thd_parse.cpp in void cthd_engine::takeover_thermal_control():

```
555                                if (sysfs.exists(policy.str().c_str())) {
556                                        sysfs.read(policy.str(), curr_policy);
557                                        zone_preferences.push_back(curr_policy);
558                                        sysfs.write(policy.str(), "user_space");
559                                }
```

It may be worth adding some sanity checks in case the I/O fails.

**Comment by spandruvada** [comment]
Hi Colin,

On Thu, 2020-04-09 at 03:12 -0700, Colin Ian King wrote:

Hi there, I ran some static analysis on thermal_daemon on today's tip and there are calls to sysfs.read() and sysfs.write() that don't check for read/write failes in src/thd_parse.cpp in void cthd_engine::takeover_thermal_control():

555                                if (sysfs.exists(policy.str().c_str())) {

556                                        sysfs.read(policy.str(), curr_policy);

557                                        zone_preferences.push_back(curr_policy);

558                                        sysfs.write(policy.str(), "user_space");

559                                }

It may be worth adding some sanity checks in case the I/O fails.

Fixed.

Thanks,
Srinivas

**Comment by ColinIanKing** [comment]
Thanks!
