### ISSUE TITLE
Can't stop default zones from tripping

### ISSUE THREAD

**Issue by ramonmaruko** [intel/thermal_daemon#232]
My laptop has default thermal zones where the tripping point is 75050. How do I turn the default thermal zones off?

The command arguments I have tried are:
`thermald --no-daemon --loglevel=debug --disable-active-power --ignore-default-control`
and
`thermald --no-daemon --loglevel=debug --ignore-default-control`
I am using the `thermal-conf.xml.auto` generated from `dptfxtract` but with a modified power limit. I am attaching the config file and the debug log for your perusal. I started the stress test at around `1590602183`.

[thermald.log](https://github.com/intel/thermal_daemon/files/4690835/thermald.log)
[thermal-conf.xml.auto.txt](https://github.com/intel/thermal_daemon/files/4690845/thermal-conf.xml.auto.txt)

**Comment by ramonmaruko** [comment]
I am also adding the output of `acpidump` and `dptfxtract`
[output.zip](https://github.com/intel/thermal_daemon/files/4690913/output.zip)

**Comment by spandruvada** [comment]
I don't see any throttling done by thermald (please point me, if you see).
Check if  cat /sys/bus/pci/devices/0000\:00\:04.0/tcc_offset_degree_celsius
is throttling (This is offset from max temp).

**Comment by ramonmaruko** [comment]
```
# cat /sys/bus/pci/devices/0000:00:04.0/tcc_offset_degree_celsius
5
```

I noticed something weird. This only happens when I am docked using the
ThinkPad Thunderbolt 3 Workstation Dock (230W). The dock is supposed to proved
a maximum of 230W to the connected laptop and this laptop only requires 135W.

When I am connected using just the 135W power adapter, the stress test will
easily cause package0 temperature to rise up to ~95C.

The weird part is that when I enable the battery charging thresholds using
`/sys/class/power_supply/BAT0/charge_start_threshold` and
`/sys/class/power_supply/BAT0/charge_stop_threshold`, the 70C limit is also
gone; even when I am just using the dock.

So I guess this isn't a bug or issue with `thermald` but a bug on my laptop's
firmware?

**Comment by spandruvada** [comment]
This may not be a bug in the firmware, but may be by design.
