### ISSUE TITLE
[Clevo N151CU] i5-10210U CPU performance regressions

### ISSUE THREAD

**Issue by drjhe** [intel/thermal_daemon#233]
With thermald 1.9.1 and the config below, when stressed the processor goes into maximum turbo boost (about 3.5GHz, 35W) from idle for a good 15 seconds of high performance, until it hits 92C and then it drops straight to about 2.4GHz at 15W -- the TDP, whereupon the temperature holds steady.

```
<?xml version="1.0"?>
<ThermalConfiguration>
  <Platform>
    <Name>Reduce maximum temperature for safety</Name>
    <ProductName>*</ProductName>
    <Preference>QUIET</Preference>
    <PPCC>
      <PowerLimitIndex>0</PowerLimitIndex>
      <PowerLimitMinimum>3000</PowerLimitMinimum>
      <PowerLimitMaximum>15000</PowerLimitMaximum>
      <TimeWindowMinimum>20000</TimeWindowMinimum>
      <TimeWindowMaximum>30000</TimeWindowMaximum>
      <StepSize>100</StepSize>
    </PPCC>
    <ThermalZones>
      <ThermalZone>
        <Type>cpu</Type>
        <TripPoints>
          <TripPoint>
            <Temperature>92000</Temperature>
            <type>passive</type>
          </TripPoint>
        </TripPoints>
      </ThermalZone>
    </ThermalZones>
  </Platform>
</ThermalConfiguration>
```

This machine has no DPTF table, and I consider this the optimal behaviour balancing cooling with performance.

With the same config, I see what I consider to be performance regressions traced to the following commits:
- eeadf7d -- after hitting the 92C limit, the CPU clock drops down to 1.6GHz for 5-10 seconds before going back up to 2.3-2.4GHz.
- 02f4c26 -- gets worse. It hits the limit, then spends several seconds at 400MHz before eventually getting back up to 2.3-2.4GHz/15W as before.

Please let me know what additional info/logs/trace etc. you need for the respective versions.

**Comment by spandruvada** [comment]
On Mon, 2020-06-01 at 16:39 -0700, James wrote:

With thermald 1.9.1 and the config below, when stressed the processor goes into maximum turbo boost (about 3.5GHz, 35W) from idle for a good 15 seconds of high performance, until it hits 92C and then it drops straight to about 2.4GHz at 15W -- the TDP, whereupon the temperature holds steady.

Adding manually doesn't mean that the platform can support. Even for short time it is allowed eventually it will drop.


<?xml version="1.0"?>

<ThermalConfiguration>

  <Platform>

    <Name>Reduce maximum temperature for safety</Name>

    <ProductName>*</ProductName>

    <Preference>QUIET</Preference>

    <PPCC>

      <PowerLimitIndex>0</PowerLimitIndex>

      <PowerLimitMinimum>3000</PowerLimitMinimum>

      <PowerLimitMaximum>15000</PowerLimitMaximum>

      <TimeWindowMinimum>20000</TimeWindowMinimum>

      <TimeWindowMaximum>30000</TimeWindowMaximum>

      <StepSize>100</StepSize>

    </PPCC>

    <ThermalZones>

      <ThermalZone>

        <Type>cpu</Type>

        <TripPoints>

          <TripPoint>

            <Temperature>92000</Temperature>

            <type>passive</type>

          </TripPoint>

        </TripPoints>

      </ThermalZone>

    </ThermalZones>

  </Platform>

</ThermalConfiguration>

This machine has no DPTF table, and I consider this the optimal behaviour balancing cooling with performance.

With the same config, I see what I consider to be performance regressions traced to the following commits:

  *   eeadf7d<https://github.com/intel/thermal_daemon/commit/eeadf7d2efe557ac57363e75d14ffcf262651dca> -- after hitting the 92C limit, the CPU clock drops down to 1.6GHz for 5-10 seconds before going back up to 2.3-2.4GHz.
  *   02f4c26<https://github.com/intel/thermal_daemon/commit/02f4c26d732c773f4f7340a3a43ffd67a5f37a0c> -- gets worse. It hits the limit, then spends several seconds and 400MHz before eventually getting back up to 2.3-2.4GHz/15W as before.

Please let me know what additional info/logs/trace etc. you need for the respective versions.

Stop the deamon and run via command line and attach logs.

thermald --no-daemon --loglevel=info

**Comment by ettlz** [comment]
I've attached below the thermald info logs from version 1.9.1 and commits eeadf7d and 02f4c26 (with respective names). In each case I ran a stress -c 8 cycle from cool idle until the machine reached its stable loaded warm.

[thermald-1.9.1.log](https://github.com/intel/thermal_daemon/files/4719013/thermald-1.9.1.log)
[thermald-eeadf7d.log](https://github.com/intel/thermal_daemon/files/4719023/thermald-eeadf7d.log)
[thermald-02f4c26.log](https://github.com/intel/thermal_daemon/files/4719020/thermald-02f4c26.log)

I also obtained some temperature-CPU frequency graphs. In the following the minimum CPU core frequency is blue, left y-scale; and package temperature is red, right y-scale. X-axis is in seconds.

1.9.1: Goes straight to long-term stable frequency, about 2.4GHz. Seems reasonable, desired behaviour.
![temp-freq-graph-1 9 1](https://user-images.githubusercontent.com/24683940/83557352-65d57c80-a509-11ea-8ba9-fae28094172b.png)

eeadf7d: Dips to 1.6GHz. Doesn't seem necessary given above.
![temp-freq-graph-eeadf7d](https://user-images.githubusercontent.com/24683940/83557366-6e2db780-a509-11ea-9fa2-74555d635b2e.png)

02f4c26: Dips deep to 400MHz, system becomes noticeably sluggish.
![temp-freq-graph-02f4c26](https://user-images.githubusercontent.com/24683940/83557684-f90eb200-a509-11ea-8ba9-ab94cd74dec2.png)

**Comment by ettlz** [comment]
Dropping to 400MHz looks like something of a panic reaction whenever a 'passive' threshold is hit. I also see it on my Dell with the i5-1035G1, configured using just the PPCC block from dptfxtract, when it hits the 95C default passive trip point. (Although this is rarer on the Dell than the Clevo because on the Dell I can adjust the TCC to below the trip point.)

**Comment by benzea** [comment]
@spandruvada what is your take on this?

> Adding manually doesn't mean that the platform can support. Even for short time it is allowed eventually it will drop.

Sounds to me like you may be implying that the user generated configuration is simply not safe. And as the configuration is not safe, the panic reaction by thermald to drop down to 400MHz is indeed reasonable. Even if one might argue that there is a "regression" when compared to a previous release.

**Comment by spandruvada** [comment]
I am not able to reproduce this on the system which I have. I am looking to optimize this. I will send a branch info, please check if it is fixed.

**Comment by spandruvada** [comment]
Please try the v2.3_development branch.
Checkout
git checkout remotes/origin/v2.3_development -b v2.3_development
and try.

**Comment by drjhe** [comment]
> Please try the v2.3_development branch.
> Checkout
> git checkout remotes/origin/v2.3_development -b v2.3_development
> and try.

I see the same behaviour as 2.2 with the 2.3 branch -- several seconds at 400MHz after the trip point is reached. Let me know if any debug trace is needed.

**Comment by spandruvada** [comment]
If you disable thermald (systemctl disable thermald) and then reboot, what is the output for"
#grep . /sys/class/powercap/intel-rapl/intel-rapl\:0/*

Also you verify before that thermald is not running
#ps -e | grep thermald

**Comment by drjhe** [comment]
Double-checked thermald is not running with ps. Freshly booted on kernel 5.7.8:

```
# grep . /sys/class/powercap/intel-rapl/intel-rapl:0/*
/sys/class/powercap/intel-rapl/intel-rapl:0/constraint_0_max_power_uw:15000000
/sys/class/powercap/intel-rapl/intel-rapl:0/constraint_0_name:long_term
/sys/class/powercap/intel-rapl/intel-rapl:0/constraint_0_power_limit_uw:15000000
/sys/class/powercap/intel-rapl/intel-rapl:0/constraint_0_time_window_us:127926272
/sys/class/powercap/intel-rapl/intel-rapl:0/constraint_1_max_power_uw:0
/sys/class/powercap/intel-rapl/intel-rapl:0/constraint_1_name:short_term
/sys/class/powercap/intel-rapl/intel-rapl:0/constraint_1_power_limit_uw:35000000
/sys/class/powercap/intel-rapl/intel-rapl:0/constraint_1_time_window_us:2440
grep: /sys/class/powercap/intel-rapl/intel-rapl:0/device: Is a directory
/sys/class/powercap/intel-rapl/intel-rapl:0/enabled:1
/sys/class/powercap/intel-rapl/intel-rapl:0/energy_uj:1008940959
grep: /sys/class/powercap/intel-rapl/intel-rapl:0/intel-rapl:0:0: Is a directory
grep: /sys/class/powercap/intel-rapl/intel-rapl:0/intel-rapl:0:1: Is a directory
grep: /sys/class/powercap/intel-rapl/intel-rapl:0/intel-rapl:0:2: Is a directory
/sys/class/powercap/intel-rapl/intel-rapl:0/max_energy_range_uj:262143328850
/sys/class/powercap/intel-rapl/intel-rapl:0/name:package-0
grep: /sys/class/powercap/intel-rapl/intel-rapl:0/power: Is a directory
grep: /sys/class/powercap/intel-rapl/intel-rapl:0/subsystem: Is a directory
```

Additional info: Note that there's no INT3400 on this machine, so I can't manipulate the TCC offset via sysfs (but I can with direct MSR tweaking). Without thermald, under full load the CPU runs at 35W, eventually gets up to 99C, and then starts to throttle hard.

Hope this helps!

**Comment by spandruvada** [comment]
For TCC offset setting don't you see
/sys/devices/pci0000:00/0000:00:04.0/tcc_offset_degree_celsius

For this issue I update the code in the same development branch as before remotes/origin/v2.3_development. This platform's default time window is too big. In your PPCC xml block above set  TimeWindowMaximum  close to TimeWindowMinimum. You are giving 10 second bigger value, so it will take atleast 10 second to recover. For example from the actual table from a DPTF enabled system
power_limit_0_tmax_us:32000000
power_limit_0_tmin_us:28000000

**Comment by drjhe** [comment]
Yeah, the file  /sys/devices/pci0000:00/0000:00:04.0/tcc_offset_degree_celsius doesn't exist on this system. turbostat says:
```
cpu0: MSR_IA32_TEMPERATURE_TARGET: 0x02640000 (100 C)
cpu0: MSR_IA32_PACKAGE_THERM_STATUS: 0x883e0808 (38 C)
cpu0: MSR_IA32_PACKAGE_THERM_INTERRUPT: 0x00000003 (100 C, 100 C)
```

I've adjusted the PPCC section as you suggested:
```
    <PPCC>
      <PowerLimitIndex>0</PowerLimitIndex>
      <PowerLimitMinimum>3000</PowerLimitMinimum>
      <PowerLimitMaximum>15000</PowerLimitMaximum>
      <TimeWindowMinimum>28000</TimeWindowMinimum>
      <TimeWindowMaximum>32000</TimeWindowMaximum>
      <StepSize>125</StepSize>
    </PPCC>
```
and on the 2.3 branch things are now behaving as with 1.9.1: hits the trip point, then down to 15W. Excellent -- thanks!

(Out of curiosity I did try upping the PowerLimitMaximum to 18000 and after the trip point, it dropped to 18W and maintained a steady temperature. Then after abount 2.5 of minutes or so it drops on its own to 15W. I guess this is the hardware taking action independently?)

**Comment by spandruvada** [comment]
We can set the any higher limits, HW will clip it when it can't meet.

**Comment by drjhe** [comment]
For reference - TCC offset is now exposed in sysfs for this chip, and I've switched to setting this to 5 using a udev rule (rather than thermald). Chip seems to manage itself in a manner similar to thermald.
