### ISSUE TITLE
Build failure on x32 with -Werror=format

### ISSUE THREAD

**Issue by jpalus** [intel/thermal_daemon#234]
e79199a added timestamps to logged messages:
```
syslog(syslog_priority, "[%ld]%s%s", seconds, prefix, message);
...
g_print("[%ld]%s%s", seconds, prefix, message);
```
in the way which assumes sizeof(time_t) == sizeof(long). That however is not true on x32 ABI where long is 4 bytes, and long long is 8 bytes.

**Comment by spandruvada** [comment]
On Mon, 2020-06-29 at 10:39 -0700, Jan Palus wrote:

e79199a<https://github.com/intel/thermal_daemon/commit/e79199a38aa2349b5645be9347ff2444ff46bb65> added timestamps to logged messages:

syslog(syslog_priority, "[%ld]%s%s", seconds, prefix, message);


syslog(syslog_priority, "[%ld]%s%s", (long long)seconds, prefix, message);


...

g_print("[%ld]%s%s", seconds, prefix, message);


g_print("[%ld]%s%s", (long long)seconds, prefix, message);


in the way which assumes sizeof(time_t) == sizeof(long). That however is not true on x32 ABI where long is 4 bytes, and long long is 8 bytes.

Can you check with the above changes, you can compile?

**Comment by jpalus** [comment]
I believe format should be updated to %lld then. I made a similar quick fix (%lld + long long) available here: https://github.com/pld-linux/thermal-daemon/blob/master/print-time_t.patch and I can confirm that it builds fine.

**Comment by spandruvada** [comment]
On Mon, 2020-06-29 at 13:31 -0700, Jan Palus wrote:

I believe format should be updated to %lld then. I made a similar quick fix (%lld + long long)

correct.


available here: https://github.com/pld-linux/thermal-daemon/blob/master/print-time_t.patch and I can confirm that it builds fine.

Send me a pull request, I will apply.

Thanks,
Srinivas
