### ISSUE TITLE
Add amdgpu cdev no matter amdgpu name under /sys/class/hwmon/ is exist or not

### ISSUE THREAD

**Issue by KaiChuan-Hsieh** [intel/thermal_daemon#236]
thermald after 1.9 add thd_cdev_kbl_amdgpu.cpp for kbl_amdgpu cooling device support. However, the code logic will add the amdgpu cdev no matter the hwmon with name "amdgpu" is exist or not.

**Comment by spandruvada** [comment]
On Tue, 2020-07-07 at 03:27 -0700, KaiChuan Hsieh wrote:

thermald after 1.9 add thd_cdev_kbl_amdgpu.cpp for kbl_amdgpu cooling device support. However, the code logic will add the amdgpu cdev no matter the hwmon with name "amdgpu" is exist or not.

Will be addressed in the next release.

Thanks

**Comment by spandruvada** [comment]
Fixed.
