### ISSUE TITLE
Make it possible to disable desktop users poking at config

### ISSUE THREAD

**Issue by hadess** [intel/thermal_daemon#243]
Unless I misread `src/thd_dbus_interface.cpp` and `data/org.freedesktop.thermald.conf`, there's currently no way to disable users logged in at the physical console (eg. desktop users) from having access to thermald and poking at it.

For certain configurations, it might be useful to disable this, as the user should not be allowed to change the configuration, because either the administrator (or the OS provider) would already have done the job of setting it up properly.

If that's OK with you, I can create the patch to do that.

**Comment by benzea** [comment]
The busconfig says:
```
<busconfig>

        <policy user="root">
                <allow own="org.freedesktop.thermald"/>
                <allow send_destination="org.freedesktop.thermald"/>
                <allow receive_sender="org.freedesktop.thermald"/>
        </policy>

        <policy context="default">
                <deny send_destination="org.freedesktop.thermald"/>
                <allow receive_sender="org.freedesktop.thermald"/>
        </policy>

        <policy group="power">
                <allow send_destination="org.freedesktop.thermald"/>
                <allow receive_sender="org.freedesktop.thermald"/>
        </policy>

</busconfig>
```

i.e. I believe users are only allowed to access that API if they are in the power group. Probably not the best approach, as most users are unlikely to be added to the group in the first place.

**Comment by hadess** [comment]
Ha! `policy group` not `policy context`. That's fine, I'll add a comment.

**Comment by hadess** [comment]
Changed it to:
```xml
        <!-- Only allow members of the power group to communicate
             with the daemon -->
        <policy context="default">
                <deny send_destination="org.freedesktop.thermald"/>
                <allow receive_sender="org.freedesktop.thermald"/>
        </policy>
        <policy group="power">
                <allow send_destination="org.freedesktop.thermald"/>
                <allow receive_sender="org.freedesktop.thermald"/>
        </policy>
```
in https://github.com/intel/thermal_daemon/pull/242
