### ISSUE TITLE
No generated documentation

### ISSUE THREAD

**Issue by hadess** [intel/thermal_daemon#244]
The code at https://gitlab.freedesktop.org/hadess/iio-sensor-proxy/-/tree/cf1ac31f554d92518d15c0e22c58975e43e03995/docs shows how gtk-doc can be used to generate D-Bus API documentation for D-Bus interfaces.

I'd be happy to provide a patch to add this to the build system, but `src/thd_dbus_interface.xml` would need to be filled in with some documentation. This is an example of what the API docs could look like:
https://gitlab.freedesktop.org/hadess/iio-sensor-proxy/-/blob/cf1ac31f554d92518d15c0e22c58975e43e03995/src/net.hadess.SensorProxy.xml

**Comment by spandruvada** [comment]
Please provide.

**Comment by hadess** [comment]
There would need to be something to generate first, and there's no docs whatsoever in `src/thd_dbus_interface.xml`. There would need to be at least some text, or some details as to what the docs for those functions should be.
