### ISSUE TITLE
uninitialized variable in src/thd_engine_adaptive.cpp

### ISSUE THREAD

**Issue by ColinIanKing** [intel/thermal_daemon#258]
Static analysis has detected an uninitialized variable in src/thd_engine_adaptive.cpp, analysis is as follows:

432 int cthd_engine_adaptive::parse_ppcc(char *name, char *buf, int len) {

   1. var_decl: Declaring variable ppcc.

433        ppcc_t ppcc;
434
435        ppcc.name = name;
436        ppcc.power_limit_min = *(uint64_t*) (buf + 28);
437        ppcc.power_limit_max = *(uint64_t*) (buf + 40);
438        ppcc.time_wind_min = *(uint64_t*) (buf + 52);
439        ppcc.time_wind_max = *(uint64_t*) (buf + 64);
440        ppcc.step_size = *(uint64_t*) (buf + 76);
441

CID 103190 (#1 of 1): 
Uninitialized scalar variable (UNINIT)
  2. uninit_use_in_call: Using uninitialized value ppcc. Field ppcc.valid is uninitialized when calling push_back.

442        ppccs.push_back(ppcc);
443
444        return 0;

**Comment by spandruvada** [comment]
fixed
