### ISSUE TITLE
Request: Please upload the screenshot of thermal monitor.

### ISSUE THREAD

**Issue by tele1** [intel/thermal_daemon#269]
Please upload the screenshot of thermal monitor.
Because:
1. I can not find screenshot.
2. Curiosity eats me :sweat_smile: 
3. I tried compile on VirtualBox with Linux Mint 20 Mate 64 bit,
and I compiled,  but I can not run.

On VirtualBox with Linux Mint 20
I have installed 
```
$ thermald --version
1.9.1
```
And in " thermald --help " I don't see "--simulation" option.
It probably hasn't been invented yet and was not introduced to the project :smile: 

Without simulation I can not run thermald service / deamon

```
$ sudo systemctl status thermald 
● thermald.service - Thermal Daemon Service
     Loaded: loaded (/lib/systemd/system/thermald.service; enabled; vendor preset: enabled)
     Active: inactive (dead) since Tue 2020-09-01 22:30:57 CEST; 27min ago
    Process: 519 ExecStart=/usr/sbin/thermald --no-daemon --dbus-enable (code=exited, status=1/FAILURE)
   Main PID: 519 (code=exited, status=1/FAILURE)

Sep 01 22:30:56 test-VirtualBox thermald[519]: [WARN]sensor id 0 : No temp sysfs for reading raw temp
Sep 01 22:30:56 test-VirtualBox thermald[519]: [WARN]sensor id 0 : No temp sysfs for reading raw temp
Sep 01 22:30:57 test-VirtualBox thermald[519]: [WARN]sysfs open failed
Sep 01 22:30:57 test-VirtualBox thermald[519]: [WARN]sysfs open failed
Sep 01 22:30:57 test-VirtualBox thermald[519]: [ERR]Thermal DTS or hwmon: No Zones present Need to configur>
Sep 01 22:30:57 test-VirtualBox thermald[519]: [ERR]XML zone: invalid sensor type
Sep 01 22:30:57 test-VirtualBox thermald[519]: [WARN]Zone update failed: unable to bind
Sep 01 22:30:57 test-VirtualBox thermald[519]: [ERR]No thermal sensors found
Sep 01 22:30:57 test-VirtualBox systemd[1]: thermald.service: Succeeded.
Sep 01 22:30:57 test-VirtualBox thermald[519]: [ERR]THD engine start failed
```

And I can not run thermal_monitor.
```
$ ./ThermalMonitor --help
qt5ct: using qt5ct plugin
Cannot connect to interface org.freedesktop.thermald
```

> Make sure that thermal daemon started with --dbus-enable option
> and that you're in the 'power' group

```
$ inxi -F
System:    Host: test-VirtualBox Kernel: 5.4.0-42-generic x86_64 bits: 64 Desktop: MATE 1.24.0 
           Distro: Linux Mint 20 Ulyana 
Machine:   Type: Virtualbox System: innotek product: VirtualBox v: 1.2 serial: <superuser/root required> 
           Mobo: Oracle model: VirtualBox v: 1.2 serial: <superuser/root required> BIOS: innotek 
           v: VirtualBox date: 12/01/2006 
...
Sensors:   Message: No sensors data was found. Is sensors configured? 
```

Please note that Virtualbox does not have virtual sensors.

**Comment by spandruvada** [comment]
On virtual box the host will thermal control. So thermald will not be able to access any sensors.

**Comment by tele1** [comment]
**spandruvada** if I'm not mistaken.

 **Host** this is system where VirtualBox is installed.
So host it could be a system installed 
- on a real hardware  ( Virtualbox is usually installed there )
- or on a virtual machine. For example on VirtualBox.
( installing a virtual machine in a virtual machine is possible, but rarely makes sense )

**Guest** It's system on  virtual machine system.

I know that a virtual machine does not need sensors. Because is virtual.
But I want only see how looks thermal_monitor.
I didn't want to test it on a real machine because I don't like installing and then removing a lot of packages.
I can write a script to remove packages or use Timeshift to backup and restore a Linux system.
But for me use VirtualBox was faster.
