### ISSUE TITLE
Possible unstable thermal regulation on old MacBook (2011)

### ISSUE THREAD

**Issue by benzea** [intel/thermal_daemon#271]
I have had a report (https://bugzilla.redhat.com/show_bug.cgi?id=1877438) where there is a lot of idle injection at times. The user is also suggesting that the fans on the machine are not spinning at full speed at times (it was building chromium at the time).

Looking at the log, the behaviour from thermald appears relatively sane overall. It does seem to be a bit unstable though. In the sense that it only gets a 1°C accurate temperature reading and updating once a second is resulting in quite a lot of changes to the cooling devices.

Srinivas, could you check if you see anything suspicious here?

**Comment by spandruvada** [comment]
I merged change from benzea.
