### ISSUE TITLE
PID unique to trip point seems to be incorrect

### ISSUE THREAD

**Issue by benzea** [intel/thermal_daemon#272]
I read the code a bit, and stumbled across this:

```
		// Handle PID param unique to a trip
		pid.set_target_temp(target_temp);
		ret = pid.pid_output(temperature);
		ret += get_curr_state(true);
...
		// Handle PID param common to whole cooling device
		pid_ctrl.set_target_temp(target_temp);
		ret = pid_ctrl.pid_output(temperature);
		ret += get_min_state();
```

This was changed in commit e31f67e50272b75bfed1dc35be10e4bff42df69a. But using the current state (which is then updated) results in an integration over the PID regulator output.

I am not sure whether this really is incorrect or how big the impact would be. But intuitively, this looks really wrong to me from a theoretical point of view.

**Comment by benzea** [comment]
Thinking about it, maybe what is needed here is a special PID reset/startup that initialises the integrative component to a value resulting in the current state to be calculated (if the temperature was exactly at the target temperature).

**Comment by spandruvada** [comment]
Only way to use PID currently  if someone using XML file to configure.
None of the auto config or adaptive opti choose PID.
We had couple or earlier discussions  on this. So open to improve. If we don't do from current state then swings are too big on setting next performance.

**Comment by spandruvada** [comment]
Only way to use PID currently  if someone using XML file to configure.
None of the auto config or adaptive opti choose PID.
We had couple or earlier discussions  on this. So open to improve. If we don't do from current state then swings are too big on setting next performance.

**Comment by benzea** [comment]
In that case, I am in favour of adding a small comment that it is probably broken and just ignoring it otherwise ;)

**Comment by benzea** [comment]
OK, submitted a patch, which I believe is actually the proper fix here.
