### ISSUE TITLE
Comet Lake CPUID levels; family:model:stepping 0x6:a5:2 (6:165:2) is not included

### ISSUE THREAD

**Issue by KaiChuan-Hsieh** [intel/thermal_daemon#275]
I check the id_table, the CPUID is not included. Does it mean that thermald can't support the CPU?

Here is the journalctl log when using Ubuntu 20.04.
Sep 15 17:07:00 ubuntu systemd[1]: Starting Thermal Daemon Service...
Sep 15 17:07:00 ubuntu systemd[1]: Started Thermal Daemon Service.
Sep 15 17:07:00 ubuntu thermald[1089]: [WARN]22 CPUID levels; family:model:stepping 0x6:a5:2 (6:165:2)
Sep 15 17:07:00 ubuntu thermald[1089]: [WARN] Need Linux PowerCap sysfs
Sep 15 17:07:00 ubuntu thermald[1089]: I/O warning : failed to load external entity "/etc/thermald/thermal-conf.xml"
Sep 15 17:07:00 ubuntu thermald[1089]: [WARN]error: could not parse file /etc/thermald/thermal-conf.xml
Sep 15 17:07:00 ubuntu thermald[1089]: [WARN]Unsupported cpu model, use thermal-conf.xml file or run with --ignore-cpuid-check
Sep 15 17:07:00 ubuntu thermald[1089]: [ERR]THD engine start failed
Sep 15 17:07:00 ubuntu systemd[1]: thermald.service: Succeeded.

**Comment by spandruvada** [comment]
Is it a desktop or laptop system? Seems desktop CPU model.

Thanks.

On Thu, 2020-09-17 at 03:08 -0700, KaiChuan Hsieh wrote:

I check the id_table, the CPUID is not included. Does it mean that thermald can't support the CPU?

Here is the journalctl log when using Ubuntu 20.04.
Sep 15 17:07:00 ubuntu systemd[1]: Starting Thermal Daemon Service...
Sep 15 17:07:00 ubuntu systemd[1]: Started Thermal Daemon Service.
Sep 15 17:07:00 ubuntu thermald[1089]: [WARN]22 CPUID levels; family:model:stepping 0x6:a5:2 (6:165:2)
Sep 15 17:07:00 ubuntu thermald[1089]: [WARN] Need Linux PowerCap sysfs
Sep 15 17:07:00 ubuntu thermald[1089]: I/O warning : failed to load external entity "/etc/thermald/thermal-conf.xml"
Sep 15 17:07:00 ubuntu thermald[1089]: [WARN]error: could not parse file /etc/thermald/thermal-conf.xml
Sep 15 17:07:00 ubuntu thermald[1089]: [WARN]Unsupported cpu model, use thermal-conf.xml file or run with --ignore-cpuid-check
Sep 15 17:07:00 ubuntu thermald[1089]: [ERR]THD engine start failed
Sep 15 17:07:00 ubuntu systemd[1]: thermald.service: Succeeded.

**Comment by KaiChuan-Hsieh** [comment]
It is a laptop.

Thanks,

**Comment by spandruvada** [comment]
I will push a change this week to add this CPU model.

On Thu, 2020-09-17 at 10:06 -0700, KaiChuan Hsieh wrote:

It is a laptop.

Thanks,

**Comment by spandruvada** [comment]
Added CPU models and pushed to repo.
Thanks for notifying.


On Thu, 2020-09-17 at 10:06 -0700, KaiChuan Hsieh wrote:

It is a laptop.

Thanks,

**Comment by KaiChuan-Hsieh** [comment]
Thanks for your support.
