### ISSUE TITLE
"Unsupported CPU model" leads to failure status

### ISSUE THREAD

**Issue by mcatanzaro** [intel/thermal_daemon#276]
Hi, I notice that my `systemctl status` is in `State: degraded` when I expect no errors. It's caused by thermald:

```
Sep 29 07:45:02 chargestone-cave thermald[2211]: Config file /etc/thermald/thermal-conf.xml does not exist
Sep 29 07:45:02 chargestone-cave thermald[2211]: Unsupported cpu model, use thermal-conf.xml file or run with --ignore-cpuid-check
Sep 29 07:45:02 chargestone-cave thermald[2211]: THD engine start failed
```

Since thermald is now being shipped by default in Fedora, it's going to be running on arbitrary systems where it's now expected that the CPU may not be supported. This is not a misconfiguration, so it should exit with a success code instead.

CC @benzea

**Comment by benzea** [comment]
Actually, just looked at it, and it shouldn't be the reason for your degraded state. Error exit code 1 is not considered a failure for thermald.

Though, it would still good to change this as other error cases also result in exit code 1 and we should probably go into the failed state then.

**Comment by mcatanzaro** [comment]
Full output of `systemctl status thermald`:

```
● thermald.service - Thermal Daemon Service
     Loaded: loaded (/usr/lib/systemd/system/thermald.service; enabled; vendor preset: enabled)
     Active: inactive (dead) since Thu 2020-10-01 06:28:24 CDT; 11min ago
    Process: 1488 ExecStart=/usr/sbin/thermald --systemd --dbus-enable --adaptive (code=exited, status=1/FAILURE)
   Main PID: 1488 (code=exited, status=1/FAILURE)
        CPU: 9ms

Oct 01 06:28:24 chargestone-cave systemd[1]: Starting Thermal Daemon Service...
Oct 01 06:28:24 chargestone-cave thermald[1488]: NO RAPL sysfs present
Oct 01 06:28:24 chargestone-cave thermald[1488]: NO RAPL sysfs present
Oct 01 06:28:24 chargestone-cave thermald[1488]: Config file /etc/thermald/thermal-conf.xml does not exist
Oct 01 06:28:24 chargestone-cave thermald[1488]: Unsupported cpu model, use thermal-conf.xml file or run with --ignor>
Oct 01 06:28:24 chargestone-cave thermald[1488]: THD engine start failed
Oct 01 06:28:24 chargestone-cave systemd[1]: thermald.service: Succeeded.
Oct 01 06:28:24 chargestone-cave systemd[1]: Started Thermal Daemon Service.
```

In particular, note: `(code=exited, status=1/FAILURE)`.

BTW, I notice now that it prints "succeeded" and "started" when it is failed and inactive. That's strange.

**Comment by benzea** [comment]
Yeah, I think that is just systemd being a bit stupid in its status= printing there.

The relevant bit is `Active: inactive (dead)` rather than `Active: failed (Result: ...)`.

**Comment by benzea** [comment]
That mapping to "FAILURE" seems to always happen for exit code 1. I changed it now to return 2 for "should not run", which actually also means that it doesn't show anything like that anymore.

See #277

**Comment by benzea** [comment]
I believe this bug can be closed.
