### ISSUE TITLE
Possibility to release Power Limit Throttling HP Spectre x360 (Late 2019) i7-1065G7 on Windows Subsystem for Linux??

### ISSUE THREAD

**Issue by brybalicious** [intel/thermal_daemon#279]
Hello,

Just found this intriguing project while seeking alternatives to being locked down via DPTF with a 15W TDP Limit. I am wondering whether it's possible to use this tool with Windows Subsystem for Linux, and if there is a walkthrough or guide of some sort somewhere?

Cheers. Great work..

**Comment by spandruvada** [comment]
Don't understand "Windows subsystem for Linux". Are you running Linux or Windows in this laptop?
For Linux this tool should be build in for most distros. But you can follow "README" and build yours.
There are some kernel changes required for fully support some HP models.
Refer to https://github.com/intel/thermal_daemon/issues/266

**Comment by brybalicious** [comment]
Ah... I'm running Windows 10, but with WSL2 enabled.

https://docs.microsoft.com/en-us/windows/wsl/compare-versions

Does this help? The kernel is exposed...

**Comment by joel-sampson** [comment]
I've got the same model but i'm running fedora not windows or wsl. The Thermal Monitor tool starts up blank, without detecting any sensors. It seems the auto config files are auto created successfully. dnf has supplied me with latest 2.3 version and i'm running kernel 5.8.18-300. systemd logs attached [thermald.txt](https://github.com/intel/thermal_daemon/files/5557384/thermald.txt).

**Comment by joel-sampson** [comment]
Cheers guys latest version fixed it for me
