### ISSUE TITLE
22 CPUID levels; family:model:stepping 0x6:a6:0 (6:166:0)

### ISSUE THREAD

**Issue by HayeQuarrie** [intel/thermal_daemon#281]
CPU: Intel Core i7-10710U @ 12x 1.1GHz [46.0°C]
Kernel: x86_64 Linux 5.9.8-arch1-1

`Nov 15 10:44:09 itachi thermald[12674]: Unable to find a sensor for \_SB_.PCI0.LPCB.H_EC.SEN1
Nov 15 10:44:09 itachi thermald[12674]: 22 CPUID levels; family:model:stepping 0x6:a6:0 (6:166:0)
Nov 15 10:44:09 itachi thermald[12674]:  Need Linux PowerCap sysfs
Nov 15 10:44:09 itachi thermald[12674]: Unsupported cpu model, use thermal-conf.xml file or run with ->
Nov 15 10:44:09 itachi thermald[12674]: 22 CPUID levels; family:model:stepping 0x6:a6:0 (6:166:0)
Nov 15 10:44:09 itachi thermald[12674]:  Need Linux PowerCap sysfs
Nov 15 10:44:09 itachi thermald[12674]: Config file /etc/thermald/thermal-conf.xml does not exist
Nov 15 10:44:09 itachi thermald[12674]: Unsupported cpu model, use thermal-conf.xml file or run with ->
Nov 15 10:44:09 itachi thermald[12674]: THD engine start failed
Nov 15 10:44:09 itachi systemd[1]: thermald.service: Succeeded.
`
It's a laptop

**Comment by spandruvada** [comment]
This CPU is supported in the master branch. There is no release made with this yet.
But you can build from the source here.

**Comment by HayeQuarrie** [comment]
thank you.
