### ISSUE TITLE
Use the configuration file when started as systemd unit

### ISSUE THREAD

**Issue by ro-i** [intel/thermal_daemon#283]
Hi! :slightly_smiling_face: 
When `thermald` is started by its systemd unit, the configuration file `/etc/thermald/thermal-conf.xml` is not taken into account. Editing the unit file and removing the `--adaptive` flag enables the configuration file. Maybe you want to add some documentation for this behavior?

system: Fedora 33; `thermald` version: 2.3

**Comment by spandruvada** [comment]
I will add to the man page.

Thanks,
Srinivas

On Sat, 2020-11-21 at 04:39 -0800, Robert Imschweiler wrote:

Hi! 🙂
When thermald is started by its systemd unit, the configuration file /etc/thermald/thermal-conf.xml is not taken into account. Editing the unit file and removing the --adaptive flag enables the configuration file. Maybe you want to add some documentation for this behavior?

system: Fedora 33; thermald version: 2.3

**Comment by spandruvada** [comment]
Added to the man page in the release 2.4.
