### ISSUE TITLE
Missing /etc/thermald/thermal-conf.xml file

### ISSUE THREAD

**Issue by andrfgs** [intel/thermal_daemon#289]
Hello, I am trying to use thermald on my Arch Linux setup but there's no `thermal-conf.xml`. I haven't found info on how this file is supposed to be generated, I only found documentation about its structure, which doesn't really help in my case.

Is there any reason thermald won't generate the file if its not there? How am I supposed to get the file? Do I create it by hand? The service is running perfectly, but there's no file present. Am I missing something?

Some specs of my system which might help:
Computer: MSI GP73 Leopard 8RF (Laptop)
CPU: i7-8750H CPU @ 2.20GHz
Kernel: 5.10.3-arch1-1

**Comment by spandruvada** [comment]
Thermald will be generate config file, if there is information in BIOS-ACPI to create. If you are using –adaptive option then it will not generate config file but it reads some special tables and acts.
So you should run with loglevel=info and see what mode it is running.

man thermal-conf.xml
will give some example if you want to configure manually if you are having certain thermal issues.

**Comment by andrfgs** [comment]
Thank you for the reply. I must admit I am quite clueless how the whole process works. The thermal issue is due to the laptop itself, but I was hoping thermald could help minimize the issue a bit.

Whenever I am playing heavy games, especially under Steam Proton, the temperatures of both the CPU and GPU hit 90C and the CPU might fluctuate from 90C to 95C which seems very serious. The MSI has a button controlled fan for turbo cooling, which is on during these high temperatures, but doesn't seem enough. The fans of the laptop are not detected by `lm-sensors`.

I read on the manfile that I am supposed to run `dptfxtract` but the program returns:
```
DPTF Tables Extraction Utility 
Copyright (c) 2000 - 2020 Intel Corporation


No valid tables found 
```

So I don't even know If `thermald` can help me in this case.

**Comment by spandruvada** [comment]
You can lower the threshold temperature using example 1, in thermal_conf.xml man page.
But it may lower your game performance.

If MSI has some fan control sysfs, then you can use for fan control as described in example 3.
But first you need to find out if MSI allows to control fan from Linux sysfs (There has to be some driver in Linux).

**Comment by alkisg** [comment]
In Ubuntu 20.04, thermald runs from systemd as:

```shell
/usr/sbin/thermald --systemd --dbus-enable --adaptive
```

As you mentioned above, in this mode, /etc/thermald/thermal-conf.xml isn't generated. But in `journalctl -b -pwarning`, I see a lot of:

```syslog
Mar 08 17:06:26 gltsp0b thermald[2865]: error: could not parse file /etc/thermald/thermal-conf.xml
```

In order to keep logs cleaner, would it be possible to omit logging that warning when thermald is started with `--adaptive`? Or at least lower its log priority, so that sysadmins aren't alerted about it... Thank you!

**Comment by xorinzor** [comment]
> Is there any reason thermald won't generate the file if its not there? How am I supposed to get the file? Do I create it by hand? The service is running perfectly, but there's no file present. Am I missing something?

For others who might find this, in order to auto-generate a new config file you need to run `dptfxtract`.
It also says in `man thermald` that that's the way to do it.

**Comment by saxofon** [comment]
> > Is there any reason thermald won't generate the file if its not there? How am I supposed to get the file? Do I create it by hand? The service is running perfectly, but there's no file present. Am I missing something?
> 
> For others who might find this, in order to auto-generate a new config file you need to run `dptfxtract`. It also says in `man thermald` that that's the way to do it.

seems like wrong path to go beacuse

1. repo is containing a prebuilt binary, thus no possibility to verify what it actually do
2. repo is discontinued and not supported since years back
