### ISSUE TITLE
Lenovo C940: SEN4 overheating / throttled down to 400MHz

### ISSUE THREAD

**Issue by torotil** [intel/thermal_daemon#294]
Without a `thermal-conf.xml` my Laptop (Lenovo C940) frequently shuts down due to high temperature (SEN4 reaching the critical temperature of 80°C).  [thermald-no-config.log](https://github.com/intel/thermal_daemon/files/6154350/thermald-no-config.log) (The log stops after I’ve manually throttled the CPU using `cpupower`)

That’s why I’ve used `dptfxtract` to generate a [`thermal-conf.xml`](https://gist.githubusercontent.com/torotil/2c29dd536d62df70952fef725d94f82f/raw/55e851bcb85c835d163fd78884fedf0229e5f1c9/thermal-conf-sen2-60c.xml.txt).
With this config rapl_controller_mmio is used because SEN2 surpasses 60°C. This leads to the system firing away at >3GHz (3.9GHz is the CPUs max speed) then slowly declining to ~2.5GHz and then finally dropping to 400MHz for a few seconds. [thermald.log](https://gist.githubusercontent.com/torotil/2c29dd536d62df70952fef725d94f82f/raw/55e851bcb85c835d163fd78884fedf0229e5f1c9/thermald-sen2-60c.log)

![CPU frequency with config](https://gist.githubusercontent.com/torotil/2c29dd536d62df70952fef725d94f82f/raw/55e851bcb85c835d163fd78884fedf0229e5f1c9/cpu-freq-sen2-60c.png)

This is somewhat successful in keeping SEN4 below 80°C (thermal shutdowns occur only rarely), but the Laptop is becoming mostly useless whenever it’s throttled to 400Mhz.

When I use `cpupower` to limit the CPU to 2GHz SEN2 keeps at ~57°C and SEN4 at ~69°C. So throttling to 400MHz seems a bit excessive.

I’ve read the [manpage for the thermal-conf.xml](http://manpages.ubuntu.com/manpages/trusty/en/man5/thermal-conf.xml.5.html) but I’m non the wiser how I could fine-tune things.

Any suggestions on what I could try?

----

- Kernel: 5.10.17-gentoo-x86_64
- CPU: i7-1065G7 @ 1.30GHz
- thermald 2.4.1

**Comment by torotil** [comment]
I seem to be unable to attach more than 2 files. Will upload them to a gist.

**Comment by torotil** [comment]
I can see no improvement after upgrading to kernel 5.10.23 and thermald 2.4.3.

**Comment by spandruvada** [comment]
[thermal_conf_xml.txt](https://github.com/intel/thermal_daemon/files/7856350/thermal_conf_xml.txt)

**Comment by spandruvada** [comment]
Try something like above, where you are limiting power based on temperature. For example in the above config, when SEN2 reaches 50 power is reduced to 20W, at 55C use 15W and so on.
You can tune instead of reaching 60C.

**Comment by torotil** [comment]
Thanks! I will try that (and possibly tweak it a bit). I plan to report back here when I have tested it enough.
