### ISSUE TITLE
Node eporter Container logs

### ISSUE THREAD

**Issue by TheInfamousToTo** [intel/thermal_daemon#296]
hey all , im not sure if im publishing this issue on the current place or not as its my first time using GitHub

I installed node exporter container on prtainer on openmediavault on my inter i5-6600k machine and im getting this error 

level=error ts=2021-03-26T20:40:54.822Z caller=collector.go:161 msg="collector failed" name=rapl duration_seconds=0.000386188 err="open /sys/class/powercap/intel-rapl:0:2/energy_uj: permission denied",
level=error ts=2021-03-26T20:41:04.820Z caller=collector.go:161 msg="collector failed" name=rapl duration_seconds=0.001130972 err="open /sys/class/powercap/intel-rapl:0:2/energy_uj: permission denied",
level=error ts=2021-03-26T20:40:59.826Z caller=collector.go:161 msg="collector failed" name=rapl duration_seconds=0.000314106 err="open /sys/class/powercap/intel-rapl:0:2/energy_uj: permission denied",
level=error ts=2021-03-26T20:40:49.823Z caller=collector.go:161 msg="collector failed" name=rapl duration_seconds=0.000224105 err="open /sys/class/powercap/intel-rapl:0:2/energy_uj: permission denied"

im not sure whats the issue but im able to collect data from node exporter on Grafana

note: im new on linux

**Comment by nathanaelries** [comment]
I can confirm I also have this issue. 

Here are the steps to perform a workaround to disable intel rapl collection https://github.com/prometheus/node_exporter/issues/1892#issuecomment-751815783

```Console
sudo nano /etc/systemd/system/node_exporter.service`
```

add the command line switch to the `ExecStart=/usr/local/bin/node_exporter`

`ExecStart=/usr/local/bin/node_exporter --no-collector.rapl`

save and close the file

reload the daemons

```Console
sudo systemctl daemon-reload
```

restart nod_exporter

```Console
sudo systemctl restart node_exporter.service
```

**Comment by spandruvada** [comment]
Sorry this is thermald forum, so may not be able to help.
