### ISSUE TITLE
AMD Ryzen 7 3750H not supported yet?

### ISSUE THREAD

**Issue by juggao** [intel/thermal_daemon#297]
Can not get thermald.service to run on a Ryzen 7 3750H. Unfortunately I do not have the information to make a thermal-conf.xml for this cpu. I have to rely that the BIOS cools my cpu properly, and it does. (Mostly below 60 C)

● thermald.service - Thermal Daemon Service
     Loaded: loaded (/lib/systemd/system/thermald.service; enabled; vendor preset: enabled)
     Active: inactive (dead) since Fri 2021-04-02 05:29:57 CEST; 7s ago
    Process: 15420 ExecStart=//sbin/thermald --no-daemon --dbus-enable (code=exited, status=1/FAILURE)
   Main PID: 15420 (code=exited, status=1/FAILURE)

apr 02 05:29:57 UM700 systemd[1]: Starting Thermal Daemon Service...
apr 02 05:29:57 UM700 systemd[1]: Started Thermal Daemon Service.
apr 02 05:29:57 UM700 thermald[15420]: I/O warning : failed to load external entity "/etc/thermald/th>
apr 02 05:29:57 UM700 thermald[15420]: [1617334197][WARN]error: could not parse file //etc/thermald/t>
apr 02 05:29:57 UM700 thermald[15420]: [1617334197][WARN]Unsupported cpu model, use thermal-conf.xml >
apr 02 05:29:57 UM700 thermald[15420]: [1617334197][ERR]THD engine start failed
apr 02 05:29:57 UM700 systemd[1]: thermald.service: Succeeded.

**Comment by juggao** [comment]
reinold@UM700:/etc/thermald$ cat /proc/cpuinfo 
processor	: 0
vendor_id	: AuthenticAMD
cpu family	: 23
model		: 24
model name	: AMD Ryzen 7 3750H with Radeon Vega Mobile Gfx
stepping	: 1
microcode	: 0x8108102
cpu MHz		: 1400.000
cache size	: 512 KB
physical id	: 0
siblings	: 8
core id		: 0
cpu cores	: 4
apicid		: 0
initial apicid	: 0
fpu		: yes
fpu_exception	: yes
cpuid level	: 13
wp		: yes
flags		: fpu vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pat pse36 clflush mmx fxsr sse sse2 ht syscall nx mmxext fxsr_opt pdpe1gb rdtscp lm constant_tsc rep_good nopl nonstop_tsc cpuid extd_apicid aperfmperf pni pclmulqdq monitor ssse3 fma cx16 sse4_1 sse4_2 movbe popcnt aes xsave avx f16c rdrand lahf_lm cmp_legacy svm extapic cr8_legacy abm sse4a misalignsse 3dnowprefetch osvw skinit wdt tce topoext perfctr_core perfctr_nb bpext perfctr_llc mwaitx cpb hw_pstate ssbd ibpb vmmcall fsgsbase bmi1 avx2 smep bmi2 rdseed adx smap clflushopt sha_ni xsaveopt xsavec xgetbv1 xsaves clzero irperf xsaveerptr arat npt lbrv svm_lock nrip_save tsc_scale vmcb_clean flushbyasid decodeassists pausefilter pfthreshold avic v_vmsave_vmload vgif overflow_recov succor smca sme sev sev_es
bugs		: sysret_ss_attrs null_seg spectre_v1 spectre_v2 spec_store_bypass
bogomips	: 4591.01
TLB size	: 2560 4K pages
clflush size	: 64
cache_alignment	: 64
address sizes	: 43 bits physical, 48 bits virtual
power management: ts ttp tm hwpstate eff_freq_ro [13] [14]

**Comment by spandruvada** [comment]
This needs to be pushed from AMD, currently there is no interest.
