### ISSUE TITLE
--adaptive fallback when no DPTF tables are present

### ISSUE THREAD

**Issue by kjssad** [intel/thermal_daemon#298]
thermald: 2.4.1
kernel: 5.11.11
processor: Intel® Celeron(R) CPU N3450 @ 1.10GHz × 4

Hello. Fedora's default `thermald` service runs with `--adaptive` option. It seems to prevent any optimizations. I'm under the assumption that if there isn't any DPTF adaptive tables it will fall back to the default behavior (as was mentioned on the changelog). Thermald does works without `--adaptive` option both with a config file and without one. I must admit that I don't get how the process works.

As an anecdote, `thermald`(v 1.9.1) on Ubuntu 20.04 locks powerclamp(>-1) and frequency(800MHz) when optimizations kicks in, not ticking back to its original values until a restart.

This is the [log](https://github.com/intel/thermal_daemon/files/6247897/adaptive.txt) for `thermald --no-daemon --loglevel=info --adaptive`

**Comment by benzea** [comment]
So, it looks to me like what is happening here is that we are running in adaptive mode, but only with the passive rules being applied.

i.e.:
```
[INFO]Name :IETM.D0
[INFO]	source:\_SB_.PCI0.TCPU target:\_SB_.PCI0.TCPU priority:10 sample_period:200 temp:93 domain:9 control_knob:65536 psv.limit:Max
[INFO]	source:\_SB_.PCI0.TCPU target:\_SB_.GEN1 priority:10 sample_period:200 temp:63 domain:9 control_knob:65536 psv.limit:Max
```
So, as I read it, this means that the CPU should be kept below `93°C` and `GEN1` (whatever that is) below `63°C`.

It would probably be interesting to have a log of `thermald` actually running for a longer time and throttling the system. You can also grab both a log with `--adaptive` and without it.

**Comment by spandruvada** [comment]
Without adaptive option you will have only one sensor (TCPU) you have option GEN1. It is picking up the default table.
As suggested better to share logs with --adaptive and non --adaptive option.
Please reopen if required as this thread is old and no response.
