### ISSUE TITLE
thermald effects NVIDIA GPU throttling

### ISSUE THREAD

**Issue by jolars** [intel/thermal_daemon#300]
I am not quite sure what is going on here, but apparently thermald is affecting throttling behavior on my NVIDIA Geforce MX330 card on my Lenovo Thinkpad T14 Gen 1. I've posted about this on [the NVIDIA forum](https://forums.developer.nvidia.com/t/severe-throttling-on-thinkpad-t14-gen-1-with-geforce-mx330/177366) and [RPM fusion bugzilla](https://bugzilla.rpmfusion.org/show_bug.cgi?id=5994) previously. 

Basically, I am seeing throttling on my NVIDIA GPU that seems to occur because the `GPU Max Operating Temp` setting in the nvidia driver is set too low:

```shell
nvidia-smi -q -d TEMPERATURE

==============NVSMI LOG==============

Timestamp                                 : Sat May  8 13:25:04 2021
Driver Version                            : 465.27
CUDA Version                              : 11.3

Attached GPUs                             : 1
GPU 00000000:2D:00.0
    Temperature
        GPU Current Temp                  : 56 C
        GPU Shutdown Temp                 : 102 C
        GPU Slowdown Temp                 : 97 C
        GPU Max Operating Temp            : 57 C
        GPU Target Temperature            : N/A
        Memory Current Temp               : N/A
        Memory Max Operating Temp         : N/A
```

When I install and enable thermald (2.4.4), running with the `--adaptive` option, however, I suddenly see:

```
==============NVSMI LOG==============

Timestamp                                 : Sat May  8 13:29:56 2021
Driver Version                            : 465.27
CUDA Version                              : 11.3

Attached GPUs                             : 1
GPU 00000000:2D:00.0
    Temperature
        GPU Current Temp                  : 56 C
        GPU Shutdown Temp                 : 102 C
        GPU Slowdown Temp                 : 97 C
        GPU Max Operating Temp            : 75 C
        GPU Target Temperature            : N/A
        Memory Current Temp               : N/A
        Memory Max Operating Temp         : N/A
```

and therefore much less throttling.

It seems weird to me that thermald is somehow affecting the throttling behavior of the NVIDIA card and I am wondering if anyone might possibly help me figure out what's going on here? My guess is that thermald is somehow controlling some type of system setting that the NVIDIA driver responds to, but I have too little insight into the workings of thermald (or power management in general) to figure out what that might be. I am on Fedora 34.

I realize that this is likely a bug in the nvidia driver and that this is not an issue for your software per se, but I would very much appreciate any insight anyone could offer.

**Comment by spandruvada** [comment]
thermald has no control points for Nvidia GPU. It probably increased the power limits with adaptive which somehow affecting this.
