### ISSUE TITLE
Unsupported family:model:stepping 6:97:1

### ISSUE THREAD

**Issue by KaiChuan-Hsieh** [intel/thermal_daemon#301]
Boot Ubuntu 20.04 with kernel 5.13 on a Dell platform, got thermald starts failed.

thermald[1266]: 32 CPUID levels; family:model:stepping 0x6:97:1 (6:151:1)
thermald[1266]:  Need Linux PowerCap sysfs
thermald[1266]: Unsupported cpu model or platform

**Comment by KaiChuan-Hsieh** [comment]
@spandruvada 

Hello,
Could you help to confirm if thermald should work on ADL-S?

Thanks,

**Comment by spandruvada** [comment]
Not yet.

Thanks.

On Sun, 2021-05-30 at 18:26 -0700, KaiChuan Hsieh wrote:

@spandruvada<https://github.com/spandruvada>

Hello,
Could you help to confirm if thermald should work on ADL-S?

Thanks,

**Comment by spandruvada** [comment]
Please checkout branch:
adl_support

And provide the logs with
thermald --no-daemon --loglevel=info --adaptive

**Comment by KaiChuan-Hsieh** [comment]
@spandruvada 

please check the log 
[thermald.log](https://github.com/intel/thermal_daemon/files/6690945/thermald.log)

**Comment by spandruvada** [comment]
I still see unsupported CPU model. Did you build from the branch?

**Comment by KaiChuan-Hsieh** [comment]
No, check the time after 12:13:35, I didn't reboot the device, I just restart it. The journalctl -u thermald will output all info.

六  22 12:13:35 u-Dolphin-N systemd[1]: Starting Thermal Daemon Service...
 六  22 12:13:35 u-Dolphin-N systemd[1]: Started Thermal Daemon Service.
 六  22 12:13:35 u-Dolphin-N thermald[26586]: RAPL domain count 0
 六  22 12:13:35 u-Dolphin-N thermald[26586]: RAPL domain count 1
 六  22 12:13:35 u-Dolphin-N thermald[26586]: 32 CPUID levels; family:model:stepping 0x6:97:1 (6:151:1)
 六  22 12:13:35 u-Dolphin-N thermald[26586]: THD engine start failed
 六  22 12:13:35 u-Dolphin-N thermald[26586]: --adaptive option failed on this platform
 六  22 12:13:35 u-Dolphin-N thermald[26586]: Ignoring --adaptive option
 六  22 12:13:35 u-Dolphin-N thermald[26586]: RAPL domain count 0
 六  22 12:13:35 u-Dolphin-N thermald[26586]: RAPL domain count 1
 六  22 12:13:35 u-Dolphin-N thermald[26586]: 32 CPUID levels; family:model:stepping 0x6:97:1 (6:151:1)
 六  22 12:13:35 u-Dolphin-N thermald[26586]: Running on a vanilla kernel
 六  22 12:13:35 u-Dolphin-N thermald[26586]: Polling mode is enabled: 4
 六  22 12:13:35 u-Dolphin-N thermald[26586]: sensor_update: type x86_pkg_temp
 六  22 12:13:35 u-Dolphin-N thermald[26586]: sensor_update: type INT3400
 六  22 12:13:35 u-Dolphin-N thermald[26586]: sensor_update: type TCPU
 六  22 12:13:35 u-Dolphin-N thermald[26586]: thd_read_default_thermal_sensors loaded 3 sensors

**Comment by spandruvada** [comment]
I have pushed one more change. Please try again. Instead of loglevel=info, try with loglevel=debug
Do you see
ls -l /sys/bus/platform/devices/INTC1046:00/
ls -l /sys/bus/platform/devices/INTC1046:00/firmware_node/path

**Comment by KaiChuan-Hsieh** [comment]
@spandruvada 

I don't have INTC1046 device on my system. 
[ls-sys-bus-platform-devices.log](https://github.com/intel/thermal_daemon/files/6698293/ls-sys-bus-platform-devices.log)

My system is from ODM, will check Intel reference board (RVP or SDP) to see if it has.

**Comment by spandruvada** [comment]
Sorry, I made mistake. This should be INTC1041. I pushed change again.
I already see in platform devices INTC1041.

**Comment by KaiChuan-Hsieh** [comment]
Hello @spandruvada 

here is the log of the final commit of adl_support. 
[journalctl-u-thermald.log](https://github.com/intel/thermal_daemon/files/6706691/journalctl-u-thermald.log)

Please check the time after:
 六  24 14:05:57 u-Dolphin-N thermald[6858]: Sensor TCPU :temp 50
 六  24 14:05:57 u-Dolphin-N thermald[6858]: pref 0 type 4 temp 50 trip 103050
 六  24 14:05:57 u-Dolphin-N thermald[6858]: pref 0 type 4 temp 50 trip 104550
 六  24 14:05:57 u-Dolphin-N thermald[6858]: pref 0 type 4 temp 50 trip 106050
 六  24 14:05:57 u-Dolphin-N thermald[6858]: pref 0 type 4 temp 50 trip 107050
 六  24 14:05:57 u-Dolphin-N thermald[6858]: pref 0 type 4 temp 50 trip 109050
 六  24 14:05:57 u-Dolphin-N thermald[6858]: pref 0 type 0 temp 50 trip 110050
 六  24 14:05:57 u-Dolphin-N thermald[6858]: pref 0 type 2 temp 50 trip 110050

**Comment by spandruvada** [comment]
This has AMBF, TMEM,HTPP,TSKN,CHRG. Their temperature limit is 99C, which seems to dummy.
ls /sys/class/thermal/thermal_zone*/type
Do you have these sensors?
You can send me acpidump.

**Comment by KaiChuan-Hsieh** [comment]
@spandruvada 

The system I used in https://github.com/intel/thermal_daemon/issues/301#issuecomment-867363835.
ODM said it doesn't support DPTF.

I dump the log and acpidump from otehr machine, please take a look.
[thermald.log](https://github.com/intel/thermal_daemon/files/6713034/thermald.log)
[acpidump.log](https://github.com/intel/thermal_daemon/files/6713035/acpidump.log)

For the acpidumg.log, please do acpixtract for getting the tables.

**Comment by spandruvada** [comment]
This system is giving bogus temperature of 50/1000 C. So this is not ready for thermal test yet.

**Comment by spandruvada** [comment]
If there is any change in the situation here, please run
https://github.com/intel/thermal_daemon/blob/master/test/thermal-debug-dump-ubuntu.sh
and attach the output

**Comment by KaiChuan-Hsieh** [comment]
@spandruvada 

Currently, ODM has no sample having the real temperature, which means all ADL-S hardware is not ready for thermal. ODM will receive QS CPU MB this week, will check if there is any change.

I'd like to know if the https://github.com/intel/thermal_daemon/commit/b7b460451c3baf7debc4a7da2aa73baddc40967a can be merged first?

**Comment by KaiChuan-Hsieh** [comment]
The TCPU_PCI and TCPU reports different temperature. the script and its output while running stress-ng in the following file.
[check-temp.zip](https://github.com/intel/thermal_daemon/files/7075244/check-temp.zip)
