### ISSUE TITLE
i915 *ERROR* Atomic update failure on pipe A AND snd_pcm_avail()...value...exceptionally large ¿Cause thermald.service?

### ISSUE THREAD

**Issue by Jeronimo17** [intel/thermal_daemon#302]
Hello, 
How do I put the Linux Mint forum https://forums.linuxmint.com/viewtopic.php?f=49&t=344425 
It seems that **thermald.service** was causing me a series of errors playing games on Steam in Linux that blocked my laptop stopping responding to the internal keyboard and power button (connecting a usb keyboard and the usb mouse still responds but the complete shutdown of the system never ends) It seems to always start with the stuttering of the sound being played 

For now without this service I have not had any problems 

```
jeronimo17@jeronimo17-GIGABYTE-AORUS-7-KB ~ $ inxi -Fxzn
System:    Kernel: 5.8.0-53-generic x86_64 bits: 64 compiler: N/A Desktop: Xfce 4.14.2 
           Distro: Linux Mint 20.1 Ulyssa base: Ubuntu 20.04 focal 
Machine:   Type: Laptop System: GIGABYTE product: AORUS 7 KB v: N/A serial: <filter> 
           Mobo: GIGABYTE model: AORUS 7 KB serial: <filter> UEFI: INSYDE v: FB06 date: 08/03/2020 
Battery:   ID-1: BAT0 charge: 48.0 Wh condition: 48.0/47.2 Wh (102%) model: Notebook BAT status: Full 
CPU:       Topology: 6-Core model: Intel Core i7-10750H bits: 64 type: MT MCP arch: N/A L2 cache: 12.0 MiB 
           flags: avx avx2 lm nx pae sse sse2 sse3 sse4_1 sse4_2 ssse3 vmx bogomips: 62399 
           Speed: 3349 MHz min/max: 800/5000 MHz Core speeds (MHz): 1: 2624 2: 2587 3: 2576 4: 2501 
           5: 2537 6: 2508 7: 2410 8: 2531 9: 2566 10: 2247 11: 2570 12: 2556 
Graphics:  Device-1: Intel UHD Graphics vendor: CLEVO/KAPOK driver: i915 v: kernel bus ID: 00:02.0 
           Device-2: NVIDIA TU106 [GeForce RTX 2060] vendor: CLEVO/KAPOK driver: nvidia v: 460.80 
           bus ID: 01:00.0 
           Display: x11 server: X.Org 1.20.9 driver: modesetting,nvidia unloaded: fbdev,nouveau,vesa 
           resolution: 1920x1080~144Hz 
           OpenGL: renderer: GeForce RTX 2060/PCIe/SSE2 v: 4.6.0 NVIDIA 460.80 direct render: Yes 
Audio:     Device-1: Intel Comet Lake PCH cAVS vendor: CLEVO/KAPOK driver: snd_hda_intel v: kernel 
           bus ID: 00:1f.3 
           Device-2: NVIDIA TU106 High Definition Audio driver: snd_hda_intel v: kernel bus ID: 01:00.1 
           Sound Server: ALSA v: k5.8.0-53-generic 
Network:   Device-1: Intel Wi-Fi 6 AX200 driver: iwlwifi v: kernel port: 5000 bus ID: 0c:00.0 
           IF: wlp12s0 state: down mac: <filter> 
           Device-2: Realtek RTL8111/8168/8411 PCI Express Gigabit Ethernet vendor: CLEVO/KAPOK 
           driver: r8169 v: kernel port: 3000 bus ID: 0d:00.1 
           IF: enp13s0f1 state: up speed: 1000 Mbps duplex: full mac: <filter> 
Drives:    Local Storage: total: 1.12 TiB used: 528.35 GiB (46.0%) 
           ID-1: /dev/nvme0n1 model: SX8200PNP-512GT-S size: 476.94 GiB 
           ID-2: /dev/sda model: Q-720 size: 670.69 GiB 
Partition: ID-1: / size: 144.03 GiB used: 41.74 GiB (29.0%) fs: ext4 dev: /dev/nvme0n1p4 
           ID-2: /home size: 192.12 GiB used: 127.31 GiB (66.3%) fs: ext4 dev: /dev/nvme0n1p5 
           ID-3: swap-1 size: 7.91 GiB used: 0 KiB (0.0%) fs: swap dev: /dev/nvme0n1p6 
Sensors:   System Temperatures: cpu: 49.0 C mobo: N/A gpu: nvidia temp: 44 C 
           Fan Speeds (RPM): cpu: 2047 
Info:      Processes: 316 Uptime: 1h 22m Memory: 15.34 GiB used: 2.84 GiB (18.5%) Init: systemd 
           runlevel: 5 Compilers: gcc: 9.3.0 clang: 10.0.0-4ubuntu1 Shell: bash v: 5.0.17 inxi: 3.0.38 
```

**Comment by spandruvada** [comment]
Hi,
On Wed, 2021-06-02 at 03:36 -0700, Jeronimo17 wrote:

Hello,
How do I put the Linux Mint forum https://forums.linuxmint.com/viewtopic.php?f=49&t=344425
It seems that thermald.service was causing me a series of errors playing games on Steam in Linux that blocked my laptop stopping responding to the internal keyboard and power button (connecting a usb keyboard and the usb mouse still responds but the complete shutdown of the system never ends) It seems to always start with the stuttering of the sound being played

Not sure how thermald service can cause this issue unless it is throttling.
So disable thermald service via systemctl stop thernmald" and reboot.
After reboot just run from a shell:
#thermald --no-daemon --loglevel=info --adaptive

Then do what you do to trigger this and copy paste the output of thermald to a file and attach the output.

Thanks.


For now without this service I have not had any problems

***@***.***GIGABYTE-AORUS-7-KB ~ $ inxi -Fxzn
System:    Kernel: 5.8.0-53-generic x86_64 bits: 64 compiler: N/A Desktop: Xfce 4.14.2
           Distro: Linux Mint 20.1 Ulyssa base: Ubuntu 20.04 focal
Machine:   Type: Laptop System: GIGABYTE product: AORUS 7 KB v: N/A serial: <filter>
           Mobo: GIGABYTE model: AORUS 7 KB serial: <filter> UEFI: INSYDE v: FB06 date: 08/03/2020
Battery:   ID-1: BAT0 charge: 48.0 Wh condition: 48.0/47.2 Wh (102%) model: Notebook BAT status: Full
CPU:       Topology: 6-Core model: Intel Core i7-10750H bits: 64 type: MT MCP arch: N/A L2 cache: 12.0 MiB
           flags: avx avx2 lm nx pae sse sse2 sse3 sse4_1 sse4_2 ssse3 vmx bogomips: 62399
           Speed: 3349 MHz min/max: 800/5000 MHz Core speeds (MHz): 1: 2624 2: 2587 3: 2576 4: 2501
           5: 2537 6: 2508 7: 2410 8: 2531 9: 2566 10: 2247 11: 2570 12: 2556
Graphics:  Device-1: Intel UHD Graphics vendor: CLEVO/KAPOK driver: i915 v: kernel bus ID: 00:02.0
           Device-2: NVIDIA TU106 [GeForce RTX 2060] vendor: CLEVO/KAPOK driver: nvidia v: 460.80
           bus ID: 01:00.0
           Display: x11 server: X.Org 1.20.9 driver: modesetting,nvidia unloaded: fbdev,nouveau,vesa
           resolution: 1920x1080~144Hz
           OpenGL: renderer: GeForce RTX 2060/PCIe/SSE2 v: 4.6.0 NVIDIA 460.80 direct render: Yes
Audio:     Device-1: Intel Comet Lake PCH cAVS vendor: CLEVO/KAPOK driver: snd_hda_intel v: kernel
           bus ID: 00:1f.3
           Device-2: NVIDIA TU106 High Definition Audio driver: snd_hda_intel v: kernel bus ID: 01:00.1
           Sound Server: ALSA v: k5.8.0-53-generic
Network:   Device-1: Intel Wi-Fi 6 AX200 driver: iwlwifi v: kernel port: 5000 bus ID: 0c:00.0
           IF: wlp12s0 state: down mac: <filter>
           Device-2: Realtek RTL8111/8168/8411 PCI Express Gigabit Ethernet vendor: CLEVO/KAPOK
           driver: r8169 v: kernel port: 3000 bus ID: 0d:00.1
           IF: enp13s0f1 state: up speed: 1000 Mbps duplex: full mac: <filter>
Drives:    Local Storage: total: 1.12 TiB used: 528.35 GiB (46.0%)
           ID-1: /dev/nvme0n1 model: SX8200PNP-512GT-S size: 476.94 GiB
           ID-2: /dev/sda model: Q-720 size: 670.69 GiB
Partition: ID-1: / size: 144.03 GiB used: 41.74 GiB (29.0%) fs: ext4 dev: /dev/nvme0n1p4
           ID-2: /home size: 192.12 GiB used: 127.31 GiB (66.3%) fs: ext4 dev: /dev/nvme0n1p5
           ID-3: swap-1 size: 7.91 GiB used: 0 KiB (0.0%) fs: swap dev: /dev/nvme0n1p6
Sensors:   System Temperatures: cpu: 49.0 C mobo: N/A gpu: nvidia temp: 44 C
           Fan Speeds (RPM): cpu: 2047
Info:      Processes: 316 Uptime: 1h 22m Memory: 15.34 GiB used: 2.84 GiB (18.5%) Init: systemd
           runlevel: 5 Compilers: gcc: 9.3.0 clang: 10.0.0-4ubuntu1 Shell: bash v: 5.0.17 inxi: 3.0.38

**Comment by Jeronimo17** [comment]
I can't cause the failure, it happens very rarely, but the log so far

[File.txt](https://github.com/intel/thermal_daemon/files/6585790/File.txt)

**Comment by spandruvada** [comment]
Your CPU is constantly reaching 95C so it getting throttled to CPU at 95C. If you think you can tolerate higher CPU temperature then use http://manpages.ubuntu.com/manpages/bionic/man5/thermal-conf.xml.5.html example 1 to change this to a higher temperature.

**Comment by Jeronimo17** [comment]
Could that measurement be wrong? It is a fairly new laptop, clean and activated by keyboard 100% of the fans, here it is not reaching that temperature.

![Temperatura](https://user-images.githubusercontent.com/4985763/120552212-41033600-c3f7-11eb-9982-b1f3120f5868.png)


dmesg does not indicate throttling cpu at any time, (with the old kernel yes but I think it was also wrong)

**Comment by spandruvada** [comment]
The measurement is not wrong. New kernel has filter to show throttling message. But that doesn't matter. HW may throttle at different temp. It is not unusual to reach 95C depending on workload. thermald is trying to keep 5C lower than critical.
For some users this doesn't work so they need to set to higher close to critical.
