### ISSUE TITLE
ThermalMonitor: Can't establish link with thermal daemon

### ISSUE THREAD

**Issue by ceckertz** [intel/thermal_daemon#305]
Hello everyone, 

I'm a bit of a Linux noob so please bare with me....

When I try to start ThermalMonitor a popup window tells me, it can't establish link with thermal daemon.
It goes on to say: 
 _Make sure that thermal daemon started with --dbus-enable option
and that you're in the 'power' group._
Systemctl status shows --dbus-enable to be true. 

When I try to run it from the console: 
`$ ThermalMonitor`
`Gtk-Message: 17:03:50.153: Failed to load module "colorreload-gtk-module"
error from "org.freedesktop.thermald" = QDBusError("org.freedesktop.DBus.Error.AccessDenied", "Sender is not authorized to send message")`

Because I'm a noob I can't make much sense of this, maybe someone can help.
Kind regards,
jo
edit: 
I'm on fedora 34.

**Comment by dmirubtsov** [comment]
> and that you're in the 'power' group.

did you add yourself to `power` group?

```bash
sudo gpasswd -a $USER power 
```

and then relogin

**Comment by ceckertz** [comment]
Dear @dmirubtsov 

I feel like an idiot for not looking into the power group, but now I'm all the wiser for it. 
Thank you very much for taking the time to help me! 

Kind regards, 
jo
