### ISSUE TITLE
Inconsistency between GPLv2+ and GPLv2

### ISSUE THREAD

**Issue by benzea** [intel/thermal_daemon#306]
I noticed that `thd_cdev_modem.{cpp,h}` have a GPLv2 license header rather than GPLv2+.

Just to clarify, is this intentional and desired or was it simply not noticed that a GPLv2 only file was added after d61fd1b3931b8af86ef133c6c069bb215289946f?

**Comment by spandruvada** [comment]
This was not intentional. The submitter didn't check correctly.

**Comment by spandruvada** [comment]
Fixed with release 2.4.7
