### ISSUE TITLE
Jasper Lake CPUID levels; family:model:stepping 0x6:9c:0 (6:156:0) is not included

### ISSUE THREAD

**Issue by andch-nn** [intel/thermal_daemon#309]
I check the id_table, the CPUID is not included. Does it mean that thermald can't support the CPU?

Below is the log of thermald in Ubuntu 20.04
ubuntu systemd[1]: Starting Thermal Daemon Service...
ubuntu systemd[1]: Started Thermal Daemon Service.
ubuntu thermald[974]: 27 CPUID levels; family:model:stepping 0x6:9c:0 (6:156:0)
ubuntu thermald[974]:  Need Linux PowerCap sysfs
ubuntu thermald[974]: Unsupported cpu model or platform
ubuntu systemd[1]: thermald.service: Succeeded.

Thanks.

**Comment by spandruvada** [comment]
Please run and attach the generated tar file:

https://github.com/intel/thermal_daemon/blob/master/test/thermal-debug-dump-ubuntu.sh

**Comment by andch-nn** [comment]
Hi @spandruvada ,
Here is the attached file.
Thanks.
[26200416.tar.gz](https://github.com/intel/thermal_daemon/files/6878189/26200416.tar.gz)

**Comment by andch-nn** [comment]
Hello @spandruvada ,
Does thermald plan to support Jasper lake?

**Comment by spandruvada** [comment]
Added cpu model to the code. So this platform should be supported. If backport is required for distro, include this commit
https://github.com/intel/thermal_daemon/commit/d28613aea8179c068cfab853f5aa2a0c2b7adebf
