### ISSUE TITLE
manual is missing some options

### ISSUE THREAD

**Issue by ColinIanKing** [intel/thermal_daemon#312]
thermald --help shows more options than are in the manual:  The missing options are as follows:

--ignore-default-control
--workaround-enabled
--disable-active-power
--ignore-critical-trip

The --workaround-enabled option is particularly useful, so it would be extra helpful if it could explain why it is required and a list of known machines that it could be useful for.

**Comment by spandruvada** [comment]
Fixed in release 2.4.7
