### ISSUE TITLE
Dell Inspiron 5491 overheating

### ISSUE THREAD

**Issue by julia-otran** [intel/thermal_daemon#313]
Hi, i'm using ubuntu 21.04 in a Dell Inspiron 5491 with a cpu Intel® Core™ i7-10510U CPU @ 1.80GHz × 8  and it is overheating.

By reading thermald logs I can see lots of files not found such as
```
[1632185452][DEBUG] /sys/class/powercap/intel-rapl/uevent/name doesn't exist
```
and also
```
[1632185452][INFO]Also unable to evaluate any conditions
[1632185452][INFO]Falling back to use configuration with the highest power
```
Which I think it is the cause of the problem.

I've also checked that
```
[1632189610][MSG]22 CPUID levels; family:model:stepping 0x6:8e:c (6:142:12)
```
It is a supported cpu.

[log-thermald.log](https://github.com/intel/thermal_daemon/files/7199677/log-thermald.log)

```
➜  ~ thermald --version
2.4.6
```

```
➜  ~ uname -r
5.11.0-34-generic
```

**Comment by dlezcano** [comment]
What is overheating ? The CPU or the laptop ?

How do you know it is overheating ?

**Comment by julia-otran** [comment]
I know it overheat because it have hard shutted-down. 
Also, after the shutdown o could check for bios logs and the reason was a CPU overheat.

Another thing that may be important, is that i coudn't reproduce this using `stress`. However using google meet, or zoom causes the problem.

**Comment by julia-otran** [comment]
Just did a GPU test, and the processor temp increased quickly. However using stress did not caused problems.
I could see that GPU slowdown temp is 96º according to NVidia settings. However, the processor is always more hot than GPU and I think thats the reason it is shutting down.

Will check if there's any way to reduce the slowdown temp for gpu.

**Comment by julia-otran** [comment]
I just set nvidia settings to `On Demand` mode. Now it is not overheating anymore.

However nvidia is not used anymore. (but that's another problem).
I'm going to close this because its not a thermald bug.
