### ISSUE TITLE
Thermald does not stop temperature rising in zone0

### ISSUE THREAD

**Issue by pscdasilva54** [intel/thermal_daemon#317]
Hi!

Thermald does not stop temperature rising in zone0

This is what happens:
1. Starting the PC from power off status.
2. Running a full cpu script - all 8 cores,  16 threads running.
3. The zone0 temperature goes up to 97ºC and stabilizes there.
So, no problem so far.
4. Suspend/wake the PC.
5. Running a full cpu script - all 8 cores,  16 threads running.
6. The zone0 temperature goes fast until 110ºC and something (the kernel?) shuts down the PC.

As much as I could see, it seems that thermald is not doing anything useful to cool zone0!

BTW, the fans seem to have a good behavior - in both cases they speed up as the temperature rises.
Nevertheless they never reach the RPM of "boost mode". They never did it before, however.
If I manually put them in boost mode the temperature doesn't go to the point of shutdown. It never reachs 100ºC.

If I decrease the CPU frequencies from its max 5.1GHz to, for example, 2.5GHz, the temperature in zone0 never goes up 50ºC.

I am running kubuntu 20.04 in a MSI GS75 Stealth 10SF.
I am using the thermald of the distribution, but I already tried with last version which I compiled here.

I didn't use any configuration file before. Now I am trying with one generated by dptfxtract, last version.

Please ask for any further information you may need.

Thanks for any help or comments on this.

**Comment by pscdasilva54** [comment]
Does anybody please provide me a configuration file to control the temperature from
/sys/devices/virtual/thermal/thermal_zone0/temp
BTW, how do I know which cooling devices are available?
Thanks

**Comment by dlezcano** [comment]
Usually thermal is managed from the firmware on those platforms.
Can you share the content of /sys/class/thermal and then /sys/class/thermal/*/type ?
It is also possible the CPU thermal paste may be renewed, how old is the hardware ?

**Comment by pscdasilva54** [comment]
/sys/class/thermal # ls -1
cooling_device0
cooling_device1
cooling_device10
cooling_device11
cooling_device12
cooling_device13
cooling_device14
cooling_device15
cooling_device16
cooling_device2
cooling_device3
cooling_device4
cooling_device5
cooling_device6
cooling_device7
cooling_device8
cooling_device9
thermal_zone0
thermal_zone1
thermal_zone2
thermal_zone3
thermal_zone4
thermal_zone5

/sys/class/thermal # cat /sys/class/thermal/*/type
Processor
Processor
Processor
Processor
Processor
Processor
Processor
intel_powerclamp
Processor
Processor
Processor
Processor
Processor
Processor
Processor
Processor
Processor
acpitz
SEN2
pch_cometlake
B0D4
x86_pkg_temp
iwlwifi_1

About how old ... not sure but no more than a couple of yrs.

A strange thing is that before 1st. suspension, the temp at zone0 is kept stable at 97ºC while in "full cpu" usage. Temp only rises after one suspension has occurred. From then after, I need to reduce the max. freqs. to 2.5GHz to avoid the "limit situation" where something (kernel?) shuts down the computer at 110ºC.
That's when I expected that thermald could avoid this, as last resource.

Thanks

**Comment by spandruvada** [comment]
If issue persists, please reopen.
