### ISSUE TITLE
Thermald can't run on this platform

### ISSUE THREAD

**Issue by jsilve24** [intel/thermal_daemon#318]
Just upgraded to Ubuntu 21.10. I noticed some random restarts and tracked it down to a critical temperature issue. 

Checking systemctl status thermald showed a problem that I think may be behind the random shudowns. 

```
❯ systemctl status thermald
○ thermald.service - Thermal Daemon Service
     Loaded: loaded (/lib/systemd/system/thermald.service; enabled; vendor preset: enabled)
     Active: inactive (dead) since Tue 2021-10-19 15:45:44 EDT; 5min ago
    Process: 981 ExecStart=/usr/sbin/thermald --systemd --dbus-enable --adaptive (code=exited, status=0/SUCCESS)
   Main PID: 981 (code=exited, status=0/SUCCESS)
        CPU: 7ms

Oct 19 15:45:44 i4-fl-jds6696 systemd[1]: Starting Thermal Daemon Service...
Oct 19 15:45:44 i4-fl-jds6696 systemd[1]: Started Thermal Daemon Service.
Oct 19 15:45:44 i4-fl-jds6696 thermald[981]: 22 CPUID levels; family:model:stepping 0x6:9e:d (6:158:13)
Oct 19 15:45:44 i4-fl-jds6696 thermald[981]: [/sys/devices/platform/thinkpad_acpi/dytc_lapmode] present: Thermald can't run on this platform
Oct 19 15:45:44 i4-fl-jds6696 thermald[981]: Unsupported cpu model or platform
```

Not really sure how to debug or fix this. I upgraded all firmware (through Ubuntu Software app), purged and reinstalled thermald. I checked the version and I am running thermald 2.4.6 which I noticed in the commit messages has a "fix for ubuntu" but beyond that I am not sure what other information I can provide. 

Thank you!
Justin

**Comment by benzea** [comment]
It is the intended behaviour, as the firmware manages things.
