### ISSUE TITLE
Confused: Number units in thermal-conf.xml

### ISSUE THREAD

**Issue by donquixote** [intel/thermal_daemon#320]
I have the following thermal-conf.xml.auto generated by dptfxtract.
(on LG Gram 2021)

```xml
<?xml version="1.0"?>
 <!-- BEGIN -->
 <ThermalConfiguration>
 <Platform>
        <Name> Auto generated </Name>
        <ProductName>17Z90P-G.AA79G</ProductName>
        <Preference>QUIET</Preference>
        <PPCC>
                <PowerLimitIndex>0</PowerLimitIndex>
                <PowerLimitMinimum>12000</PowerLimitMinimum>
                <PowerLimitMaximum>17000</PowerLimitMaximum>
                <TimeWindowMinimum>28000</TimeWindowMinimum>
                <TimeWindowMaximum>32000</TimeWindowMaximum>
                <StepSize>500</StepSize>
        </PPCC>
        <ThermalZones>
                <ThermalZone>
                        <Type>auto_zone_0</Type>
                        <TripPoints>
                                <TripPoint>
                                        <SensorType>SEN2</SensorType>
                                        <Temperature>62000</Temperature>
                                        <Type>Passive</Type>
                                        <CoolingDevice>
                                                <Type>B0D4</Type>
                                                <SamplingPeriod>3</SamplingPeriod>
                                                <TargetState>2147483647</TargetState>
                                        </CoolingDevice>
                                </TripPoint>
                                <TripPoint>
                                        <SensorType>SEN2</SensorType>
                                        <Temperature>63000</Temperature>
                                        <Type>Passive</Type>
                                        <CoolingDevice>
                                                <Type>B0D4</Type>
                                                <SamplingPeriod>3</SamplingPeriod>
                                        </CoolingDevice>
                                </TripPoint>
                        </TripPoints>
                </ThermalZone>
        </ThermalZones>
</Platform>
</ThermalConfiguration>
<!-- END -->
```

There are many numbers here, but what do they mean?
I assume `<Temperature>62000</Temperature>` means 62°C.
But PowerLimit? Are these millivolts?
TimeWindow? SamplingPeriod? StepSize? Are these microseconds? seconds?
And what's a TargetState?
Why are the temperatures of the two trip points so close to each other?

I assume to verify that it works I could simply lower the trip point temperatures to e.g. 30°C, and somehow restart thermald and then the fan should go full speed?

(see also #319)

**Comment by z-image** [comment]
I was wandering the same. Maybe inherited from ACPI specification?

https://uefi.org/specs/ACPI/6.4/11_Thermal_Management/thermal-objects.html

There SamplingPeriod is described as:


> The minimum period of time in tenths of seconds that OSPM should wait after applying a passive control to the device indicated by SourceDevice to detect its impact on the device indicated by TargetDevice.

**Comment by spandruvada** [comment]
I assume <Temperature>62000</Temperature> means 62°C.
Yes

But PowerLimit? Are these millivolts?
Milli Watt

TimeWindow? 

SamplingPeriod?
milli second


 StepSize? Are these microseconds? seconds?

And what's a TargetState?
The power you will apply. If you see value 2147483647, that means whatever PwerLimitMaximum specifies

Why are the temperatures of the two trip points so close to each other?
At 62 apply full power and 63 slowly reduce power till PowerLimitMinimum
