### ISSUE TITLE
Performance with one process at 100% and temperature at idle

### ISSUE THREAD

**Issue by ArchangeGabriel** [intel/thermal_daemon#33]
Hi,

I’ve been running and not running thermald for some time now, and I’ve found two strange behaviour in my opinion.

The first one is a perf limitation when I run any program that uses 100% of a core for a measurable amount of time. The program run twice slower with thermald running, for example I have a python script that usually takes 6 min on my machine to complete, but takes 12 when thermald is running. When I look in htop, I see that the process is capped at 45-46% percent of one core with thermald enabled.

And time returns this (with thermald, without user and total are in agreement):
./script.py  357,76s user 0,07s system 49% cpu 11:56,63 total

The second strange behavior is the temperatures at idle. They seems to be quite higher with thermald running than without. I’m not sure and need to test properly that (like look at temperatures after 15 min of idle while starting from a cold boot), but I would say something like all CPUs reporting 40 °C without and 47 °C with thermald.

And for both issues, if I start my computer without thermald enabled and then enable it, they happen, but they don’t stop happening until I reboot my computer with thermald disabled, whether it started from boot or manually after.

Except for that, it seems to work quite well, I almost never hear my fans, and the computer never reach very high temperatures.

I’m running Arch Linux, and I’ve been observing this behavior ever since January when I first tried thermald.

I would be happy to provide you with any supplemental informations you could need and would be glad to test anything you might want in order to help you figure out the causes of those strange behavior and fix them.

**Comment by spandruvada** [comment]
Closing older issues, reopen if you need to.
