### ISSUE TITLE
upower lid functions are deprecated and need to be replaced

### ISSUE THREAD

**Issue by paul-jewell** [intel/thermal_daemon#340]
When building version 2.4.7 with upower-0.99.15, the build fails with a deprecated function error:

`src/thd_engine_adaptive.cpp: In member function ‘int cthd_engine_adaptive::evaluate_lid_condition(condition)’:
src/thd_engine_adaptive.cpp:1002:61: error: ‘gboolean up_client_get_lid_is_closed(UpClient*)’ is deprecated [-Werror=deprecated-declarations]
 1002 |  bool lid_closed = up_client_get_lid_is_closed(upower_client);`

This has been deprecated with the update of upower to 0.15. According to their merge, logind functionality should be used instead:
[https://gitlab.freedesktop.org/upower/upower/-/merge_requests/5](url)

I could try to make a pull request, but I am not a C++ expert, and also don't know my way around the thermald code, so I don't think it would be helpful. When I look at the pull request to update gnome settings daemon to overcome this issue, I wouldn't know how to make this change gnome-agnostic (which I assume it should be).
This issue is referenced in Debian bug report: [https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=1005478](url)
(and also on other distributions)

EDIT: Looks like this is already in hand: [https://github.com/intel/thermal_daemon/pull/338/commits/93c7d2783b28a4b5ec5ca5071881547b5ee65da3](url)

**Comment by benzea** [comment]
Yep, #338 includes a fix for this.

**Comment by spandruvada** [comment]
I will include this week.
