### ISSUE TITLE
Undocumented options - mission options in man page

### ISSUE THREAD

**Issue by ColinIanKing** [intel/thermal_daemon#342]
A Debian user reported that there are some options missing from the man page:

Package: thermald
Version: 2.4.7-2
Severity: minor
X-Debbugs-Cc: debian@dirdi.name

At least the following options have not been documented at the man page:
--systemd
--test-mode
--adaptive

-- System Information:
Debian Release: bookworm/sid
  APT prefers testing
  APT policy: (500, 'testing'), (50, 'unstable'), (5, 'experimental')
Architecture: amd64 (x86_64)

https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=1006819

**Comment by spandruvada** [comment]
Fixed in 2.4.9. --adaptive was already in man page.
