### ISSUE TITLE
Dell Latitude 7420 - batch of errors and warnings

### ISSUE THREAD

**Issue by gguman** [intel/thermal_daemon#343]
Hi to all! 

Could anyone help me with errors and warnings of thermald plz.

1) unsupported condition 57 (Power_slider)
2) Unable to find a zone for TSSD
3) NO RAPL sysfs present
4) Thermal DTS: No coretemp sysfs found

Latest version of thermald. Kernel 5.15. Debian

**Comment by spandruvada** [comment]
Those errors are fine. We don't support some conditions. For the others we have alternatives to use.
