### ISSUE TITLE
Recent _OSC changes and Dell XPS 9710

### ISSUE THREAD

**Issue by morgoth6** [intel/thermal_daemon#346]
Not first time, but recent _OSC patch along with recent thermald release shows problems with Dell DSDT code. Tested with lastest BIOS release 1.7.2 and kernel 5.16.16 with patches from [#341](https://github.com/intel/thermal_daemon/issues/341#issuecomment-1072476730) 
```
ACPI BIOS Error (bug): Could not resolve symbol [\_TZ.ETMD], AE_NOT_FOUND (20211217/psargs-330)

No Local Variables are initialized for Method [_OSC]
Initialized Arguments for Method [_OSC]:  (4 arguments defined for method invocation)
   Arg0:   0000000054be46e0 <Obj>           Buffer(16) 5D A8 3B B2 B7 C8 42 35
   Arg1:   000000002a80f409 <Obj>           Integer 0000000000000001
   Arg2:   00000000c5c9b15c <Obj>           Integer 0000000000000002
   Arg3:   000000002a983728 <Obj>           Buffer(8) 00 00 00 00 05 00 00 00

ACPI Error: Aborting method \_SB.IETM._OSC due to previous error (AE_NOT_FOUND) (20211217/psparse-529)
```

It seems variable is used in SSDT2 in _OSC method:
```
                        If ((CAP1 & One))
                        {
                            If ((CAP1 & 0x02))
                            {
                                \_SB.AAC0 = 0x6E
                                \_TZ.ETMD = Zero
                            }
                            Else
                            {
                                \_SB.AAC0 = ATRP /* \_SB_.IETM.ATRP */
                                \_TZ.ETMD = One
                            }

                            If ((CAP1 & 0x04))
                            {
                                \_SB.APSV = 0x6E
                            }
                            Else
                            {
                                \_SB.APSV = PTRP /* \_SB_.IETM.PTRP */
                            }
                            
                            If ((CAP1 & 0x08))
                            {
                                \_SB.ACRT = 0xD2
                            }
                            Else
                            {
                                \_SB.ACRT = YTRP /* \_SB_.IETM.YTRP */
                            }
                        }
                        Else
                        {
                            \_SB.ACRT = YTRP /* \_SB_.IETM.YTRP */
                            \_SB.APSV = PTRP /* \_SB_.IETM.PTRP */
                            \_SB.AAC0 = ATRP /* \_SB_.IETM.ATRP */
                            \_TZ.ETMD = One
                        }
```
But it has no definition in DSDT and any of the SSDT's. I wonder as this type of problem can be see in almost all XPS and/or Precision models is anyone tests this ? I guess Windows is using same mechanisms right ?

I already use custom DSDT to fix Dell slopiness in _Q66 methods so maybe I will try to defint missing varable just to see what will bork next. I wonder is anyone here have access to anyone at Dell to report this kind of problems ? I tired in the past rto use their's support forum, but in most cases they simply remove and block this kind of posts.

**Comment by spandruvada** [comment]
This is a missing variable as far as I can say. Informed Dell about this.

**Comment by paravoid** [comment]
I also see this with the patches from #341, thermald 2.4.9, but on a Latitude 7420 (SKU Number: 0A36), BIOS Version 1.14.1 (Release Date: 12/18/2021).

**Comment by morgoth6** [comment]
> This is a missing variable as far as I can say. Informed Dell about this.

The method execution is aborted in this case or continued ? If aborted there is quite some things missing after this variable assignment ([ssdt2.dsl.gz](https://github.com/intel/thermal_daemon/files/8353229/ssdt2.dsl.gz) around line 271) so probably not everything would be set as expected by FW.

**Comment by XGIVolari** [comment]
My Lenovo Ideapad 5 15ITL05 has the exact same _OSC method in SSDT2 and encounters this issue as well. I worked around this by simply deleting all references to ETMD. Additionally, I had to remove a check for OSYS (Windows Version determined by ACPI) in SSDT10, which caused AAC0, APSV and ACRT to be missing. Now, thermald starts in adaptive mode without triggering ACPI errors. Without this fix, thermald is able to activate the INT3400 thermal zone, but cannot deactivate it again on exit. This is working properly now as well.

**Comment by dionorgua** [comment]
Same thing happens with HP Elitebook 850 G7 (latest BIOS)

**Comment by gdevenyi** [comment]
@morgoth6 Its 2024 and Dell is still releasing BIOSs with the same ACPI bugs, in my case XPS 13 7390 has the same issues.

Would you be willing to write up a quick github gist explaining how you go from dumping/patching the missing ETMD symbol and recompiling the tables? (and maybe explain how you figured out the options for the DefinitionBlock?)

**Comment by gdevenyi** [comment]
@spandruvada can you cite the commit which attempts to address these broken BIOS maps?
