### ISSUE TITLE
dell i712800h is throttled on 2Ghz during stress-ng

### ISSUE THREAD

**Issue by Kobatw** [intel/thermal_daemon#347]
Description:
With i7 12800h,
1. open s-tui
2. run stress-ng,
3. cpu is throttled on 2Ghz.
*here're SB.IETM dump
     Scope (\_SB.IETM)  
        Name (DP2P, Package (0x01)  
            ToUUID ("9e04115a-ae87-4d1c-9500-0f3e340bfe75")  
        Name (DPSP, Package (0x01)  
            ToUUID ("42a441d6-ae6a-462b-a84b-4a8ce79027d3")  
        Name (DASP, Package (0x01)  
            ToUUID ("3a95c389-e4b8-4629-a526-c52c88626bae")
        Name (DA2P, Package (0x01)
            ToUUID ("0e56fab6-bdfc-4e8c-8246-40ecfd4d74ea")
        Name (DCSP, Package (0x01)
            ToUUID ("97c68ae7-15fa-499c-b8c9-5da81d606e0a")
        Name (RFIP, Package (0x01)
            ToUUID ("c4ce1849-243a-49f3-b8d5-f97002f38e6a")
        Name (DAPP, Package (0x01)
            ToUUID ("63be270f-1c11-48fd-a6f7-3af253ff3e2d")
        Name (DPID, Package (0x01)
            ToUUID ("42496e14-bc1b-46e8-a798-ca915464426f")

*here's thermal debug logs
[31110849.tar.gz](https://github.com/intel/thermal_daemon/files/8385785/31110849.tar.gz)

**Comment by spandruvada** [comment]
Still looking into it.

**Comment by spandruvada** [comment]
What is the Dell model for this XPS?

**Comment by kobataiwan** [comment]
@spandruvada sorry, in this moment i couldn't share the model publicly.

**Comment by Kobatw** [comment]
@spandruvada sorry, i can't share model in this moment publicly

**Comment by spandruvada** [comment]
Please send email to my intel address, if possible.

**Comment by spandruvada** [comment]
Please test
checkout branch thermald_2_5_devel
build and
run test/thermal-debug-dump-ubuntu.sh or Fedora equivalent and
send me logs.

**Comment by spandruvada** [comment]
If the problem persist,attach logs and reopen.
