### ISSUE TITLE
dbus-glib is deprecated, should use gdbus

### ISSUE THREAD

**Issue by AdrianVovk** [intel/thermal_daemon#348]
Hello! Packaging thermald for a new distro here, and noticed that you're still depending on dbus-glib

[The dbus-glib library is obsolete and unmaintained](https://www.freedesktop.org/wiki/Software/DBusBindings#dbus-glibobsoleteunmaintained). According to its git README, projects [should port to use gdbus](https://gitlab.freedesktop.org/dbus/dbus-glib) which is available since GLib 2.26, which thermald happens to depend on.

**Comment by spandruvada** [comment]
Sorry, Didn't get time to get to this yet.

**Comment by spandruvada** [comment]
Any volunteers to do this change?

**Comment by smallorange** [comment]
I'm currently doing this.
Moreover, do you consider meson as the primary build scheme?

Thank you
