### ISSUE TITLE
i7-11800H: sensor id 22 : No temp sysfs for reading raw temp_

### ISSUE THREAD

**Issue by Massimo-B** [intel/thermal_daemon#350]
I'm running thermal_daemon-2.4.9 on Gentoo Linux without any configuration like
`thermald --dbus-enable --adaptive`.

In the syslog appears:

```
Apr 22 11:46:39 [thermald] 27 CPUID levels; family:model:stepping 0x6:8d:1 (6:141:1)_
                - Last output repeated twice -
Apr 22 11:46:39 [thermald] sensor id 22 : No temp sysfs for reading raw temp_
                - Last output repeated 2 times -
Apr 22 11:46:40 [thermald] Polling mode is enabled: 4_
Apr 22 11:46:44 [thermald] Manufacturer didn't provide adequate support to run in_
Apr 22 11:46:44 [thermald] optimized configuration on Linux with open source_
Apr 22 11:46:44 [thermald] You may want to disable thermald on this system if you see issue_
```

However for testing I have generated a config with dptfxtract-1.4.3-r1. That created a list of configuration files with the same result when running thermald, so I deleted those files again.

Is thermald working correctly on that machine?

**Comment by spandruvada** [comment]
run test/thermal-debug-dump-ubuntu.sh or Fedora equivalent and
attach logs

**Comment by Massimo-B** [comment]
I checked both ubuntu and Fedora scripts. They both will fail at the installation of git, autoconf-archive, g++... dependencies. Then it's going to fetch thermald from github and build it. I could adapt all that to have a script for Gentoo.

Which commands do you actually need to debug the issue?

But why don't you offer a generic debug script that just checks for all the deps and thermald being available and just use the available version?
