### ISSUE TITLE
Starting trigger for systemd

### ISSUE THREAD

**Issue by sebastianha** [intel/thermal_daemon#355]
When I enable thermald via systemd on bootup I get the following message: "NO RAPL sysfs present" and it does not work properly. Is there a known trigger for systemd that it does reliably start and function correctly? Currently I am helping myself with a delay, but this is of course not optimal:

```
[Service]
ExecStartPre=/bin/sleep 15
```

Perhaps someone has a better solution for this.

**Comment by benzea** [comment]
What is it we need to wait for, I could see the following possibilities right now:
 1. Fix it in thermald to watch for the uevent
 2. Add a udev rule which enables systemd when RAPL appears (something like `ACTION=add SUBSYSTEM==powercap DEVPATH==/devices/virtual/powercap/intel-rapl SYSTEMD_WANTS+=thermald.service`)
 3. Add `Wants=`/`After=` on ` systemd-modules-load.service` and possibly add a pre script with `udevadm settle`
