### ISSUE TITLE
cthd_engine_default::read_thermal_sensors() is enumerating the cpu thermal sensors incorrectly

### ISSUE THREAD

**Issue by SSchloetzer** [intel/thermal_daemon#356]
The problematic code is this (thermal_daemon v2.4.9).

```

int sensor_mask = 0x0f;

// ....


int cnt = 0;
unsigned int mask = 0x1;
do {
	if (sensor_mask & mask) {
		std::stringstream temp_input_str;
		std::string path = base_path[i] + entry->d_name
				+ "/";
		csys_fs dts_sysfs(path.c_str());
		temp_input_str << "temp" << cnt << "_input";
		if (dts_sysfs.exists(temp_input_str.str())) {
			cthd_sensor *sensor = new cthd_sensor(index,
					base_path[i] + entry->d_name + "/"
							+ temp_input_str.str(), "hwmon",
					SENSOR_TYPE_RAW);
			if (sensor->sensor_update() != THD_SUCCESS) {
				delete sensor;
				closedir(dir);
				return THD_ERROR;
			}
			sensors.push_back(sensor);
			++index;
		}
	}
	mask = (mask << 1);
	cnt++;
} while (mask != 0);

```

The code tries to instantiate cthd_sensor instances for all thermal sensors via the kernel's coretemp driver.

So inside the code I omitted, the function is looking for the /sys/class/hwmon/hwmonX folder where /sys/class/hwmon/hwmonX/name = coretemp.

In my case thats hwmon5.

```
$ cat /sys/class/hwmon/hwmon5/name
coretemp
```

Now let us list all cpu thermal sensors on my machine (cpu is an i5-1135G7).

```
$ grep '' /dev/null /sys/class/hwmon/hwmon5/temp*_label
/sys/class/hwmon/hwmon5/temp1_label:Package id 0
/sys/class/hwmon/hwmon5/temp2_label:Core 0
/sys/class/hwmon/hwmon5/temp3_label:Core 1
/sys/class/hwmon/hwmon5/temp4_label:Core 2
/sys/class/hwmon/hwmon5/temp5_label:Core 3
```

The faulty code will only be able to instantiate 3 cthd_sensor instances for my cpu's thermal sensors. temp1_input for the package and temp2_input and temp3_input for cores 0 and 1. This is due to the check "if (sensor_mask & mask) ... mask = (mask << 1);". My guess is that sensor_mask was supposed to be used for some additional feature, that has never been implemented. But it effectively filters out all tempX_input files where X > 3.

A more general issue not affecting me with my puny cpu, is that the loop can only count from 0 to 31 due to "mask = (mask << 1); ... while (mask != 0);" and mask being an unsigned int. This will be an issue for monster cpus like the Xeon Gold 6314U. First because there will also be package level sensors. Second because sensor enumeration might not start from 0. And last but not least: I wouldn't count on sensor enumeration being contiguous.

Let me elaborate on the last point. According to the kernel documentation at https://www.kernel.org/doc/html/v5.18/hwmon/coretemp.html?highlight=core_id the X in tempX_label is supposed to be ther core_id. This is not correct on my machine. The number inside the label file seems to be the actual core_id.

```
$ cat /sys/devices/system/cpu/cpu*/topology/core_id | sort -n | uniq
0
1
2
3
```

But nevertheless, whatever the X in tempX_label, tempX_input, ...  is. It might be related to core_id somehow. And core_id will be non-contiguous with some cpus. Have a look here https://serverfault.com/questions/866573/cpu-core-id-values-not-contiguous and inside this paper https://www.researchgate.net/publication/348937616_Observations_on_Core_Numbering_and_Core_ID's_in_Intel_Processors.

So my proposal to fix the code in a safe and future proof manner would be to enumerate all files that start with "temp" and end with "_input" and instantiate a cthd_sensor instance for each one.

I could make a pull request for this, if you like so.

**Comment by spandruvada** [comment]
Always prefer some volunteers to develop, so please do!

**Comment by SSchloetzer** [comment]
Okay. Thank you. I did create the pull request at: https://github.com/intel/thermal_daemon/pull/358
