### ISSUE TITLE
upower dependency on Clear Linux

### ISSUE THREAD

**Issue by Proulx-S** [intel/thermal_daemon#368]
I am trying to run thermald on Clear Linux server, but it seems to depend on a missing upower service. Clear Linux's swupd suggests the desktop bundle, which [does contain upower](https://clearlinux.org/software/bundle/desktop), but is darn big.

Do I really need upower?

Any way to install just upower with the full desktop bundle?

It does not feel right to have to install the full desktop bundle to be able to use thermald. Headless environments need thermal love too.

Thanks for any help!

--------------
Details on how I got there:

Following [Clear Linux's docs](https://docs.01.org/clearlinux/latest/guides/maintenance/cpu-performance.html#thermal-management), I installed thermald with `sudo swupd bundle-add thermal_daemon` and launched it with `sudo systemctl enable --now thermald upower`. The status hints at the missing upower service:
```
bass@arnold-monero~ $ sudo systemctl status thermald
● thermald.service - Thermal Daemon Service
     Loaded: loaded (/usr/lib/systemd/system/thermald.service; enabled; vendor preset: disabled)
     Active: active (running) since Fri 2022-07-29 03:24:59 UTC; 16min ago
   Main PID: 13721 (thermald)
      Tasks: 4 (limit: 38227)
     Memory: 3.3M
     CGroup: /system.slice/thermald.service
             └─13721 /usr/bin/thermald --systemd --dbus-enable --adaptive

Jul 29 03:24:59 arnold-monero systemd[1]: Starting Thermal Daemon Service...
Jul 29 03:24:59 arnold-monero thermald[13721]: 22 CPUID levels; family:model:stepping 0x6:a5:5 (6:165:5)
Jul 29 03:24:59 arnold-monero systemd[1]: Started Thermal Daemon Service.
Jul 29 03:25:00 arnold-monero thermald[13721]: Couldn't connect to proxy: Error calling StartServiceByName for org.freedesktop.UPower: Unit upower.service not found.
Jul 29 03:25:00 arnold-monero thermald[13721]: Unable to find a zone for B0D4
Jul 29 03:25:00 arnold-monero thermald[13721]: Polling mode is enabled: 4

```
Clear Linux's package manager suggests the following:
```
bass@arnold-monero~ $ sudo swupd search upower
Component upower has version 0.99.20

Bundle with the best search result:
     desktop                        	- Run the GNOME GUI desktop environment.  (568MB) 

This bundle can be installed with:

  swupd bundle-add  desktop

Alternative bundle options are
     desktop-kde                    	- Applications for the desktop from the KDE ecosystem.  (745MB) 
     desktop-dev                    	- All packages required to build the desktop bundle.  (3288MB) 
     service-os-dev                 	- All packages required to build the service-os bundle.  (627MB) 
```

**Comment by spandruvada** [comment]
There are power message for AC/DC is provided by upower. Depending on the thermal config, this may be required.
