### ISSUE TITLE
thermald WARN CPUID levels; family:model:stepping 0x6:6a:6 (6:106:6)

### ISSUE THREAD

**Issue by zhanglei-mao** [intel/thermal_daemon#372]
One of our partner get below text from syslog which seems similar to issues of this: 
  [https://github.com/intel/thermal_daemon/issues/275]
Please check if this CPUID have been added to the table too. 

grep thermald var/log/syslog
Aug 31 18:47:45 ubuntu thermald[1974]: [WARN]27 CPUID levels; family:model:stepping 0x6:6a:6 (6:106:6)
Aug 31 18:47:45 ubuntu thermald[1974]: [WARN] Need Linux PowerCap sysfs
Aug 31 18:47:45 ubuntu thermald[1974]: I/O warning : failed to load external entity "/etc/thermald/thermal-conf.xml"
Aug 31 18:47:45 ubuntu thermald[1974]: [WARN]error: could not parse file /etc/thermald/thermal-conf.xml
Aug 31 18:47:45 ubuntu thermald[1974]: [WARN]Unsupported cpu model, use thermal-conf.xml file or run with --ignore-cpuid-check
Aug 31 18:47:45 ubuntu thermald[1974]: [ERR]THD engine start failed
Aug 31 18:47:45 ubuntu systemd[1]: thermald.service: Succeeded.

**Comment by spandruvada** [comment]
That is a IceLake X server. Thermald is not for such server systems.
