### ISSUE TITLE
Laptop's fans high speed even under light loads

### ISSUE THREAD

**Issue by TmDobbin** [intel/thermal_daemon#375]
Hi, my ASUS Vivobook S513EA seems to spin up the fans even just sitting on desktop at idle. `systemctl status thermald` returns some errors:
```
thermald[7884]: sensor id 11 : No temp sysfs for reading raw temp
thermald[7884]: sensor id 11 : No temp sysfs for reading raw temp
thermald[7884]: sensor id 11 : No temp sysfs for reading raw temp
thermald[7884]: Unsupported condition 41 (Screen_state)
thermald[7884]: Unsupported condition 50 (User_presence)
thermald[7884]: Unsupported conditions are present
thermald[7884]: Polling mode is enabled: 4
thermald[7884]: Manufacturer didn't provide adequate support to run 
thermald[7884]: optimized configuration on Linux with open source
thermald[7884]: You may want to disable thermald on this system if you see issue
```
Any support appreciated!

**Comment by spandruvada** [comment]
May be try some fan control programs. Google search shows some asus-fan-control program.

**Comment by TmDobbin** [comment]
Unfortunately, my model is incompatible with such programs. Perhaps this isn't an issue with thermald, but the "Manufacturer didn't provide adequate support to run optimized configuration on linux" seemed strange.
