### ISSUE TITLE
Incompatibility with any other software?

### ISSUE THREAD

**Issue by dramirezRT** [intel/thermal_daemon#384]
Hello, 
Is thermald incompatible with TLP or auto-cpufreq?

TLP and auto-cpufreq are not compatible to run on same system, since one program modifications can step on the others.

But am not sure if that's the case with thermald and any of these two suggestions, or any other?

Thanks in advance

**Comment by spandruvada** [comment]
Hi,
Thermald should be mostly fine. In some cases it will use cpufreq to control, but that is after package power control is not working.
