### ISSUE TITLE
Issues with thermald and real time kernel.

### ISSUE THREAD

**Issue by rvega** [intel/thermal_daemon#39]
Hi, I'm using a real time kernel from Debian testing repos. 3.14-2-rt-amd64 on a MacBook Pro 8,1.
After installing thermald either from the Debian repos or from the master branch of this repo, I get errors as the following in dmesg and in syslog. Full output of dmesg is at https://gist.github.com/rvega/c72883dc1de40857b7ac. I also posted this to https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=761290

[   39.776121] BUG: scheduling while atomic: Xorg/1007/0x00010001
[   39.776123] BUG: scheduling while atomic: swapper/2/0/0x00010002
.....
[   39.776221] CPU: 1 PID: 1007 Comm: Xorg Tainted: P           O 3.14-2-rt-
amd64 #1 Debian 3.14.15-2
[   39.776222] Hardware name: Apple Inc. MacBookPro8,1/Mac-94245B3640C91C81,
BIOS    MBP81.88Z.0047.B27.1201241646 01/24/12
[   39.776223]  ffff88026401db20 ffffffff814e04fc ffff88026401db20
ffffffff814dce83
[   39.776224]  ffffffff814e2cd8 0000000000065340 0000000000065340
ffff88026392ffd8
[   39.776225]  ffff88026401db20 ffff880267083ee0 ffff88026401e278
ffff88026401db20
[   39.776225] Call Trace:
[   39.776230]  <IRQ>  [<ffffffff814e04fc>] ? dump_stack+0x4a/0x75
[   39.776232]  [<ffffffff814dce83>] ? __schedule_bug+0x96/0xa3
[   39.776234]  [<ffffffff814e2cd8>] ? __schedule+0x5f8/0x670
[   39.776235]  [<ffffffff814e2d77>] ? schedule+0x27/0xa0
[   39.776237]  [<ffffffff814e4335>] ? rt_spin_lock_slowlock+0xb5/0x220
[   39.776240]  [<ffffffffa0cf8ada>] ?
pkg_temp_thermal_platform_thermal_notify+0x3a/0x126 [x86_pkg_temp_thermal]
[   39.776242]  [<ffffffff8103b140>] ? therm_throt_process+0x10/0x140
[   39.776243]  [<ffffffff8103b471>] ? intel_thermal_interrupt+0x201/0x240
[   39.776244]  [<ffffffff8103b4f8>] ? smp_thermal_interrupt+0x18/0x40
[   39.776247]  [<ffffffff814edadd>] ? thermal_interrupt+0x6d/0x80
[   39.776249]  <EOI>  [<ffffffff814ec9fd>] ?
system_call_fast_compare_end+0x10/0x15
[   39.776251] CPU: 2 PID: 0 Comm: swapper/2 Tainted: P        W  O 3.14-2-rt-
amd64 #1 Debian 3.14.15-2
[   39.776252] Hardware name: Apple Inc. MacBookPro8,1/Mac-94245B3640C91C81,
BIOS    MBP81.88Z.0047.B27.1201241646 01/24/12
[   39.776253]  ffff8802655c32a0 ffffffff814e04fc ffff8802655c32a0
ffffffff814dce83
[   39.776254]  ffffffff814e2cd8 0000000000065340 0000000000065340
ffff8802655f5fd8
[   39.776255]  ffff8802655c32a0 ffff880267103ee0 ffff8802655c39f8
ffff8802655c32a0
[   39.776255] Call Trace:
[   39.776257]  <IRQ>  [<ffffffff814e04fc>] ? dump_stack+0x4a/0x75
[   39.776259]  [<ffffffff814dce83>] ? __schedule_bug+0x96/0xa3
[   39.776260]  [<ffffffff814e2cd8>] ? __schedule+0x5f8/0x670
[   39.776261]  [<ffffffff814e2d77>] ? schedule+0x27/0xa0
[   39.776263]  [<ffffffff814e4335>] ? rt_spin_lock_slowlock+0xb5/0x220
[   39.776266]  [<ffffffffa0cf8ada>] ?
pkg_temp_thermal_platform_thermal_notify+0x3a/0x126 [x86_pkg_temp_thermal]
[   39.776267]  [<ffffffff8103b140>] ? therm_throt_process+0x10/0x140
[   39.776268]  [<ffffffff8103b471>] ? intel_thermal_interrupt+0x201/0x240
[   39.776269]  [<ffffffff8103b4f8>] ? smp_thermal_interrupt+0x18/0x40
[   39.776271]  [<ffffffff814edadd>] ? thermal_interrupt+0x6d/0x80
[   39.776274]  <EOI>  [<ffffffff813b8b6a>] ? cpuidle_enter_state+0x4a/0xc0
[   39.776276]  [<ffffffff813b8b63>] ? cpuidle_enter_state+0x43/0xc0
[   39.776277]  [<ffffffff813b8c89>] ? cpuidle_idle_call+0xa9/0x220
[   39.776279]  [<ffffffff8101e1c5>] ? arch_cpu_idle+0x5/0x30
[   39.776281]  [<ffffffff810b86c1>] ? cpu_startup_entry+0x91/0x280
[   39.776284]  [<ffffffff810434e7>] ? start_secondary+0x1d7/0x280

**Comment by spandruvada** [comment]
Closing older issues, reopen if you need to.
