### ISSUE TITLE
cpu zone temp reading loop is off by 1

### ISSUE THREAD

**Issue by fhriley** [intel/thermal_daemon#391]
The [loop starts at 0](https://github.com/intel/thermal_daemon/blob/a61fc4267d61ef64dd213805433bb430c2ca23df/src/thd_zone_cpu.cpp#L61), but the [sysfs is defined to start at 1](https://www.kernel.org/doc/Documentation/hwmon/sysfs-interface) (see the "Temperatures" section).

**Comment by spandruvada** [comment]
Please submit a change.
