### ISSUE TITLE
build warning, ret is assigned but never changed on a sysfs write

### ISSUE THREAD

**Issue by ColinIanKing** [intel/thermal_daemon#405]
Just a minor warning, but it would be useful to silence this or actually check if the write failed.

  CXX      src/thermald-thd_cdev_gen_sysfs.o
src/thd_cdev_gen_sysfs.cpp:42:3: warning: Value stored to 'ret' is never read [deadcode.DeadStores]
                ret = cdev_sysfs.write("", 0);
                ^     ~~~~~~~~~~~~~~~~~~~~~~~

**Comment by spandruvada** [comment]
Fixed. Thanks for reporting.
