### ISSUE TITLE
Mention --ignore-cpuid-check in "unsupported" error message

### ISSUE THREAD

**Issue by rdiez** [intel/thermal_daemon#417]
Could you please mention option --ignore-cpuid-check in error message "Unsupported cpu model or platform".

My suggestion would be:

`Unsupported CPU model or platform. Use option --ignore-cpuid-check to disable this compatibility test.`

It is a strange situation. thermald  actually tends to work, most people using it are apparently using --ignore-cpuid-check already, and there are not many practical alternatives anyway.

In any case, you shouldn't need to search on the Internet how to overcome such an error message if you want to try anyway.

Even if you read the man page beforehand, it is not completely clear that "Ignore cpuid check for supported CPU models" would actually clear that hurdle.

**Comment by spandruvada** [comment]
Added to 2.5.8 release.
