### ISSUE TITLE
Question about <index>

### ISSUE THREAD

**Issue by rdiez** [intel/thermal_daemon#419]
In configuration file thermal-conf.xml, under `<TripPoint>`, `<CoolingDevice>`, there is an `<index>` element.

What is it used for?

Some examples on the Internet have sequential indexes 1, 2, and so on. Others skip values, like 1 and then 5.

Do they have to match some other index somewhere else?

**Comment by spandruvada** [comment]
Can you give some example of the element you are refering?

**Comment by rdiez** [comment]
I see now that GitHub's Markdown ate some words. I am talking about the 2 `<index>` elements here:

```
<CoolingDevice>
  <index>1</index>
  <type>intel_powerclamp</type>
  <influence>100</influence>
  <SamplingPeriod>5</SamplingPeriod>
</CoolingDevice>

<CoolingDevice>
  <index>2</index>
  <type>Processor</type>
  <influence>80</influence>
  <SamplingPeriod>5</SamplingPeriod>
</CoolingDevice>

```

**Comment by spandruvada** [comment]
They are just to show order, not used for any relationship.
