### ISSUE TITLE
Can I use thermald to stay below n degrees?

### ISSUE THREAD

**Issue by fhaust** [intel/thermal_daemon#42]
I just noticed that I had thermald installed and running on my arch linux running Dell XPS notebook for quite a while. 

The CPU temperature is constantly around 58°C when idle, still the fan is running constantly. I believe the trigger temperature for the fan is about 50°C. Sadly the `i8k` module doesn't work for this model (can force it but freezes the system every 3 seconds).

So: can I setup thermald to keep the temperature below 50°C in normal conditions?

**Comment by bamonroe** [comment]
Just thought I'd add to this old issue. The way to set an explicit temperature maximum is by using the command
`dbus-send --system --dest=org.freedesktop.thermald /org/freedesktop/thermald org.freedesktop.thermald.SetUserMaxTemperature string:cpu uint32:$max_temp`

where `$max_temp` is your maximum temperature in Celsius in thousands, so if you wanted to cap temperatures to 50C (which is quite low), `max_temp=50000`

You can see a bunch (all?) the dbus commands here: [https://github.com/01org/thermal_daemon/blob/master/tools/thermald_set_pref.sh](https://github.com/01org/thermal_daemon/blob/master/tools/thermald_set_pref.sh)

**Comment by davepuchyr** [comment]
Just to give a bump to this old thread that, seems to me, is a very relevant use case for thermald, I achieved the goal with these config files and root crontab entry:

_thermal-conf.xml_
```
<?xml version="1.0"?>
<!-- https://wiki.gentoo.org/wiki/Toshiba_Radius_12 -->
<ThermalConfiguration>
   <Platform>
      <Name>Intel Powered Laptop</Name>
      <ProductName>*</ProductName>
      <Preference>QUIET</Preference>
      <ThermalZones>
         <ThermalZone>
            <Type>cpu</Type>
            <TripPoints>
               <TripPoint>
                  <SensorType>x86_pkg_temp</SensorType>
                  <Temperature>77000</Temperature>
                  <type>passive</type>
                  <ControlType>SEQUENTIAL</ControlType>
                  <CoolingDevice>
                     <index>1</index>
                     <type>intel_pstate</type>
                     <influence>100</influence>
                     <SamplingPeriod>10</SamplingPeriod>
                  </CoolingDevice>
               </TripPoint>
            </TripPoints>
         </ThermalZone>
      </ThermalZones>
   </Platform>
</ThermalConfiguration>
```
_thermal-cpu-cdev-order.xml_
```
<CoolingDeviceOrder>
	<CoolingDevice>intel_pstate</CoolingDevice>
	<CoolingDevice>rapl_controller</CoolingDevice>
	<CoolingDevice>intel_powerclamp</CoolingDevice>
	<CoolingDevice>cpufreq</CoolingDevice>
	<CoolingDevice>Processor</CoolingDevice>
</CoolingDeviceOrder>
```
_crontab_
```
# temperature is in m°C
@reboot /usr/bin/dbus-send --system --dest=org.freedesktop.thermald /org/freedesktop/thermald org.freedesktop.thermald.SetUserMaxTemperature string:cpu uint32:80000
@reboot /usr/bin/dbus-send --system --dest=org.freedesktop.thermald /org/freedesktop/thermald org.freedesktop.thermald.SetCurrentPreference string:"ENERGY_CONSERVE"
```

I must say that the results of the software are great - a (good) laptop of mine that kept overheating is now perfectly functional - but the entirely [esoteric nature of the config files](https://github.com/01org/thermal_daemon/issues/77) is a problem; hence the need for the crontab.

Anyway, I tested the above config by transcoding an hevc(x265)/aac video into h264/mp3 and got 95+% cpu usage and all sensor temperatures stayed below 80°C after an initial peak above 80°C.

**Comment by spandruvada** [comment]
Closing older issues, reopen if you need to.
