### ISSUE TITLE
Thermald can't run on this platform

### ISSUE THREAD

**Issue by akirataguchi115** [intel/thermal_daemon#420]
Any good guesses what's up? I read something about --ignore-cpu-id but I wanted to check here first since this project is still active.
![image](https://github.com/intel/thermal_daemon/assets/31825085/71c98757-14cb-4d81-9f55-f1bb44defea7)

**Comment by spandruvada** [comment]
On lenovo laptops there is a firmware solution for thermal, where the manufacturer doesn't want thermald to run. 
So to run you have to override with  --ignore-cpu-id.
