### ISSUE TITLE
Support for Thinkpad P15g1 w/ Intel(R) Xeon(R) W-10855M CPU @ 2.80GHz

### ISSUE THREAD

**Issue by anpin** [intel/thermal_daemon#423]
Hi, I'm running Thinkpad P15g1 w/ Intel(R) Xeon(R) W-10855M CPU @ 2.80GHz with nixos on kernerl 6.4.11 and observing this 
```

└[~]> journalctl -xeu thermald
Sep 24 16:30:24 sabbath thermald[1680]: [1695558624][WARN][/sys/devices/platform/thinkpad_acpi/dytc_lapmode] present: Thermald can't run on this platform
Sep 24 16:30:24 sabbath thermald[1680]: [1695558624][MSG]Unsupported cpu model, use thermal-conf.xml file or run with --ignore-cpuid-check
Sep 24 16:30:24 sabbath thermald[1680]: [1695558624][MSG]22 CPUID levels; family:model:stepping 0x6:a5:2 (6:165:2)
Sep 24 16:30:24 sabbath thermald[1680]: [1695558624][WARN][/sys/devices/platform/thinkpad_acpi/dytc_lapmode] present: Thermald can't run on this platform
Sep 24 16:30:24 sabbath thermald[1680]: [1695558624][MSG]Using config file /nix/store/av45nr81fkz3hxy160wflq6rg02lypqw-thermald-2.5.3/etc/thermald/thermal-conf.xml
Sep 24 16:30:24 sabbath thermald[1680]: [1695558624][MSG]Unsupported cpu model, use thermal-conf.xml file or run with --ignore-cpuid-check
Sep 24 16:30:24 sabbath thermald[1680]: [1695558624][MSG]THD engine init failed
Sep 24 16:30:24 sabbath thermald[1680]: [1695558624][MSG]Polling mode is enabled: 4
Sep 24 17:49:25 sabbath thermald[1680]: [1695563365][MSG]Terminating ...
Sep 24 17:49:25 sabbath systemd[1]: Stopping Thermal Daemon Service...
```

After running `dptfxtract` I've got some configs (in attach) and was able to manually start it with `sudo thermald --no-daemon --ignore-cpuid-check --dbus-enable --adaptive --loglevel=debug | tee thermald.log` and the log is attached yet I do not know if the generated config does make any sense or difference 

[thermald.log](https://github.com/intel/thermal_daemon/files/12708753/thermald.log)
[thermald.zip](https://github.com/intel/thermal_daemon/files/12708773/thermald.zip)

**Comment by spandruvada** [comment]
I see a condition set matched and correct tables are loaded. I suggest just use and report if you find issues

**Comment by spandruvada** [comment]
With --adaptive and --ignore-cpuid-check they will be used, you don't have to do anything special.
