### ISSUE TITLE
Couldn't create introspection data: (null):

### ISSUE THREAD

**Issue by kensad-ops** [intel/thermal_daemon#431]
Hi
I install thermald and enable it, after i restart i got this line from `journalctl -p3 -b`
`Jan 24 11:31:59 Nova thermald[2038]: Couldn't create introspection data: (null):`

`sudo systemctl status thermald.service` give me this:
```
Jan 24 11:31:59 Nova systemd[1]: Starting Thermal Daemon Service...
Jan 24 11:31:59 Nova thermald[2038]: 27 CPUID levels; family:model:stepping 0x6:8d:1 (6:141:1)
Jan 24 11:31:59 Nova thermald[2038]: 27 CPUID levels; family:model:stepping 0x6:8d:1 (6:141:1)
Jan 24 11:31:59 Nova thermald[2038]: sensor id 16 : No temp sysfs for reading raw temp
Jan 24 11:31:59 Nova thermald[2038]: sensor id 16 : No temp sysfs for reading raw temp
Jan 24 11:31:59 Nova thermald[2038]: sensor id 16 : No temp sysfs for reading raw temp
Jan 24 11:31:59 Nova thermald[2038]: Polling mode is enabled: 4
Jan 24 11:31:59 Nova thermald[2038]: Couldn't create introspection data: (null):
Jan 24 11:31:59 Nova systemd[1]: Started Thermal Daemon Service.
```

Is there something wrong with thermald or it just normal behavior ? please let me know

**Comment by spandruvada** [comment]
Did you get the latest from github source (not from the archive 2.5.5 generated from the tag)?

**Comment by kensad-ops** [comment]
Hm..... weird it go away after a few day ( thermald still working properly (i guess) with that error). So i'm gonna close this for now but if anyone know what it mean pls let me know
