### ISSUE TITLE
unsupported condition 57 on Dell Inspiron 5502

### ISSUE THREAD

**Issue by guiodic** [intel/thermal_daemon#435]
systemctl status thermald
● thermald.service - Thermal Daemon Service
     Loaded: loaded (/usr/lib/systemd/system/thermald.service; enabled; preset: disabled)
     Active: active (running) since Sun 2024-03-10 12:37:22 CET; 9min ago
   Main PID: 667 (thermald)
      Tasks: 5 (limit: 18838)
     Memory: 6.6M (peak: 8.4M)
        CPU: 363ms
     CGroup: /system.slice/thermald.service
             └─667 /usr/bin/thermald --systemd --dbus-enable --adaptive

mar 10 12:37:21 manjaro systemd[1]: Starting Thermal Daemon Service...
mar 10 12:37:21 manjaro thermald[667]: 27 CPUID levels; family:model:stepping 0x6:8c:1 (6:140:1)
mar 10 12:37:22 manjaro thermald[667]: 27 CPUID levels; family:model:stepping 0x6:8c:1 (6:140:1)
mar 10 12:37:22 manjaro thermald[667]: sensor id 11 : No temp sysfs for reading raw temp
mar 10 12:37:22 manjaro thermald[667]: sensor id 11 : No temp sysfs for reading raw temp
mar 10 12:37:22 manjaro thermald[667]: sensor id 11 : No temp sysfs for reading raw temp
mar 10 12:37:22 manjaro thermald[667]: Unsupported condition 57 (UKNKNOWN)
mar 10 12:37:22 manjaro thermald[667]: Unsupported conditions are present
mar 10 12:37:22 manjaro thermald[667]: Polling mode is enabled: 4
mar 10 12:37:22 manjaro systemd[1]: Started Thermal Daemon Service.

**Comment by guiodic** [comment]
Operating System: Manjaro Linux 
KDE Plasma Version: 5.27.11
KDE Frameworks Version: 5.115.0
Qt Version: 5.15.12
Kernel Version: 6.7.7-1-MANJARO (64-bit)
Graphics Platform: X11
Processors: 8 × 11th Gen Intel® Core™ i5-1135G7 @ 2.40GHz
Memory: 15.4 GiB of RAM
Graphics Processor: Mesa Intel® Xe Graphics
Manufacturer: Dell Inc.
Product Name: Inspiron 5502

**Comment by guiodic** [comment]
[thermald_debug.log](https://github.com/intel/thermal_daemon/files/14550022/thermald_debug.log)

**Comment by spandruvada** [comment]
Thermald can't parse this condition, hence it is unknown. Thermald can't parse all conditions like Windows. But here it has a workaround to still function.
