### ISSUE TITLE
The final dbus-glib clean up- thd_cdev_modem.cpp

### ISSUE THREAD

**Issue by smallorange** [intel/thermal_daemon#437]
Hi,

The basic GDBUS implementation for the thermald was already done but thd_cdev_modem still uses glib-dbus to access ofono service.
According to the DBUS interface name, it was used to manage the Modem and sofia3gr. As far as I know, this platform was already discontinued. (If I'm wrong, please let me know and sorry for the wrong information)
https://www.intel.com/content/www/us/en/products/sku/94227/intel-atom-x3c3235rk-processor-1m-cache-up-to-1-20-ghz/specifications.html

Could thd_cdev_modem.cpp be deprecated from thermald or move all the glib-dbus API to GDBUS?

Thank you.

**Comment by spandruvada** [comment]
Good question. I am willing to do this.

**Comment by smallorange** [comment]
Cool.
Let me prepare the PR for this one.
