### ISSUE TITLE
Questionable implementation of PID controller

### ISSUE THREAD

**Issue by patrakov** [intel/thermal_daemon#44]
(This issue may be invalid, as I am not an expert in control theory, and that's why there is a word "questionable" and not e.g. "wrong" in the title.)

I think that the PID controller output is used in mathematically "improper" way. Here is the code in thermal_daemon/src/thd_cdev.cpp because of which I think so:

```
        if (pid_enable) {
                pid_ctrl.set_target_temp(target_temp);
                ret = pid_ctrl.pid_output(temperature);
                ret += get_curr_state();
                if (ret > get_max_state())
                        ret = get_max_state();
                if (ret < get_min_state())
                        ret = get_min_state();
                set_curr_state_raw(ret, zone_id);
                thd_log_info("Set : %d, %d, %d, %d, %d\n", set_point, temperature,
                                index, get_curr_state(), max_state);
                ret = THD_SUCCESS;
        } else {
```

The questionable line is: ret += get_curr_state();

I.e., because of this questionable line, the output of the PID controller only controls the speed with which e.g. the RAPL power limit is changed. Here is why this looks bad.

For simplicity, let's consider a P-only controller - i.e. the one with Ki = Kd = 0.

The CPU has a massive heatsink. It is heated by the CPU and cooled either passively or with a fan. Let's assume that the heatsink or fan removes heat with the rate proportional to the temperature difference of the heatsink and the air, and that all heat produced by the CPU goes to heating the heatsink. That is:

C \* T' = -K \* (T - T0) + P, where C > 0, K > 0

where T is the CPU temperature, C is the heat capacity of the heatsink, K is related to the "heat conductivity" between the sink and the outside air (which has the temperature T0), and P is the power dissipated by the CPU into the heatsink.

The output of the P-controller (i.e. PID controller with only P-term, and no I or D) is proportional to the difference of the actual CPU temperature T and the desired one Tw, and, due to the questionable line, the time-derivative of the power dissipated by the CPU is proportional to the PID controller output:

P' = A \* (Tw - T), where A > 0 is proportional to the P-term.

Inserting the second equation into the time-derivative of the first one, we get a second-order differential equation for T:

C \* T'' + K \* T' + A \* (T - Tw) = 0

...which is just a linear differential equation for (T - Tw). Of course, this is valid only if the effects of the finite sampling rate can be neglected, which may be false for certain values of A. The most important thing is that the part of the time derivative of the temperature error due to the controller has the opposite sign to the temperature error. This looks more like a pendulum than like a stabilizer, yielding overshoots and not noticing that (e.g. due to suddenly reduced load) the CPU is already cooling by itself.

Still, if the differential equation is valid, its solutions are either decaying exponents or exponentially decaying oscillations, depending on the value of A. So the controller is stable under such conditions. However, the decay time of the oscillations is of the same order as 2C/K, and, in the case with exponents, the worst exponent will have the decay time more than 2C/K. So, with a massive heatsink, the controller is also slow.

That's why the I and D terms, you say. While the D term can indeed provide the needed damping here, including the I term yields a third-order differential equation, which looks scary and brings one more possibility for unstable solutions - and that's still with the questionable assumption that the sampling rate is sufficient.

One more note regarding the questionable line.

The texts on PID controllers usually say that, with a pure P controller, there is a non-zero residual error in the stationary state. However, with implementation in the thermal daemon, this is not the case. This makes me think that you have implemented not a PID, but a I-I^2-P controller (for the lack of the better name due to the double-integral term).

I could understand adding the extra integration step (in the questionable line) if it helped to bring the system into the class where well-known PID tuning methods work (e.g., Ziegler–Nichols method does not work with second-order systems). I have actually tried to tune the PID controller according to this method on my silent PC (with a Streacom FC8 Evo case-heatsink, which is sufficient with a large-enough safety margin to keep the CPU from overheating if one disables Turbo Boost, but is insufficient with Turbo Boost enabled). I found that, even with a sampling interval of 1 second, the controller tuning process fails (yields an unstable controller unless one removes the I term). To be fair, with that line commented out, thermald still works, and the procedure yields a controller that eventually does converge to the target temperature, but exhibits oscillations for a rather long time before doing so, so not exactly a success. This is probably related to the wrong initial value of the I term, which is expected without this line. It does react quickly to adding or removing of burnMMX instances, and generally keeps the temperature within 3 degrees from the target from that point on.

So I guess that the true intent of the questionable line is to make sure that, when the "PID" controller is first activated, P and I terms are approximately correct (by being zero). If this is the case, the I term should be removed, as only original "P" and "D" (corresponding to "I" and "P" with the questionable line removed) terms are useful. Whether or not I guessed the intention correctly, the purpose of the line should be documented in a comment in the code.

Anyway, with the line in place and with P and D coefficients being non-zero, the controller works as it should. And I understand the corresponding differential equation - it is the same as for a damped oscillator.

**Comment by spandruvada** [comment]
Thanks Patrakov. I will look into this.

**Comment by pattop** [comment]
Is there any news on this issue?

**Comment by patrakov** [comment]
No news here

**Comment by cooper151288** [comment]
i made this mistake when writing my own controller. mine was in bash and bc. Haven't learned c++ yet....
I used state=P + I + D
where P=kp * err_now
I_new = I_old + (0.5 * ki *poll interval (err_now + err_ last)) (trapezium rule)
D = kd * (err_now - err_last)/poll interval. weighted averages help smooth the D out too
I needed to put an anti-windup mechanism and initialisation constants in too so it would work. if anyones impatient enough to want a prerelease script, message me.

**Comment by spandruvada** [comment]
Closing older issues, reopen if you need to.

**Comment by cooper151288** [comment]
I'll test this when I have time. Looks like the line that is referred to should be deleted Nothing else needs to be changed by the looks of things, although using the trapezium rule will give you a far better integral. I've tuned the PID with some success by tuning the D term (with P and I set to 0) until there is a steady oscillation, then lowering the D term while increasing the P term. This is consistent with the implementation being a P-I-II controller. What I'd expect to see with that line removed is that I'd be able to repeat the same process but starting with P, then adding some I and using D to ramp the cooling up when the temperature approaches the trip point to avoid overshoot.

**Comment by cooper151288** [comment]
[pidncurses.c.txt](https://github.com/intel/thermal_daemon/files/1183035/pidncurses.c.txt)

here's a really long winded reference in C. I am aware that that program can be made about a quarter of the size, but the PID function works solidly for me. Its basically the same as in my bash script, bashPID, which is long due an update

**Comment by cooper151288** [comment]
I am testing the modification now, with the line removed and also the trapezium rule addition. This seems to work, however the issue of integral windup is here now as expected. This can be dealt with by setting upper and lower bounds to err_sum, but i think that is beyond my level code-wise.

**Comment by cooper151288** [comment]
Please test my patch set and pull when you think its ready. I get better regulation at the expense of a tiny amount of cpu time for the trapezium integral. I am happy to leave my computer alone while it does lots of work on this patchset. Make sure you are careful with the tuning, set the setpoint low until you are happy, then up it again until it is right.
