### ISSUE TITLE
Question: how to stop a fan below a certain temperature

### ISSUE THREAD

**Issue by mferland** [intel/thermal_daemon#442]
I have a fan here controlled via a pwm device. The 'valid' pwm values are between 125 and 255. Below 125, the fan will not start turning and/or exhibit weird behavior (i.e.: moves just a little bit then stops). My question is the following:

How do I express this in thermald? Ultimately, I would like to make the fan stop (PWM = 0) below a certain temperature. So valid PWM vales are: 0, [125..255]. 

I've tried MinState=0 MaxState=0 with a virtual CoolingDevice, and it kinda works, meaning the fan will stop but it never spins back up for some reason. I've also seen thermald set the PWM to '3' even though the MaxState was 0.

Any help appreciated!

**Comment by spandruvada** [comment]
Check https://github.com/intel/thermal_daemon/blob/master/man/thermal-conf.xml.5 example 3.
