### ISSUE TITLE
thermald: Unsupported conditions are present

### ISSUE THREAD

**Issue by metemaddar** [intel/thermal_daemon#443]
**Summary**: Unsupported conditions in thermald during startup

**Description**:
The following thermald message appears during startup:

19:48:52 thermald: Unsupported conditions are present

**System Information**:
- Distribution: Ubuntu 22.04
- Thermald Version: 2.4.9

**Additional Information**:
This message does not seem to impact functionality but should be investigated.

**Comment by spandruvada** [comment]
That is correct. Thermald can't support every condition which a Windows OS can support.
