### ISSUE TITLE
proc_thermal_pci probed failed against Intel LNL with thermal interruppt configured as MSI

### ISSUE THREAD

**Issue by supperrabbit88** [intel/thermal_daemon#448]
With linux-next-20240717, proc_thermal_pci probe failed with Intel LNL.
Also tried the linux-next-20240917, the same issue still happens.

This system thermal interruppt has been configured to use MSI.

Call trace log is as follow:
[    2.932935] proc_thermal_pci 0000:00:04.0: msi enabled:1 msix enabled:0
[    2.933051] proc_thermal_pci 0000:00:04.0: Request IRQ -22 failed
[    2.933709] ------------[ cut here ]------------
[    2.933711] remove_proc_entry: removing non-empty directory 'irq/172', leaking at least 'processor_thermal_device_pci'
[    2.933719] WARNING: CPU: 0 PID: 501 at fs/proc/generic.c:717 remove_proc_entry+0x1b4/0x1e0
[    2.933740]  intel_lpss psmouse nvme_auth ucsi_acpi video intel_ish_ipc idma64 xhci_pci_renesas thunderbolt i2c_hid_acpi typec_ucsi intel_ishtp typec i2c_hid hid wmi pinctrl_intel_platform
[    2.933744] CPU: 0 UID: 0 PID: 501 Comm: (udev-worker) Not tainted 6.10.0-next-20240717-dirty #22
[    2.933747] RIP: 0010:remove_proc_entry+0x1b4/0x1e0
[    2.933749] Code: 90 78 ff ff ff 48 0f 45 c2 49 8b 57 f0 48 89 f1 48 c7 c6 80 3f 25 9c 48 8b 92 a0 00 00 00 4c 8b 80 a0 00 00 00 e8 fc 4d b3 ff <0f> 0b e9 64 ff ff ff 49 8b 77 18 48 c7 c7 70 c6 82 9c e8 e5 4d b3
[    2.933750] RSP: 0018:ffffc0b640433598 EFLAGS: 00010246
[    2.933751] RAX: 0000000000000000 RBX: ffff9e39047e6840 RCX: 0000000000000000
[    2.933752] RDX: 0000000000000000 RSI: 0000000000000000 RDI: 0000000000000000
[    2.933752] RBP: ffffc0b6404335e0 R08: 0000000000000000 R09: 0000000000000000
[    2.933752] R10: 0000000000000000 R11: 0000000000000000 R12: ffff9e39047e68c0
[    2.933753] R13: ffffc0b6404335f6 R14: ffffc0b6404335f6 R15: ffff9e39047e68c8
[    2.933753] FS:  000072ca4aa5c8c0(0000) GS:ffff9e3c7f600000(0000) knlGS:0000000000000000
[    2.933754] CS:  0010 DS: 0000 ES: 0000 CR0: 0000000080050033
[    2.933755] CR2: 00007530978ca920 CR3: 00000001073b8001 CR4: 0000000000f70ef0
[    2.933756] DR0: 0000000000000000 DR1: 0000000000000000 DR2: 0000000000000000
[    2.933756] DR3: 0000000000000000 DR6: 00000000ffff07f0 DR7: 0000000000000400
[    2.933757] PKRU: 55555554
[    2.933757] Call Trace:
[    2.933758]  <TASK>
[    2.933763]  ? show_regs+0x6c/0x80
[    2.933766]  ? __warn+0x8d/0x150
[    2.933769]  ? remove_proc_entry+0x1b4/0x1e0
[    2.933770]  ? report_bug+0x182/0x1b0
[    2.933773]  ? handle_bug+0x51/0xa0
[    2.933775]  ? exc_invalid_op+0x18/0x80
[    2.933778]  ? asm_exc_invalid_op+0x1b/0x20
[    2.933781]  ? remove_proc_entry+0x1b4/0x1e0
[    2.933782]  ? remove_proc_entry+0x1b4/0x1e0
[    2.933783]  unregister_irq_proc+0xf2/0x120
[    2.933785]  free_desc+0x41/0xe0
[    2.933788]  ? irq_domain_free_irqs+0x138/0x1c0
[    2.933790]  irq_free_descs+0x52/0x80
[    2.933793]  irq_domain_free_irqs+0x151/0x1c0
[    2.933795]  msi_domain_free_locked.part.0+0x17e/0x1c0
[    2.933796]  msi_domain_free_irqs_all_locked+0x74/0xc0
[    2.933798]  pci_msi_teardown_msi_irqs+0x50/0x60
[    2.933801]  pci_free_msi_irqs+0x12/0x40
[    2.933803]  pci_free_irq_vectors+0x58/0x70
[    2.933805]  proc_thermal_pci_probe+0x407/0x446 [processor_thermal_device_pci]
[    2.933809]  local_pci_probe+0x44/0xb0
[    2.933812]  pci_device_probe+0xc5/0x280
[    2.933813]  really_probe+0xee/0x3c0
[    2.933817]  __driver_probe_device+0x8c/0x180
[    2.933818]  driver_probe_device+0x24/0xd0
[    2.933819]  __driver_attach+0x10b/0x210
[    2.933821]  ? __pfx___driver_attach+0x10/0x10
[    2.933822]  bus_for_each_dev+0x8a/0xf0
[    2.933824]  driver_attach+0x1e/0x30
[    2.933825]  bus_add_driver+0x14e/0x290
[    2.933826]  driver_register+0x5e/0x130
[    2.933828]  ? __pfx_proc_thermal_pci_driver_init+0x10/0x10 [processor_thermal_device_pci]
[    2.933830]  __pci_register_driver+0x5e/0x70
[    2.933832]  proc_thermal_pci_driver_init+0x23/0xff0 [processor_thermal_device_pci]
[    2.933833]  do_one_initcall+0x5b/0x340
[    2.933836]  do_init_module+0x97/0x290
[    2.933838]  load_module+0x22c3/0x2380
[    2.933841]  init_module_from_file+0x96/0x100
[    2.933842]  ? init_module_from_file+0x96/0x100
[    2.933844]  idempotent_init_module+0x11c/0x2b0
[    2.933846]  __x64_sys_finit_module+0x64/0xd0
[    2.933848]  x64_sys_call+0x218f/0x2650
[    2.933849]  do_syscall_64+0x7e/0x170
[    2.933850]  ? syscall_exit_to_user_mode+0x4e/0x250
[    2.933852]  ? do_syscall_64+0x8a/0x170
[    2.933852]  ? syscall_exit_to_user_mode+0x4e/0x250
[    2.933853]  ? do_syscall_64+0x8a/0x170
[    2.933854]  ? restore_fpregs_from_fpstate+0x3d/0xd0
[    2.933857]  ? switch_fpu_return+0x5c/0x100
[    2.933858]  ? syscall_exit_to_user_mode+0x18d/0x250
[    2.933859]  ? do_syscall_64+0x8a/0x170
[    2.933860]  ? irqentry_exit+0x43/0x50
[    2.933861]  ? sysvec_call_function+0x57/0xc0
[    2.933862]  entry_SYSCALL_64_after_hwframe+0x76/0x7e
[    2.933863] RIP: 0033:0x72ca4a92725d
[    2.933865] Code: ff c3 66 2e 0f 1f 84 00 00 00 00 00 90 f3 0f 1e fa 48 89 f8 48 89 f7 48 89 d6 48 89 ca 4d 89 c2 4d 89 c8 4c 8b 4c 24 08 0f 05 <48> 3d 01 f0 ff ff 73 01 c3 48 8b 0d 8b bb 0d 00 f7 d8 64 89 01 48
[    2.933866] RSP: 002b:00007fffeca900d8 EFLAGS: 00000246 ORIG_RAX: 0000000000000139
[    2.933867] RAX: ffffffffffffffda RBX: 000064b2a372a130 RCX: 000072ca4a92725d
[    2.933867] RDX: 0000000000000004 RSI: 000072ca4ab9f07d RDI: 000000000000001b
[    2.933868] RBP: 00007fffeca90190 R08: 0000000000000040 R09: 00007fffeca90120
[    2.933868] R10: 000072ca4aa03b20 R11: 0000000000000246 R12: 000072ca4ab9f07d
[    2.933869] R13: 0000000000020000 R14: 000064b2a3729370 R15: 000064b2a372bae0
[    2.933870]  </TASK>
[    2.933870] ---[ end trace 0000000000000000 ]---

**Comment by spandruvada** [comment]
This is a kernel issue. Looking into this.

**Comment by spandruvada** [comment]
https://lore.kernel.org/lkml/20240723140228.865919-1-srinivas.pandruvada@linux.intel.com/T/#t

Fixes this kernel issue.
