### ISSUE TITLE
Clock speeds get locked to 800Mhz randomly until restarting thermald

### ISSUE THREAD

**Issue by russelltg** [intel/thermal_daemon#449]
I often (a few times a day) hit a condition where the clock speeds for all cores get stuck at 800Mhz. It generally happens when the system is loaded. When I restart thermald, the clock speeds go back up. 

What info can I gather to help diagnose the issue? 

System information
OS: Arch Linux
Platform: Dell XPS 15 9510
CPU: i9-11900H
Thermald version: 2.5.6
Kernel: 6.9.10-arch1-1

**Comment by spandruvada** [comment]
Can you send logs by running stress workload?
Can you run https://github.com/intel/thermal_daemon/blob/master/test/thermal-debug-dump-fedora.sh or
https://github.com/intel/thermal_daemon/blob/master/test/thermal-debug-dump-ubuntu.sh

and send the tar file it generates?

**Comment by spandruvada** [comment]
If you can't run those scripts:

systemctl disable thermald

Reboot

thermald --no-daemon --loglevel=debug --adaptive --dbus-enable


It will dumpl lot of logs. In another Window run stress workload and till you hit the condition, collect the log, copy and send. It is possible that your terminal buffer may overflow. So you may need to increase.

**Comment by spandruvada** [comment]
I am in process of releasing a new version. I will prefer to address this issue.

**Comment by russelltg** [comment]
I've tried to get logs with no luck, which is really strange. Either I've been really unlucky or it's harder to repro with logging, which would be very strange. 

I also just hit the same issue in Windows on the same laptop (or I think so. It did go away eventually, right around when I started up HWINFO64, not sure if related or not. But clocks were definitely all at 800Mhz), which makes me think maybe it's a lower level issue. 

Nasty issue for such a popular laptop!

**Comment by russelltg** [comment]
It happened again, seems it resolving itself was unrelated to HWINFO64. 
![image](https://github.com/user-attachments/assets/5b6bf922-0f90-4202-9900-b13f90a2b056)

And definitely not because there's no load, I'm currently compiling some software.

**Comment by spandruvada** [comment]
You can atleast turn on --loglevel=info in the service file:
/usr/lib/systemd/system/thermald.service
Add to line
ExecStart=/usr/sbin/thermald --systemd --dbus-enable --adaptive --loglevel=info
And then do
sudo systemctl daemon-reload

Next time it happens, send logs from journal
journalctl -r -u thermald

**Comment by russelltg** [comment]
I did what some on the internet have suggested and power off the system, unplug the battery, press the power button, wait a while, and then reassemble and the issue seems to have gone away. I've had a stable few weeks when otherwise I'd see this at least twice a day. 

Ex: https://forums.bit-tech.net/index.php?threads/solved-laptop-stuck-at-800mhz.338423/

Strange issue!
