### ISSUE TITLE
/sys/devices/system/cpu/cpu0/cpufreq/scaling_available_frequencies doesn't exist

### ISSUE THREAD

**Issue by dannyp777** [intel/thermal_daemon#455]
I am using Linux kernel 6.8.0-40-generic and I don't have the `scaling_available_frequencies` value under `/sys/devices/system/cpu/cpu0/cpufreq/`

It seems that thermald fails to add a cpufreq cooling device from the sysfs if it doesn't find this value. It still allows me to add it via the thermal-conf.xml, but why won't it add it by default if this value is not there?

[thd_cdev_cpufreq.cpp :- line 68](https://github.com/intel/thermal_daemon/blob/13c310ee3149c743aefc6870f08527877a00d5a5/src/thd_cdev_cpufreq.cpp#L68)

**Comment by spandruvada** [comment]
Thermald will pick intel_pstate in this case as this system supports intel_pstate not using acpi_cpufreq with multiple frequencies. 
intel_pstate has global control instead of writing to every CPU.

**Comment by dannyp777** [comment]
Just ignore this. I realised my system started using pstate driver after I upgraded my BIOS, so the pstate driver is managing the scaling frequencies. It makes total sense. I am still learning.
