### ISSUE TITLE
Non-dbus and non-glib builds

### ISSUE THREAD

**Issue by ffainelli** [intel/thermal_daemon#46]
Hi,

I have started forking thermal_daemon to offer a non-DBUS and non-GLIB build since I am using it an embedded context. I would remove DBUS completely (at runtime) and use libevent for the event-loop. Is this something you would be willing to accept as a contribution?

Thanks!

**Comment by spandruvada** [comment]
On Mon, 2015-01-19 at 11:30 -0800, Florian Fainelli wrote:
Hi,
> Hi,
> 
> I have started forking thermal_daemon to offer a non-DBUS and non-GLIB
> build since I am using it an embedded context. I would remove DBUS
> completely (at runtime) and use libevent for the event-loop. Is this
> something you would be willing to accept as a contribution?
Sure. Make sure that the abstraction is clear and not break current
implementation. We can review your implementation, once you have
something ready.

Thanks,
Srinivas

**Comment by spandruvada** [comment]
Closing older issues, reopen if you need to.
