### ISSUE TITLE
Weird CPU usage raising when thermald is running

### ISSUE THREAD

**Issue by wil93** [intel/thermal_daemon#50]
When thermald is running, some tasks tend to require an unusually high percentage of CPU. I noticed this when watching a video (chromium's and firefox's html5 player) on Coursera: it would play perfectly for some time, then start eating up CPU.

This is the "normal" usage when watching a youtube video:

![1](https://cloud.githubusercontent.com/assets/1285361/5892678/1484bb30-a4c8-11e4-884c-bd6a031ee179.png)

This is still the same youtube video playing, but after thermald was started (the CPU usage decreased, not bad):

![2](https://cloud.githubusercontent.com/assets/1285361/5892682/335b7940-a4c8-11e4-94d6-3c303eb39863.png)

This is after some time passed:

![3](https://cloud.githubusercontent.com/assets/1285361/5892683/3fae0d34-a4c8-11e4-9bef-61db66ba7e31.png)

**Comment by spandruvada** [comment]
If still issue, rerun by stopping the service and by command line and attach output.
# thermald --no-daemon --loglevel=info
