### ISSUE TITLE
please provide a client to query the daemon

### ISSUE THREAD

**Issue by rickysarraf** [intel/thermal_daemon#53]
rrs@learner:~$ acpi -V
Battery 0: Discharging, 75%, 05:27:39 remaining
Battery 0: design capacity 4269 mAh, last full capacity 4270 mAh = 100%
Adapter 0: off-line
Thermal 0: ok, 29.8 degrees C
Thermal 0: trip point 0 switches to mode critical at temperature 105.0 degrees C
Thermal 0: trip point 1 switches to mode passive at temperature 108.0 degrees C
Thermal 1: ok, 27.8 degrees C
Thermal 1: trip point 0 switches to mode critical at temperature 105.0 degrees C
Thermal 1: trip point 1 switches to mode active at temperature 100.0 degrees C
Thermal 1: trip point 2 switches to mode active at temperature 55.0 degrees C
Cooling 0: x86_pkg_temp no state information available
Cooling 1: intel_powerclamp no state information available
Cooling 2: Processor 0 of 10
Cooling 3: Processor 0 of 10
Cooling 4: Processor 0 of 10
Cooling 5: Processor 0 of 10
Cooling 6: Fan 1 of 1
Cooling 7: Fan 1 of 1
Cooling 8: Fan 1 of 1
Cooling 9: Fan 1 of 1
Cooling 10: Fan 1 of 1
14:01 ♒♒♒   ☺    

At this time, on the CLI, I use acpi to give me the temperature status. As you can see above, it is incorrect. The thermald project should provide a client to query the daemon on what the current status is for the machine

**Comment by spandruvada** [comment]
There is ThermalMonitor a GUI program release for sometime now.
