### ISSUE TITLE
Question: Arch AUR package

### ISSUE THREAD

**Issue by mkjois** [intel/thermal_daemon#57]
I'm interested in using thermald on an Arch system but the package on AUR is flagged out of date. The top comment suggests using a specific commit of this repo but now there are many more recent commits on master. Will thermald be distributed through AUR again? If not, what version of the code can I use?

**Comment by spandruvada** [comment]
On Thu, 2015-05-07 at 00:06 -0700, Manny Jois wrote:
> I'm interested in using thermald on an Arch system but the package on
> AUR is flagged out of date. The top comment suggests using a specific
> commit of this repo but now there are many more recent commits on
> master. Will thermald be distributed through AUR again? If not, what
> version of the code can I use?
> 
Latest version is 1.4 at
https://github.com/01org/thermal_daemon

**Comment by dennishamester** [comment]
Somewhat related: I just wanted to build this through AUR and noticed that `git describe` still outputs `v1.02-rc1-198-gd8c5278` instead of something related to 1.4. I definitely have the 1.4 tag in my local repo. Does anyone have an idea what's going on?

**Comment by spandruvada** [comment]
On Sun, 2015-05-10 at 06:36 -0700, Dennis Hamester wrote:
> Somewhat related: I just wanted to build this through AUR and noticed
> that git describe still outputs v1.02-rc1-198-gd8c5278 instead of
> something related to 1.4. I definitely have the 1.4 tag in my local
> repo. Does anyone have an idea what's going on?
> 
This is because git describe prefers annotated tags. The last one was
v1.02-rc1.

Pull again I added annotated tag v1.4.2

**Comment by ArchangeGabriel** [comment]
AUR package has been updated. This can be closed.
