### ISSUE TITLE
Question: What is the "Processor" cooling device

### ISSUE THREAD

**Issue by XapaJIaMnu** [intel/thermal_daemon#60]
Hey,

I stumbled upon the file /etc/thermald/thermal-cpu-cdev-order.xml and I have the following available cooling devices

``` xml
    <!-- Specify Cooling device order -->
    <CoolingDevice>rapl_controller</CoolingDevice>
    <CoolingDevice>intel_pstate</CoolingDevice>
    <CoolingDevice>intel_powerclamp</CoolingDevice>
    <CoolingDevice>cpufreq</CoolingDevice>
    <CoolingDevice>Processor</CoolingDevice>
```

What is the Processor device? Is it the fan?

Cheers,

Nick

**Comment by spandruvada** [comment]
Processor device is not a FAN. This is a passive cooling device for processor.
If there is a control for FAN on a platform, it can be

-          /sys/class/thermal/coolingdevice?/ with type == Fan

-          Some platforms have some additional Fan control like on thinkpad

On some platforms, the manufacturer may not want to allow any Fan control.

**Comment by XapaJIaMnu** [comment]
Hey,

Thanks for specifying. All my cooling devices seem to be of type processor:
```bash
cat /sys/class/thermal/cooling_device*/type
Processor
Processor
Processor
Processor
Processor
Processor
Processor
Processor
```

Basically it means that thermald doesn't have a fan device exposed to it so it makes do with the other available options to it?

**Comment by XapaJIaMnu** [comment]
Hey,

Thanks for your time. I already checked, it is not present there. Does it mean then that thermald applies the available passive cooling devices while the bios independently turns on the fan?

**Comment by spandruvada** [comment]
Yes.
