### ISSUE TITLE
logging level is increased since 1.4.3 update

### ISSUE THREAD

**Issue by hadrons123** [intel/thermal_daemon#66]
Is it just me or anybody else see this higher rate of log levels in journal?

Jul 21 19:06:41 archlinux thermald[275]: Read set point 80000
Jul 21 19:06:40 archlinux thermald[275]: thd_trip_cdev_state_reset index 9:rapl_controller
Jul 21 19:06:40 archlinux thermald[275]: thd_trip_cdev_state_reset index 10:intel_pstate
Jul 21 19:06:40 archlinux thermald[275]: thd_trip_cdev_state_reset index 8:intel_powerclamp
Jul 21 19:06:40 archlinux thermald[275]: thd_trip_cdev_state_reset index 0:Processor
Jul 21 19:06:40 archlinux thermald[275]: thd_trip_cdev_state_reset
Jul 21 19:06:40 archlinux thermald[275]: thd_trip_cdev_state_reset index 9:rapl_controller
Jul 21 19:06:40 archlinux thermald[275]: thd_trip_cdev_state_reset index 10:intel_pstate
Jul 21 19:06:40 archlinux thermald[275]: thd_trip_cdev_state_reset index 8:intel_powerclamp
Jul 21 19:06:40 archlinux thermald[275]: thd_trip_cdev_state_reset index 0:Processor
Jul 21 19:06:40 archlinux thermald[275]: thd_trip_cdev_state_reset
Jul 21 19:06:40 archlinux thermald[275]: thd_trip_cdev_state_reset
Jul 21 19:06:40 archlinux thermald[275]: Dropped below poll threshold
Jul 21 19:06:28 archlinux NetworkManager[6591]: <warn>  (wlp2s0): Lowering IPv6 MTU (1500) to match device MTU (1280)
Jul 21 19:05:52 archlinux thermald[275]: Read set point 80000
Jul 21 19:05:51 archlinux thermald[275]: thd_trip_cdev_state_reset index 9:rapl_controller
Jul 21 19:05:51 archlinux thermald[275]: thd_trip_cdev_state_reset index 10:intel_pstate
Jul 21 19:05:51 archlinux thermald[275]: thd_trip_cdev_state_reset index 8:intel_powerclamp
Jul 21 19:05:51 archlinux thermald[275]: thd_trip_cdev_state_reset index 0:Processor
Jul 21 19:05:51 archlinux thermald[275]: thd_trip_cdev_state_reset
Jul 21 19:05:51 archlinux thermald[275]: thd_trip_cdev_state_reset index 9:rapl_controller
Jul 21 19:05:51 archlinux thermald[275]: thd_trip_cdev_state_reset index 10:intel_pstate
Jul 21 19:05:51 archlinux thermald[275]: thd_trip_cdev_state_reset index 8:intel_powerclamp
Jul 21 19:05:51 archlinux thermald[275]: thd_trip_cdev_state_reset index 0:Processor
Jul 21 19:05:51 archlinux thermald[275]: thd_trip_cdev_state_reset
Jul 21 19:05:51 archlinux thermald[275]: thd_trip_cdev_state_reset
Jul 21 19:05:51 archlinux thermald[275]: Dropped below poll threshold

**Comment by spandruvada** [comment]
Your platform constantly reaching thresholds and thermald is taking action. So it is dumping these messages when it is taking action.
Can you send complete log?

Thanks,
Srinivas

**Comment by hadrons123** [comment]
I have run journalctl -r and the output is here.
https://dl.dropboxusercontent.com/u/106654446/journalctl.txt

Let me know if you need anymore logs.

**Comment by deki** [comment]
Same here, I've read that I may change /lib/systemd/system/thermald.service and append a loglevel param to the ExecStart line. But I would appreciate a general fix instead of doing this.

**Comment by reidpr** [comment]
Note that the log lines above are at the `info` level (check the source code), which is currently the minimum according to the man page. I agree with the OP; these add no value to routine logging.

**Comment by spandruvada** [comment]
There are very few logs with default options.
