### ISSUE TITLE
Thermald configuration is retard, please fix

### ISSUE THREAD

**Issue by diegogarciaa** [intel/thermal_daemon#77]
1 - Try to configure your thermald configuration for 3 days straight
2 - Be fucking mad because that shit is a stock pile of shieeet
3 - Riot in github.

**Comment by soul9** [comment]
The documentation is so bad it's not even worth reading. all it gives is three examples, while what we would need is all the different options and the available parameters for them. I don't think it is possible to configure thermald without intimate understanding of the source code.
