### ISSUE TITLE
thermald fails to start: no RAPL

### ISSUE THREAD

**Issue by sos-michael** [intel/thermal_daemon#78]
thermald(on a stock fedora 23 install) simply fails to start complaining about a few things(at the start and at the end):

https://gist.github.com/sos-michael/fb0c7c98730aea16b417#file-thermald

I've tried modprobing intel_rapl:
modprobe: ERROR: could not insert 'intel_rapl': No such device

I know this is not a lot to go on... and it might just be a quirk. But I think something else is up, I'm likely simply missing something obvious, but I'm unsure where else to look.

**Comment by spandruvada** [comment]
This should be fixed now in new release.
